### ISSUE TITLE
Number of test in Sweden

### ISSUE THREAD

**Issue by digimen-ch** [owid/covid-19-data#108]
What happend to the number of tests in Sweden. It looks like most of them are gone. Only from 2020-06-29  to 2020-07-12 in the file.

**Comment by edomt** [comment]
Hi @digimen-ch 

Sweden has changed its reporting methodology—they now report the number of samples tested instead of people tested. The old series is still available in our graphs though: https://pbs.twimg.com/card_img/1283879292330532874/ZwFrcG2B?format=png&name=small
As well as in our testing dataset: https://github.com/owid/covid-19-data/blob/master/public/data/testing/covid-testing-all-observations.csv

See here for more information: https://ourworldindata.org/coronavirus-testing#sweden

Edouard
