### ISSUE TITLE
Total Tests Column is empty

### ISSUE THREAD

**Issue by touradnik9** [owid/covid-19-data#110]

**Comment by touradnik9** [comment]
The column for the total number of tests done is completely empty, but it was not always like this. what happened?

**Comment by breck7** [comment]
Which file are you looking at @touradnik9 ?

In https://covid.ourworldindata.org/data/owid-covid-data.csv I am seeing data in the `total_tests` column:

https://v20.ohayo.computer/?filename=untitled.ohayo&data=web.get%2520https%253A%252F%252Fcovid.ourworldindata.org%252Fdata%252Fowid-covid-data.csv%250A%2520columns.keep%2520location%2520total_tests%250A%2520%2520filter.where%2520total_tests%2520%253E%25200%250A%2520%2520%2520handsontable.basic

**Comment by touradnik9** [comment]
This should not be closed. Sweden has no data on total tests.

**Comment by edomt** [comment]
Hi @touradnik9 

This is normal, see here: https://ourworldindata.org/coronavirus-testing#sweden

**Our first source until early July was the number of people tested (Sweden Public Health Agency).** From the start of the pandemic up until July 2020, the Swedish Public Health Agency provided weekly reports on COVID-19 on the number of people tested. This time series had a cumulative total, but it was discontinued by the Health Agency and we can no longer update it.

**Our second, new source is the number of samples tested (Sweden Public Health Agency).** Since July 2020, the Public Health Agency has replaced its previous weekly updates of the number of people tested with the weekly count of samples tested. **This data does not allow us to publish any cumulative total**, since no data is available on how many samples had been tested prior to the first week of reporting. However, we integrate this data into our “daily tests” time series by dividing each weekly total by 7, thereby estimating the average daily number of samples tested.

Edouard

**Comment by edomt** [comment]
If needed, the first time series (discontinued) is available in our "all testing observations" file: https://github.com/owid/covid-19-data/blob/master/public/data/testing/covid-testing-all-observations.csv
