### ISSUE TITLE
Strategy to fill extreme_poverty

### ISSUE THREAD

**Issue by harrytrinh96** [owid/covid-19-data#111]
Can someone me how to fill the missing values of  `extreme_poverty`?

**Comment by edomt** [comment]
Hi @harrytrinh96 

The `extreme_poverty` column contains the share of the population living in extreme poverty, most recent year available since 2010. The data comes directly from the World Bank World Development Indicators, sourced from the World Bank Development Research Group. Missing values mean that no data on extreme poverty is available for those countries.

Edouard
