### ISSUE TITLE
Excess Mortality Tabe - Data for 2021 mortality is on the wrong line 

### ISSUE THREAD

**Issue by AMI3** [owid/covid-19-data#1112]
it seems that 2021 mortality is shown on the 2020 lines:
The column "death 2021 all ages" has data on the lines that match the 2020 time and not on the corresponding 2021 week/month

Armenia for example:
(data is present only for the 2020 dates, but seems to correlate to the 2021 months)

location | date             | deaths_2020_all_ages | deaths_2021_all_ages | time
Armenia | 31/03/2021 |                                    |                                     | 3
Armenia | 28/02/2021 |                                    |                                     | 2
Armenia | 31/01/2021 |                                    |                                     | 1
Armenia | 31/12/2020 | 4395                           |                                     | 12
Armenia | 30/11/2020 | 6060                           |                                     | 11
Armenia | 31/10/2020 | 3632                           |                                     | 10
Armenia | 30/09/2020 | 2042                           |                                     | 9
Armenia | 31/08/2020 | 2106                           |                                     | 8
Armenia | 31/07/2020 | 2719                           |                                     | 7
Armenia | 30/06/2020 | 2869                           |                                     | 6
Armenia | 31/05/2020 | 2103                           |                                     | 5
Armenia | 30/04/2020 | 2156                           |                                     | 4
Armenia | 31/03/2020 | 2288                           |                                     | 3
Armenia | 29/02/2020 | 2434                           | **2665**                       | 2
Armenia | 31/01/2020 | 2567                           | **3295**                       | 1

and Austria:
(data is present only for the 2020 weeks, but seems to correlate to the 2021 weeks - were there is no data)

location | date | deaths_2020_all_ages | deaths_2021_all_ages | time | time_unit
Austria | 22/03/2020 | 1836 | **1599** | 12 | weekly
Austria | 15/03/2020 | 1718 | **1675** | 11 | weekly
Austria | 08/03/2020 | 1744 | **1741** | 10 | weekly
Austria | 01/03/2020 | 1768 | **1578** | 9 | weekly
Austria | 23/02/2020 | 1719 | **1662** | 8 | weekly
Austria | 16/02/2020 | 1721 | **1718** | 7 | weekly
Austria | 09/02/2020 | 1682 | **1758** | 6 | weekly
Austria | 02/02/2020 | 1947 | **1866** | 5 | weekly
Austria | 26/01/2020 | 1779 | **1948** | 4 | weekly
Austria | 19/01/2020 | 1797 | **2008** | 3 | weekly
Austria | 12/01/2020 | 1702 | **1958** | 2 | weekly
Austria | 05/01/2020 | 1614 | **1960** | 1 | weekly

**Comment by CGiattino** [comment]
Hi @AMI3,

Thanks for writing.

The dates and how everything is organized is a bit confusing — I'll try to clarify this more in the readme.

The "deaths_" columns data over the years is primarily organized according to the "time" column — this number refers either to the week number or month number in that year (depending on the "time_unit" column). The dates for months in different years are essentially the same (save for leap years), but the dates for weeks vary a little from year to year. You can see that [here](https://www.epochconverter.com/weeks/2021). Because of this, the "date" column dates are only correct for "deaths_2020_all_ages."

The various "p_scores_" columns, however, _do_ match the dates in the "date" column for both 2020 and 2021 dates. The main reason for the difference here is how we visualize these data on our site — the [p_scores_ charts](https://ourworldindata.org/grapher/excess-mortality-p-scores) have dates at the bottom that continue into 2021, while the [raw deaths chart](https://ourworldindata.org/grapher/excess-mortality-raw-death-count) just has the 2020 dates at the bottom, and 2021 data overlaid on top of that.

Hope that makes sense. Let me know if you have any more questions.

Best,
Charlie
