### ISSUE TITLE
VAX: Data inconsistencies in Panama

### ISSUE THREAD

**Issue by lucasrodes** [owid/covid-19-data#1144]
## Context
- Data inconsistencies between multiple official sources: [@MINSAPma](https://twitter.com/MINSAPma) and [official dashboard](https://vacunas.panamasolidario.gob.pa/). The reported number of total administered doses appears to be lower in Twitter's announcements.
- Inconsistencies are quite large. As of 22 April 2021 12:38 PM (UTC):
    - [@MINSAPma's announcement](https://twitter.com/MINSAPma/status/1385028828918075394?s=20): 574212 total administered doses.
    - [Dashboard](https://vacunas.panamasolidario.gob.pa/vacunometro): 542875 total administered doses.

<img src="https://user-images.githubusercontent.com/18101289/115715595-340f1380-a370-11eb-990e-0f0badafec3c.png " width="450" />
<img src="https://user-images.githubusercontent.com/18101289/115715562-2a85ab80-a370-11eb-8718-62844907e587.png" width="350" />

## Actions
- Continue to solely rely on the [@MINSAPma](https://twitter.com/MINSAPma/status/1385028828918075394?s=20) announcements until data in both sources are more or less consistent.
- Once both sources are considered more or less aligned, data import automation would be appreciated from the [official dashboard](https://vacunas.pa)

**Comment by mmorenoc25** [comment]
Perfect, then we would continue with the parts of the official communiqués found on the website of the ministry, but I am also concerned about the issue of the second dose on These will be extracted from the Vaccine Meter What is the only official source with a second dose, I am also concerned about the Google issue in which it only appears in 5 days of vaccination and not the 72 By having entered the information of the second dose, it only interprets that information as valid and the rest of the lines that remain empty do not qualify as vaccination days, despite  having dispensed doses that day. He was attentive to all the comments and I appreciate the interest, since as we know this platform is widely used to compare numbers worldwide, especially in a subject as sensitive as that of Vaccination against COVID-19.

**Comment by lucasrodes** [comment]
As of today, discrepancies remain

<img src="https://user-images.githubusercontent.com/18101289/115898468-7e1df500-a455-11eb-85da-1ff1f11603d9.png " width="450" />
<img src="https://user-images.githubusercontent.com/18101289/115898502-89712080-a455-11eb-9402-6c465b441c54.png" width="350" />

**Comment by mmorenoc25** [comment]
That's right, from what I see the difference will exist for a long time without that difference of 25000 being permanently maintained, so I propose that in total doses it be extracted from the daily reports, and that the second dose is extracted from the Vaccine Meter because they confirmed that this figure is 100% accurate, because once the person applies the second dose, it is mandatory to present the identification card, and once the card is presented and it is scanned, it is immediately placed in the vaccine meter, so I propose that we use the second dose of the vaccine meter and the totals from the daily report.

**Comment by lucasrodes** [comment]
Thanks for your contributions,  @mmorenoc25.
For now, we will be getting official numbers from Twitter announcements and second doses from the vacunómetro.

**Comment by mmorenoc25** [comment]
Thank you very much, in the next few days I will submit a letter to the National Government Innovation Authority (AIG), the government institution in charge of the vaccine meter. and the Ministry of Health (MINSA) to request that the information in the vaccine meter be corrected in time of the law and that they also present a daily report of the doses on Twitter with the information required for the right that assists us in requesting public information as well as that of the previous days in order to obtain the most complete and accurate information and once they respond within 30 calendar days maximum I would share it immediately. Thank you very much and extremely grateful for the support and interest given to Panama. Greetings and blessings.

**Comment by lucasrodes** [comment]
Thanks, @mmorenoc25 for actively asking for better and more reliable data! Let's hope that we will get some answers soon.
Que tengas un muy buen día, ¡Saludos!

**Comment by lucasrodes** [comment]
For maintenance, we are switching to the source https://vacunas.panamasolidario.gob.pa/vacunometro.

**Comment by Javierpedatos** [comment]
The data on the page, https: //vacunas.panamasolidario.gob.pa/vacunometro, are outdated compared to the Twitter account of the Ministry of Health of Panama. While in the vaccine that is taken as a source, the application of 4.67 million is presented in the last report on the website, the data is 4.95 million. The idea of ​​the user @mmorenoc25  should be carried out Extract the data of administered doses from the twitter page and the first and second doses from the vaccine meter .

https://twitter.com/MINSAPma/status/1434702168037146627/photo/1

**Comment by lucasrodes** [comment]
Hi @Javierpedatos. 
Thanks for your feedback.

We have been following the approach stated in https://github.com/owid/covid-19-data/issues/1144#issuecomment-826076480 for some months now. We have been waiting for the _vacunometro_ to catch up for some months now, and now need to switch to it.

We prefer the _vacunometro_ over Twitter feeds, as it provides an automatable way of importing the data. This may not seem relevant in the context of Panamá, but it is in the context of the more than 220 data imports that we need to do on a daily basis.

We expect that the Government of Panamá will soon align both data sources.

**Comment by Javierpedatos** [comment]
I have a question, today the Ministry of Health of Panama in a public conference published the number of doses administered, first and second doses. My question is, can the data be published with these numbers without altering the link? Leaving the link of the vaccine meter 



![image](https://user-images.githubusercontent.com/79803615/132428204-77ea10da-40bd-4e9d-8df4-ee1a46f1bce1.png)

**Comment by edomt** [comment]
Hi @Javierpedatos 

The issue isn't what link we show in our data, it's the process by which we collect this data. See this message from @lucasrodes above:

> We prefer the vacunometro over Twitter feeds, as it provides an automatable way of importing the data. This may not seem relevant in the context of Panamá, but it is in the context of the more than 220 data imports that we need to do on a daily basis.

**Comment by 8913409nhocac7** [comment]
Vào 13:10, CN, 25 thg 4, 2021 mmorenoc25 ***@***.***> đã viết:
