### ISSUE TITLE
Spain data is always 1 day behind?

### ISSUE THREAD

**Issue by dbaroncelli** [owid/covid-19-data#122]
I have just realized that every day, Spain data is always 1 day behind. It never has the record with the current day.
Is this a bug?

**Comment by edomt** [comment]
Hi @dbaroncelli 

This is not a bug, it's due to the way that Spain reports its cases & deaths: unlike other countries that report the daily count at the end of the day (or early in the morning for the previous day), Spain reports with a lag of 24 hours. So the August 9 update of the European CDC includes cases & deaths in Spain up to August 7.
