### ISSUE TITLE
field "tests_units" reports the value "tests performed" instead of a number

### ISSUE THREAD

**Issue by dbaroncelli** [owid/covid-19-data#124]
in some cases (for example Germany),
field "tests_units" reports the value "tests performed" instead of a number

**Comment by edomt** [comment]
Hi @dbaroncelli 
This is intentional: as explained in our [codebook](https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-codebook.csv), `tests_units` contains the **Units used by the location to report its testing data**. The numbers themselves are available in various other columns (`total_tests`, `new_tests`, `new_tests_smoothed`, etc.)
Edouard
