### ISSUE TITLE
OWID_WRL calculations

### ISSUE THREAD

**Issue by stark71** [owid/covid-19-data#127]
CSV and JSON from 2020-08-19:
When I try to calculate OWID_WRL by my self I can't get your figures.

Date: 2020-08-18

total_cases:
 - Your calculation=21_901_632.
 - When I sum all the total_cases for all the countries (HK is missing btw) I get 21_900_936.
  - 696 are missing!

population: 44_315_622 missing!

Regarding *_per_million (total_deaths_per_million, new_deaths_per_million, etc.)
How do you calculate OWID_WRL?
  - Averaging by number of countries
  - sum_for_each_country(country_value * (country_population / 1_000_000) )/ cardinal(countries)

What about demographic data (median age, population density, gdp per capita, etc)

Could you document your calculations?

Thank you for your work.

**Comment by edomt** [comment]
Hi @stark71 

The reasons for those discrepancies are different, so I'll reply for each.

### 696 missing for total cases

These 696 cases belong to the "International" group, i.e. they're cases that weren't attributed to a particular country. I've fixed our code so that these totals are now carried forward from the last date they were counted (March 10), which should solve the issue.

Note that Hong Kong is included by the European CDC as part of the figures for China.

### World population

The total world population isn't calculated but rather taken directly from the UN estimate available here: https://github.com/owid/covid-19-data/blob/master/scripts/input/un/population_2020.csv
The difference of 44 million is due to the fact that not every country in the world has reported cases & deaths figures for COVID-19.

### World figures per capita

These are calculated by adding up the metric (e.g. total_deaths) across all countries, then dividing the result by the world population (UN estimate).

### Demographic data

The demographic data is imported from various sources. See here for the complete list in our codebook: https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-codebook.csv

Edouard
