### ISSUE TITLE
SWE testing data reliable? 

### ISSUE THREAD

**Issue by RaMateQalo** [owid/covid-19-data#130]
Hi, 

Thank you for your efforts to gather covid-19 related data. 
I have issue with Swedish data, earlier, I retrieved data on 1/07/2020 where Sweden had data (not necessarily daily, but at least weekly values) for variables  total_tests and total_tests_per_thousand, in the recent edition, I see that the values for these variables are empty, not only the new series, but entire variable is just missing data. 
Could you please kindly share what is the reason for it?

**Comment by edomt** [comment]
Hi @RaMateQalo 

This is normal, see here: https://ourworldindata.org/coronavirus-testing#sweden

Our first source until early July was the number of people tested (Sweden Public Health Agency). From the start of the pandemic up until July 2020, the Swedish Public Health Agency provided weekly reports on COVID-19 on the number of people tested. This time series had a cumulative total, but it was discontinued by the Health Agency, and we can no longer update it.

Our second, new source is the number of samples tested (Sweden Public Health Agency). Since July 2020, the Public Health Agency has replaced its previous weekly updates of the number of people tested with the weekly count of samples tested. This data does not allow us to publish any cumulative total, since no data is available on how many samples had been tested prior to the first week of reporting. However, we integrate this data into our “daily tests” time series by dividing each weekly total by 7, thereby estimating the average daily number of samples tested.

Edouard
