### ISSUE TITLE
Suriname data fields switched

### ISSUE THREAD

**Issue by martinstabe** [owid/covid-19-data#1312]
Hi, and thank you for your invaluable work.

It appears that the vaccination data for Suriname after 2021-05-05 has been recorded in the wrong fields, perhaps due to a change of the structure of the [source website](https://laatjevaccineren.sr/). 

The `people_vaccinated` figure appears to refer to the value for total vaccination doses according to the website, while the `people_fully_vaccinated` value is actually the number of people having received the first dose. The calculated sum for `total_vaccinations` is therefore generating an incorrect value. The correct value for `people_fully_vaccinated` is 502 for 2021-05-08. I logged it yesterday as 216 on 2021-05-07.

**Comment by lucasrodes** [comment]
Hi @martinstabe,
Thanks for reporting this.

Apparently, this was due to a small change in the https://laatjevaccineren.sr/ HTML code. A new field reporting `total_vaccinations` has been added. This made our script wrongly report `people_vaccinated` as the total number of administered doses and `people_fully_vaccinated` as the number of people with at least one dose. This has now been corrected in a7f384826f8f3d7993b2b867488e80a7583d9748 and our [charts](https://ourworldindata.org/explorers/coronavirus-data-explorer?Metric=People+fully+vaccinated&Interval=Cumulative&Relative+to+Population=true&Align+outbreaks=false&country=~SUR) on our website.

Thanks!
