### ISSUE TITLE
Swedish data is not correct

### ISSUE THREAD

**Issue by hewwra** [owid/covid-19-data#134]
When I looked at the new covid-19 cases it looked like it dropped off a cliff, the number of case are indeed going down but as fast as the graph would suggest. 

I download xlsx file from this github and it says that the number of cases are 60 for the last day.
This is not true, the cases for Thursday are currently 134.
I assume the reason for this error is that Sweden has recently found som cases were falsely identified as positive and this is now being corrected.
One additional thing is that the cases for Thursday is currently 134 but that will most certainly be additional cases reported for Thursday in the next update (Monday)  meaning if you use this data the last day will almost always be inaccurate since cases for Thursday will be reported on Friday & Monday.
 
In the past you used the total number of cases reported for a day regardless of they happened on Thursday or Wednesday, in the last update published by the authorities that would be 134 for Thursday and 75 for Wednesday for a total of 209.

Now I can't say exactly how many actual cases happened on Thursday but its definitely not 60 and it should be more then 134. It probably wont be exactly 209 cases but its probably the closest we can get based on the data we have available. 

The data for the last day is available [here](https://www.folkhalsomyndigheten.se/smittskydd-beredskap/utbrott/aktuella-utbrott/covid-19/statistik-och-analyser/bekraftade-fall-i-sverige/), I looked at the excel document.

**Comment by edomt** [comment]
Hi @hewwra 

As far I can see, the cumulative totals for cases and deaths both match the official totals, which indicates that there's no error in the overall counts:

- 83,958 in [our data explorer](https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&country=~SWE&casesMetric=true&interval=total&smoothing=0&pickerMetric=total_deaths&pickerSort=desc) == 83,958 on [the official page](https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa/page/page_0/)
- 5,821 in [our data explorer](https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&country=~SWE&deathsMetric=true&interval=total&smoothing=0&pickerMetric=total_deaths&pickerSort=desc) == 5,821 on [the official page](https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa/page/page_0/)

On the other hand, the daily numbers might look slightly different due to the issues discussed in #58, but there is unfortunately not much we can do to fix this. We source our data directly from the European Center for Disease Prevention and Control, and report it without making alterations to its original cases and death figures. You may try to get in touch with them if you believe that cases & deaths should be reported differently.

Edouard
