### ISSUE TITLE
Population data for Sweden is too low

### ISSUE THREAD

**Issue by DrChr** [owid/covid-19-data#139]
The population value for Sweden, assuming a reference date of 2020-07-01, should be: ```10 358 538``` [1].
However, the file ```scripts/input/un/population_2020.csv``` contains: ```Sweden,SWE,2020,10099270```
and that number is low by 2.5%.

If you don't trust the official swedish data [1], you can e.g. look at data from the UN Statistics Division [2] for 2017-2019 and extrapolate to 2020-07-01. Using the Octave/MATLAB code below, this gives a population size of 10 325 282.
```
ref_date = [2017 2018 2019];
population = [9995153 10120142 10230185];
pop_2020_07 = interp1(t, a, 20, 'spline', 'extrap')
```

My guess is that you've used data from the UN World Population Prospects (WPP) 2019, which unfortunately is a little off for Sweden and 2020. (Actually, the WPP value is off by 0.3% or so for 2015, and then it increases to about 2.5% for 2020.).

[1] Official swedish population statistics: https://www.scb.se/en/finding-statistics/statistics-by-subject-area/population/population-composition/population-statistics/

[2] UN Statistics Division, link to Swedish population data for 2019: http://data.un.org/Data.aspx?d=POP&f=tableCode%3a22%3bcountryCode%3a752%3brefYear%3a2017%3bsexCode%3a0&c=2,3,4,10,16&s=_countryEnglishNameOrderBy:asc,refYear:desc,areaCode:asc&v=1

**Comment by edomt** [comment]
Hi @DrChr — the data we're using for 2020 is indeed from the latest UNWPP dataset, including our estimate for Sweden's population (see below). As these are estimates, it's of course entirely likely that some national figures may differ (especially if a country has conducted a new census very recently) but for consistency we go with the latest UN population release for all countries, rather than going to each national source individually.

![image](https://user-images.githubusercontent.com/7103774/93059616-4524d300-f671-11ea-9d97-1aa69b1c3f80.png)
