### ISSUE TITLE
Smoothing does not account for delay in filter

### ISSUE THREAD

**Issue by esillekens** [owid/covid-19-data#142]
The smoothed data should be delayed by 3 days as the moving average filter has an (N-1)/2 samples group delay. So a 7 day moving average will introduce 3 days of delay into the data.

The data shown on 17-09-2020 should be at 14-09-2020 and the 15, 16 and 17 September data should probably not exist. 

This fix should help line up the smoothed data with the actual data.

https://wirelesspi.com/moving-average-filter/

**Comment by edomt** [comment]
Hi @esillekens 
I'm not sure I understand the rationale behind this. Could you share references to articles or sources that explain the issue better? Are you talking about a particular country?

**Comment by esillekens** [comment]
Hi, 

This is a general observation and a result of the maths used. As my background is more in digital signal processing than data science, I look at the moving average filter as finite impulse response filter where all filter coefficients are 1/N. If we look [1, Sec. 5.10.3] it uses the N-tap moving average filter as the example on how to calculate group delay. The moving average filter luckily has a constant group delay of (N-1)/2 samples.

This means that the data out of the filter has both the fluctuations removed (7 tap filter is especially good at removing fluctuations with a 1 week period) and is delayed by (N-1)/2 samples (this is only a whole number of samples for odd-length filters).

As an example, I have taken the Italy data and added the smoothed entries as a line, I have also added the delayed line what should be more correct.
![italy](https://user-images.githubusercontent.com/38911408/93592665-7a4f5f00-f9aa-11ea-9b8b-059a65d78138.png)

In scripts/scripts/shared.py I found the setting used for the rolling average and I would advise against having data in the last 3 days as this is effectively extrapolating, we simply do not know yet where the moving average is going. This is not unique, if you look at the UK dashboard, [UK cases](https://coronavirus.data.gov.uk/cases) you can see that the moving average stops 3 days before the last data point. 

[1] Richard G. Lyons, “Understanding Digital Signal Processing, 3rd edition”

**Comment by edomt** [comment]
As I understand it, what you're suggesting (in more "data sciency" terms) is to align our 7-day averages to the center of each 7-day period rather than to the right, which would indeed mean that the last 3 days of data would not show averages (since all/part of the 3 days "on their right" would be missing).

I agree that this would create a slightly more truthful representation of the trends (as your example shows). However, on our side we need to balance this need for perfect representation with:
- The need to provide the public with a smoothed metric that is "fresh". My fear is that center-aligning our averages and thus delaying them by 3 days would lead viewers of our graphs to refer to raw daily values more often, so they can show up-to-date data. We're actively trying to promote the use of smoothed metrics rather than raw, daily values, and this would probably go against this goal.
- The need to "keep things simple": our COVID-19 data explorer also shows a weekly metric (e.g. cases confirmed in the last week), which is effectively the right-aligned 7-day average multiplied by 7. If we move to daily averages that are center-aligned instead of right-aligned, those two metrics wouldn't have such a simple relationship anymore and would become harder to explain to the public.

We'll keep this in mind for the future, but for now I think that those needs outweigh the benefits of center-aligning to create a slightly more precise representation of the data.
