### ISSUE TITLE
Climate related variables?

### ISSUE THREAD

**Issue by drdee** [owid/covid-19-data#149]
Would it be possible to add climate related variables such as average daily temperature and average daily humidity?

**Comment by nikitaagarwala16** [comment]
Yes, I totally agree with you. Such information can be very useful to study the effect of climatic conditions on the spread of Covid-19. Maybe we find some pattern which can help people prepare for winters in the northern hemisphere.

**Comment by edomt** [comment]
Thanks for the suggestion. I'll leave it open but our team's resources are limited at the moment, and we're focusing on other areas of the COVID-19 data, so I'm afraid that won't happen for a while. It's also a non-trivial thing to add: weather APIs are either limited in use or not free, and weather information wouldn't necessarily be very relevant since our current dataset is only at the country level.

**Comment by J-Dunn** [comment]
Firstly, this is not "climate" data, it is weather data.  As edomt points out anything more detailed than monthly averages are costly and often not even available to the public. European countries do not have the same open access ethic to govt funded data as the USA does. 

This would be useful but I doubt it would be possible to meaningfully tie the two together.  Infection is an individual event and we do not have individual temp and rel. humidity data.  Influenza is known to strongly depend on temp and R.H. but this means inside the home/office environment more than outside weather. 

The big issue is cold air has low specific humidity ( actual water molecules ) though RH can be near 100%.  The problem is domestic heating raises air temp drastically, causing RH to plummet to very unhealthy "dry" conditions. 

There is some published research showing the SARS-COV2 does not have the same dependency to temp and RH as influenza strains, so naive expectation of similar seasonality is not well founded. 

This needs to be determined by lab work not global statistics since we don't have anything logging the pertinent quantities at an individual level. 

I only heat my living space to 12-14C in winter and I don't get colds or flu, ever. YMMV. Maybe you'd prefer to get the flu !
