### ISSUE TITLE
Dates are missing in Government Response data (bsg)

### ISSUE THREAD

**Issue by jazzypan** [owid/covid-19-data#151]
Dates are missing in Government Response data (bsg)

**Comment by edomt** [comment]
Hi @jazzypan 
Which file are you referring to?

**Comment by jazzypan** [comment]
This one 
https://github.com/owid/covid-19-data/tree/master/public/data/bsg

I guess it start from Feb. 1 for each country, but I need to make sure about that

**Comment by edomt** [comment]
This is an internal file for OWID's database, so for various technical reasons the date is named "Year" in the header, and the values are integers counting the number of days since January 1, 2020.

You can also use the original file from the OxCGRT repo: https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv
