### ISSUE TITLE
Japan 9/21-9/22 and 10/1-10/2

### ISSUE THREAD

**Issue by kaufkauf** [owid/covid-19-data#153]
Hello,

I am using your data for weekly COVID reporting to determine global office re-opening criteria.  For Japan, in both two day periods of 9/21-9/22 and 10/1-10/2, both periods appear to report 0 new cases on the first day, and a combined total of both day's new cases on the second day.  10/2 is the most concerning, as it shows 1,205 new cases, which is the first one-day total above 1,000 that we've seen in Japan the last 30 days.  However, other sources report ~650 on 10/1 and ~550 on 10/2.

Are these two examples typos, or is there something about the reporting schedule that is not daily or reports certain periods in arrears?  Any background you can provide would be helpful.

Thank you!

**Comment by edomt** [comment]
Hi @kaufkauf,

This is due to the way the European CDC (our source for cases & deaths data) collects the data: sometimes, when publishing their daily update (usually around 10am London time), some countries haven't yet reported their numbers for the day. When this happens, the ECDC will set those values to 0 for the day, and the next day will include the equivalent of two full days of cases and deaths.

For this reason (and many others) we generally advise against using daily reported values, but instead to look at the 7-day rolling average, which will smooth out those daily variations.

Edouard
