### ISSUE TITLE
Continent and countries badly set

### ISSUE THREAD

**Issue by metal3d** [owid/covid-19-data#1544]
Thanks for the data !

In "location", you also set `['European Union', 'Europe', 'North America', 'South America','Oceania','Asia', 'Africa', 'World', 'International']` - so we need to remove this from the dataset before to work...

**Comment by edomt** [comment]
Hi @metal3d 

This is done on purpose. The complete CSV dataset feeds our [data explorer](https://ourworldindata.org/coronavirus-data-explorer), so we need those aggregate locations to be pre-calculated in it. Also, many users like to have them for their own analysis, as it saves a lot of time instead of having to create continent lists and do it themselves.

If you need to get rid of them, the easiest way is to remove rows where `iso_code` contains `OWID_`

**Comment by metal3d** [comment]
`OWID_` removal made the job :) thanks a lot
