### ISSUE TITLE
possible errors in covid and all-cause mortality death counts

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#1550]
In [my script](https://github.com/czka/covid_toll_tool/blob/main/covid_toll_tool.py) I aggregate daily covid death counts (column `new_deaths` in [owid-covid-data.csv](https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv)) into weekly or monthly, and substract the aggregated value from the (weekly or monthly, depending on a country) all-cause mortality (`deaths_2020_all_ages` in [excess_mortality.csv](https://github.com/owid/covid-19-data/blob/master/public/data/excess_mortality/excess_mortality.csv)).

I'm getting strange/impossible results for few countries at certain dates:
- The difference exceeds the all-cause mortality:
  - [Spain](https://github.com/czka/covid_toll_tool/blob/main/covid_toll_ALL/Spain_2020.png) on 31.05.2020
  - [Estonia](https://github.com/czka/covid_toll_tool/blob/main/covid_toll_ALL/Estonia_2020.png) on 02.08.2020
  - [Switzerland](https://github.com/czka/covid_toll_tool/blob/main/covid_toll_ALL/Switzerland_2020.png) on 25.10.2020
  - [Monaco](https://github.com/czka/covid_toll_tool/blob/main/covid_toll_ALL/Monaco_2020.png) on 30.09.2020
  - [Kyrgyzstan](https://github.com/czka/covid_toll_tool/blob/main/covid_toll_ALL/Kyrgyzstan_2020.png) on 31.08.2020
- Negative difference for [Ecuador](https://github.com/czka/covid_toll_tool/blob/main/covid_toll_ALL/Ecuador_2020.png) on 13.09.2020.
- Strangely huge difference for [Chile](https://github.com/czka/covid_toll_tool/blob/main/covid_toll_ALL/Chile_2020.png) on 19.07.2020.

I did my best to rule out any errors in my script (it's quite simple if you want to take a look). Could you help me find out whether the culprit for these singular artifacts on these 7 charts might be due to some errors in OWID's data, or the sources you rely on? [Remaining 84 charts for 2020 and all 91 charts for 2021](https://github.com/czka/covid_toll_tool/tree/main/covid_toll_ALL) don't have any such obvious quirks, so I'm guessing these could be errors in the data indeed.

**Comment by edomt** [comment]
Hi @czka 

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues

That being said, there are two main caveats to the comparisons you're making here:

- Deaths are collected by JHU by date of report. This means that when there are data corrections, they are often added on a single day. For example, you can see [here](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&pickerSort=asc&pickerMetric=location&Metric=Confirmed+deaths&Interval=New+per+day&Relative+to+Population=false&Align+outbreaks=false&country=~CHL) that for Chile in July 2020, a big data correction was made. That's probably the cause of the discrepancy you're seeing.

- Excess mortality isn't a perfect measure by itself. It can be hard to measure in some countries. Also, all the excess deaths counted during a period don't have to be COVID deaths—they could also be due to other reasons. Inversely, the excess mortality can sometimes be lower than the official number of COVID deaths, if for example the lockdown or restrictions led to fewer deaths than usual among young people.

**Comment by czka** [comment]
@edomt Yes, I know were OWID are taking their data from. I was hoping OWID would forward my report as needed. Thanks for your interest though.

> all the excess deaths counted during a period don't have to be COVID deaths

Are you telling me this because you are under impression my charts claim otherwise? This wasn't my intention.

> excess mortality can sometimes be lower than the official number of COVID deaths

I'm confused why you mention excess mortality again. I'm not showing excess mortality as such on my charts. I'm showing: all-cause mortality (solid black), all-cause mortality minus covid mortality (dashed black) and all-cause mortality in previous years as a background/reference for these.
