### ISSUE TITLE
Huge spike in people_vaccinated & people_fully_vaccinated in China (+ Asia/World) on 2021-06-10

### ISSUE THREAD

**Issue by Fabian42** [owid/covid-19-data#1551]
I got a bit surprised when my automatically filled sheet (which uses this source) claimed that about 3% of the entire world's population got their second vaccine dose on Thursday. If only that was true…
When I went to the website, I noticed that these doses are getting attributed to Asia, but to none of the Asian countries:
![image](https://user-images.githubusercontent.com/10481506/121932578-4fc9e100-cd45-11eb-81c3-68bec0394bfc.png)
I have not checked other data points, apart from secondary vaccinations in Germany and Austria, which look normal.

**Comment by Fabian42** [comment]
Actually, when I disable the lines for world and Asia, I can see that there is a single data point for China, which seems to be very close to that delta. Where did the rest of the data go? Or was there no data before, they now published a single number and that simply got added to the Asia-wide and worldwide data for that day? In that case, is there really no better way than to blindly assume that it was all on that day?

**Comment by edomt** [comment]
Hi @Fabian42 

Yes, this is indeed due to newly-published data by the Chinese government. Unfortunately, since this is the very first time that they publish information on 1st/2nd doses, we cannot assign to a date other than the date of the announcement. We'll be looking into ways to smooth the time series, but ideally we want to stick to official data rather than infer trends ourselves.

**Comment by lucasrodes** [comment]
Hi Fabian,
Thanks for your message.


This is due to the fact that China just released the first data on the number of people that got the first and second vaccinate dose. As a consequence, there is a spike in the data.




Hope this helps,
Kind regards,





—
Lucas Rodés-Guirao
Senior Data Analyst, Our World in Data
@lucasrodesg / lcsrg.me

--- original message ---
On June 14, 2021, 6:19 PM GMT+1 ***@***.*** wrote:



I got a bit surprised when my automatically filled sheet (which uses this source) claimed that about 3% of the entire world's population got their second vaccine dose on Thursday. If only that was true…

When I went to the website, I noticed that these doses are getting attributed to Asia, but to none of the Asian countries:


I have not checked other data points, apart from secondary vaccinations in Germany and Austria, which look normal.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by vyaduvanshi** [comment]
Just came across this myself.

![image](https://user-images.githubusercontent.com/37543003/123509182-9c8cb080-d691-11eb-89f7-a08c3f73dfe7.png)

But well, if it's the official data, then it should not be changed. We as users can handle it in our own ways but the source should indeed remain the same. Just like Turkey's old spike in `new_cases`.

There also seems to be a spike in `Australia` on date `24th May 2021`. @edomt Any idea why that is?

![image](https://user-images.githubusercontent.com/37543003/123509341-7ddae980-d692-11eb-930e-44f3707cefa8.png)

![image](https://user-images.githubusercontent.com/37543003/123509349-88957e80-d692-11eb-9f90-f8bbcced53ec.png)

**Comment by lucasrodes** [comment]
Hi @vyaduvanshi,
The spike in Australia is due to starting reporting second doses (and thus fully vaccinated and vaccinated with >= 1 dose)

**Comment by aywi** [comment]
@edomt @Fabian42 There is a serious misunderstanding for COVID-19 vaccination data on China:
You cannot simply use **[people_vaccinated = total_vaccinations - people_fully_vaccinated]** to obtain **people_vaccinated**, because there are 1-dose (CanSino), 2-dose (Sinopharm/Beijing, Sinopharm/Wuhan, Sinovac, [Shenzhen Kangtai](https://en.wikipedia.org/wiki/Minhai_COVID-19_vaccine), [IMBCAMS](https://en.wikipedia.org/wiki/Chinese_Academy_of_Medical_Sciences_COVID-19_vaccine)), and 3-dose ([Anhui Zhifei Longcom](https://en.wikipedia.org/wiki/ZF2001)) COVID-19 vaccines currently in use in China, and their detailed proportions are unknown. (From my personal observation, the 3-dose one is much more common than the 1-dose.)

For data on 2021-06-10:
**people_fully_vaccinated** was not mentioned on the [source_url](http://www.nhc.gov.cn/xcs/fkdt/202106/e28487f08ad745c5952356e448a87f13.shtml), so the line for 2021-06-10 should be
| total_vaccinations | people_vaccinated | people_fully_vaccinated |
| -----------------: | ----------------: | ----------------------: |
|          845299000 |         622000000 |                         |

For data on 2021-08-12:
**people_vaccinated** was not mentioned on the [source_url](http://www.nhc.gov.cn/xcs/s3574/202108/6c77e46253b84b1f9cca2d5aa4a0f76b.shtml), so the line for 2021-08-12 should be
| total_vaccinations | people_vaccinated | people_fully_vaccinated |
| -----------------: | ----------------: | ----------------------: |
|         1832450000 |                   |               777046000 |

For data on 2021-08-26:
**people_vaccinated** should be 1,072.5 million, from the sentence on the [source_url](http://www.nhc.gov.cn/xcs/s3574/202108/f211dd79672642b7908ffb7575d020a1.shtml) `疫苗接种的总人数达到了10亿7250万人，覆盖全国人口的76%。`, translated as `The total number of people vaccinated reached 1,072.5 million, covering 76% of the country’s population.`, so the line for 2021-08-26 should be
| total_vaccinations | people_vaccinated | people_fully_vaccinated |
| -----------------: | ----------------: | ----------------------: |
|         2003914000 |        1072500000 |               889439000 |

Summary:
| location |    date    | total_vaccinations | people_vaccinated | people_fully_vaccinated |
| :------: | :--------: | -----------------: | ----------------: | ----------------------: |
|  China   | 2021-06-10 |          845299000 |         622000000 |                         |
|  China   | 2021-08-12 |         1832450000 |                   |               777046000 |
|  China   | 2021-08-26 |         2003914000 |        1072500000 |               889439000 |

I can submit a pull request if needed.

**Comment by edomt** [comment]
Thank you @aywi. Indeed we know that the assumption of `people_vaccinated = total_vaccinations - people_fully_vaccinated` is not valid for China, but we had decided to use that as the lack of reporting made the situation difficult — because we didn't have any figure for `people_vaccinated` for China since June, and China represents such a huge part of global vaccinations that it made even our global figures too low.

But that's only because we had missed the second quote referring to those 1.0275 people vaccinated! Thanks very much for letting us know, we'll fix the data now.
