### ISSUE TITLE
Argentina and Thailand Data Revisions

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#159]
Hello, thanks for constantly provide good quality of data. In the latest release, Argentina and Thailand testing data have large revisions from very beginning of pandemic. Other counties also revised a little, like Bulgium, New Zealand, Mexico and Slocakla. I would like to ask if these revisions are corect?

**Comment by edomt** [comment]
Hi @RuijingZ 

Thank you very much for notifying us.

The large change for Argentina was due to a technical error; which we've now fixed.

For Thailand we revised the time series based on a more complete source, see here: https://ourworldindata.org/coronavirus-testing#thailand

The data for those other countries, on the other hand, should be fine—unless you're seeing something that specifically looks abnormal?

**Comment by RuijingZ** [comment]
> Hi @RuijingZ
> 
> Thank you very much for notifying us.
> 
> The large change for Argentina was due to a technical error; which we've now fixed.
> 
> For Thailand we revised the time series based on a more complete source, see here: https://ourworldindata.org/coronavirus-testing#thailand
> 
> The data for those other countries, on the other hand, should be fine—unless you're seeing something that specifically looks abnormal?

Thank you very much for fixing it! Other countries revisions seem normal for me too, but just wanted to confirm those revision in case they have any problem.
