### ISSUE TITLE
 ICU & Hospital admissions: Vietnam

### ISSUE THREAD

**Issue by Ltn123456** [owid/covid-19-data#1592]
As I said in #1589, every week, WHO publishes Viet Nam Situation Report, starting from 19 July 2020. (https://www.who.int/vietnam/internal-publications-detail/covid-19-in-viet-nam-situation-report-01).
![screenshot2](https://user-images.githubusercontent.com/80508367/123028302-6c32e100-d409-11eb-80da-13b2607c3384.PNG)
I think we can use ICU Admissions or hospital admissions data from WHO. Here is a screenshot from COVID-19 in Viet Nam Situation Report 47 (https://www.who.int/vietnam/internal-publications-detail/covid-19-in-viet-nam-situation-report-47)
![screenshot](https://user-images.githubusercontent.com/80508367/123027683-77394180-d408-11eb-9697-15dc10253856.PNG)

**Comment by Ltn123456** [comment]
And is it possible to sum up the 11 Southeast Asia countries data to create a Southeast Asia data. The region has a population of more than 600 million, nearly 700mil, higher than European Union, North America and South America

**Comment by lucasrodes** [comment]
Hi @Ltn123456,
Currently, we are unable to incorporate new countries into the hospitalization dataset unless their report does include the whole time series data and comes in a machine-friendly format such as CSV or JSON. This is basically due to our limited resources.

We will let you know if this changes, as we would really like to add new countries to this dataset.

**Comment by lucasrodes** [comment]
> And is it possible to sum up the 11 Southeast Asia countries data to create a Southeast Asia data? The region has a population of more than 600 million, nearly 700mil, higher than European Union, North America and South America

Please open a separate issue
