### ISSUE TITLE
Missing Data for Denmark

### ISSUE THREAD

**Issue by hpgjg** [owid/covid-19-data#1593]
Data for Denmark in 'Daily COVID-19 vaccine doses administered per 100 people' from May 27 forward has gone missing.

Data in 'COVID-19 vaccine doses administered per 100 people' and others have also been lost and is not being updated.

**Comment by lucasrodes** [comment]
Hi @hpgjg,
Thanks for your message.

To the best of our knowledge, Denmark does report figures on the total number of doses administered in its time-series archives (found [here).](https://covid19.ssi.dk/overvagningsdata/download-fil-med-vaccinationsdata) Also not in their [dashboard](https://experience.arcgis.com/experience/1c7ff08f6cef4e2784df7532d16312f1).

Prior to the 27th of May, we could estimate this metric by adding the number of first doses and second doses, as only two-dose vaccination schemes were being used. However, since Johnson & Johnson vaccine was introduced, this estimation was no longer valid and hence stopped reporting the number of doses.

Hope this helps!

**Comment by hpgjg** [comment]
Hi @lucasrodes

Thanks for your quick response.

No need to estimate. ;-) 

All data needed is included in the files.

First of all, on ssi.dk it’s described how the Janssen vaccines are included and used. It is in Danish, but it describes that the Janssen-doses (J&J) are included in both ‘have started vaccination’ (påbegyndt vaccination/første vacc.) and in fully vaccinated (færdigvaccineret).

In file ‘Vaccinationstyper_regioner.csv’ (updated daily) you can see how many have received shots from which company/type.

From this it’s fairly easy to calculate a daily total and a delta from day to day.

Basically ‘have started (including 1x total J&J)’ + (plus) ’fully vacc.(including 1x total J&J)’ - (minus) ‘1x total J&J-shots’ = total number of shots given.

That will give us a total number of doses given from December until today.
    
Eg. the grand total with the latest data published would be 3,114,453+1,703,645-41,855=4,776,243

Calculating a daily rate or total can be done by looking at the delta between days and using national population numbers.

Currently that would be a total of about 83 doses per 100 pop. depending on which population data you use.

Doses administered in the lastest 24 hours per 100 people in Denmark would be ‘latest 24h have started (including 1x total J&J)’ + (plus) ’latest 24h fully vacc.(including 1x total J&J)’ - (minus) ‘1x total J&J-shots’ = total number of shots given in the latest 24h of data.

In today's published data that would come to 46,269+27,024-616=72,677 doses given in the latest 24 hours of data. That would equal a rate of approximately 1.26 doses per 100 pop in the latest 24 hours (daily) depending on which population data you use.


About the data: 
I have used SSI.dk datasets published on 20210622 and 20210623. They are usually generated at around 04.00 CET and published at 14.00 CET.

Danish vaccination data is based on data from DDV (Det Danske Vaccinationsregister). A national Danish register of all vaccines given to the Danish population. All health professionals are by law required to register all vaccinations in this register. On a personal note - I have never been given a vaccine (flu, covid or other) that has not been instantaneously visible when I login to the national health site which gets its data from DDV.

**Comment by lucasrodes** [comment]
Thanks for your reply, @hpgjg. And for the carefully detailed info.

> First of all, on ssi.dk it’s described how the Janssen vaccines are included and used. It is in Danish, but it describes that the Janssen-doses (J&J) are included in both ‘have started vaccination’ (påbegyndt vaccination/første vacc.) and in fully vaccinated (færdigvaccineret).

We are aware of this, and this matches our metrics `people_vaccinated` and `people_fully_vaccinated` definitions.

> Basically ‘have started (including 1x total J&J)’ + (plus) ’fully vacc.(including 1x total J&J)’ - (minus) ‘1x total J&J-shots’ = total number of shots given.

You are totally right with this. We actually thought of this, but we were expecting authorities to start providing the clean number directly. So we decided not to start development on our side and wait for them to release this data.

If it is possible for you, we encourage you to edit the [automation script](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/src/vax/batch/denmark.py) and create PR for Denmark's process. You can check the [Contribution guideline](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/CONTRIBUTE.md).

Otherwise, we will likely address it later, but hopefully soon enough.

---

The rest of the metrics that you cite (per capita, daily, etc.) are calculated in the following processes so no need to estimate them here.

---

Thanks once again for your interest and help, it is very much appreciated!

**Comment by lucasrodes** [comment]
Continuing discussion in #1617. Apparently 

Hi Lucas, I’m sorry to contradict you but the Johnson and Johnson vaccine is not used in Denmark, https://www.sst.dk/en/English/news/2021/The-Danish-COVID-19-vaccine-rollout-continues-without-the-COVID-19-vaccine-from-Johnson-Johnson Sundhedstyrelsen - the Health Authority – confirmed on 25 June https://www.sst.dk/da/corona/COVID-19-vacciner-i-Danmark/Johnson-Johnson that the J+J vaccine would continue not to be used. The two vaccines used in Denmark are Moderna and Pfizer so the official data sources I provided remain relevant to vaccine data. Kind regards Karen 

_Originally posted by @KarenB-N in https://github.com/owid/covid-19-data/issues/1617#issuecomment-869390157_
