### ISSUE TITLE
Data on chart not showing properly for single dates data like Singapore

### ISSUE THREAD

**Issue by oliverlim71** [owid/covid-19-data#16]
Hi,

I noticed that for testing reports, For countries where you only have certain dates like Singapore 7 April 2020. When you add the country in this case Singapore, it will only be shown on the chart if you adjust the end date to on or before 7 April.  If it is left at the current like 14 April as of today, Singapore will not appear on the chart. I also noticed the same for a few other countries but do you recall which ones now.

**Comment by edomt** [comment]
Hi @oliverlim71,

This is due to Singapore having only reported 1 data point for tests (on 7 April 2020), which makes it impossible to draw a line on the chart. As soon as they report a second data point, the time series will appear.
In the meantime, if you want to compare Singapore to other countries, you can use the slider to select only 1 day (7 April), and the lines will be replaced by a bar chart—this one will include Singapore.

Edouard
