### ISSUE TITLE
US State Vaccination Outliers

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#1652]
Daily COVID-19 Vaccinations administered on Jul 01 in us_state_vaccinations.csv for some states are weird, like Arizona and Puerto Rico, and North Carolina, which also cause 7-day smoothed has a large jump. 
Could you check the validity of these data?

**Comment by lucasrodes** [comment]
Hi @RuijingZ,
This is likely a correction from the source. 

We source the data from US CDC, (see here https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data).

We import that data with little to no processing (see our [script](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/us_vaccinations.py)), hence we assume that these spikes are due to data corrections.

**Comment by RuijingZ** [comment]
> Hi @RuijingZ,
> This is likely a correction from the source.
> 
> We source the data from US CDC, (see here https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data).
> 
> We import that data with little to no processing (see our [script](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/us_vaccinations.py)), hence we assume that these spikes are due to data corrections in the source.

Yeah, it matches with cdc data. Thanks for the link.
