### ISSUE TITLE
Fully vaccinated people in Ireland

### ISSUE THREAD

**Issue by blasf1** [owid/covid-19-data#1752]
Hi!
Ireland's covid datahub is not counting Janssen in the dose_2 column (if my maths are right). However, I think for people_fully_vaccinated the code is taking dose_2 as it is, i.e., it is not including J&J. J&J is added to people_vaccinated instead (which is dose_1, where J&J should already be included, I believe). Maybe I am missing something, but I wanted to let you know just in case :)

Link to the datahub: https://covid19ireland-geohive.hub.arcgis.com/pages/vaccinations

Thanks for the great work!

**Comment by edomt** [comment]
Hi @blasf1 

Indeed, based on the fact that on the dashboard `Total 1st Dose Vaccines Administered + Total 2nd Dose Vaccines Administered ==  Total Vaccines Administered`, I agree that J&J doses are only counted in one of these 2 numbers. However, our understanding so far has been that they're counted in the left-hand total (Total 1st Dose Vaccines Administered) and not in the right-hand one (Total 2nd Dose Vaccines Administered), rather than the opposite. 

So far this has seemed to work well with the official data announced by the government. For example, on [July 8](https://twitter.com/MichealMartinTD/status/1413038048749707270?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1413038048749707270%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.bbc.com%2Fnews%2Fworld-europe-57763694) it was announced that _"Two million people are now fully vaccinated"_ — this is also [what we get](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&pickerSort=asc&pickerMetric=location&Metric=People+fully+vaccinated&Interval=7-day+rolling+average&Relative+to+Population=false&Align+outbreaks=false&country=~IRL) with our current data processing.

**Comment by blasf1** [comment]
Hi! 

Thanks for your response! I found this PDF by the HSE that may help to clarify things :)

https://www.hse.ie/eng/services/news/newsfeatures/covid19-updates/vaccination-programme-dashboard-as-of-21-july-2021.pdf

Apparently, comparing with the dashboard, they are adding the Single Dose to Dose 1 (in the PDF) to get what in the dashboard they call Total 1st Dose Vaccines Administered. I hope it helps!

**Comment by edomt** [comment]
Thank you! This means your assumption was actually correct. I'll fix it now :)
