### ISSUE TITLE
France full vaccinations

### ISSUE THREAD

**Issue by blasf1** [owid/covid-19-data#1757]
Hi!

I found this [dataset](https://www.data.gouv.fr/fr/datasets/r/fa4ad329-14ec-4394-85a4-c5df33769dff) on the French government website that has a column for fully vaccinated people (n cum_complet) that shows a considerably bigger amount of fully vaccinated people than the one shown currently on your website. I can't find where the discrepancy is but it seems to fit much better the [PR released](https://solidarites-sante.gouv.fr/actualites/presse/communiques-de-presse/vaccination-contre-la-covid-en-france-au-21-juillet-2021-pres-de-67-200-000) by the French government.

As I said, I'm not sure where the discrepancy is, or if there is even one, I just wanted to point it out just in case :)

Thanks!

**Comment by edomt** [comment]
Hi @blasf1 

This is due to the different definition used by the French government: people with only 1 dose but who have previously had COVID-19 are considered fully vaccinated.

In our data, fully-vaccinated people are those who have received all doses prescribed by their vaccination regimen (e.g. 2 doses for Pfizer/BioNTech, Moderna, Oxford/AstraZeneca, etc. and 1 dose for Johnson & Johnson, CanSino, etc.).

Some countries, including France, also allow for alternative definitions, such as having been infected with SARS-CoV-2 in the past and having received 1 dose of a two-dose regimen. We currently ignore these alternative definitions to preserve the common definition of fully vaccinated, i.e. all doses required in the vaccine regimen. This allows for an optimal comparability between countries.

**Comment by GeoffreyOnRails** [comment]
Hi @edomt , 

Thanks a lot for the explanation. I think that this should at least be added to the README and probably to the owid explorer's definition as well, as this is extremely surprising for someone looking at those countries only, especially since it is displayed on Google's first page on some keywords.

The data definition might be something like : 
> Share of the total population that have received all doses prescribed by the original pharmaceutical firm's vaccination protocol. This data is only available for countries which report the breakdown of doses administered by first and second doses. Some countries have adopted a different vaccination protocol (e.g only one dose for those having been infected with SARS-CoV-2), the data doesn't adopt those local definitions to allow relevant cross-countries comparisons.

Thinking about it, it might also be useful to have another dataset with "people fully vaccinated based on local vaccination protocol", as it might be the data that most people are looking for, despite it doesn't allow cross-country comparaisons. 

Do you think I should open a dedicated issue for this?

**Comment by edomt** [comment]
Hi @GeoffreyOnRails 

Thank you for your feedback.

For now, we won't add a new variable to our dataset — our current resources don't allow us to extend our collection process to local definitions of full vaccinations.

We've added a footnote to our charts of fully vaccinated people to make this distinction clearer.
