### ISSUE TITLE
Are Northern Ireland Figures Correct?

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#1758]
Just a query. We get figures for 11 July and then the next ones are for 18 July which is OK but .....

They usually do 1st vac between 1000 and 2000 a single day but now they have done only 180 in 7 days is that correct?

The file I was looking at is 

https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Northern%20Ireland.csv

If correct then just close ticket, I will use the data as is.

**Comment by edomt** [comment]
Hi @zizwiz 

The issue comes from the source data itself, that includes a drop in the number of people vaccinated:

<img width="901" alt="Capture d’écran 2021-07-23 à 19 51 50" src="https://user-images.githubusercontent.com/7103774/126821912-58cab6fb-405d-46ec-87d3-b98d9723672c.png">

This is most likely a data correction on their end, but to keep the series logical and monotonically increasing, we therefore have to remove some rows.
