### ISSUE TITLE
Doses per day missing for Denmark

### ISSUE THREAD

**Issue by lucasvduin** [owid/covid-19-data#1759]
How come the number of vaccine doses per day is missing for Denmark since may 26th? The number of people vaccinated and fully vaccinated seems to be up-to-date.

**Comment by lucasrodes** [comment]
Hi @lucasvduin,
Thanks for your message.

We have fixed this in https://github.com/owid/covid-19-data/commit/499257ecc66215d33136cbbd20cccdca51510a4c. Note that we have had some difficulties in reporting complete data figures for Denmark due to the format of the official reports.

Now values for metric `total_vaccinations` are reported for dates after 27th of May.
