### ISSUE TITLE
Dates are not linked to the correct data 

### ISSUE THREAD

**Issue by Arsenic1** [owid/covid-19-data#176]
Hi All,

I was trying to analyze data and, looking at least in the Italian Data it seems that the Dates are not aligned with the correct data.
eg. Italy, 2020-11-08 contains New_Cases and New_Deaths corresponding to 9 of Nov, while New_Tests seems to be correct  for 8 of Nov.

Please may I ask you to check, these mismatches have huge impact on calculations and forecasts

**Comment by edomt** [comment]
Hi @Arsenic1 
This is due to the collection method used by the European CDC (our source for cases and deaths data): each morning they collect the latest cumulative total in every country. For some countries, especially in Europe, this is the number that was announced the preceding day in the afternoon/evening. This results indeed (for some countries) in a 1-day lag between official data and ECDC data.
This is one of the reasons why we advise that people use smoothed estimates instead (`new_cases_smoothed`, `new_deaths_smoothed`, `new_tests_smoothed`) to analyze trends.
Edouard

**Comment by Arsenic1** [comment]
Hi Mathieu,

Many thanks for your reply I ll rely on the smoothed data then :)

Many Thansùks
*Andrea Quattrocchi*

Tel. +39 06768689 | Cell. +39 3891522121
andrea.quattrocchi90@gmail.com <andrea.quattrocchi90@gmaail.com>



Il giorno mer 11 nov 2020 alle ore 11:22 Edouard Mathieu <
notifications@github.com> ha scritto:
