### ISSUE TITLE
Pakistan Partially Vaccinated Numbers not updated

### ISSUE THREAD

**Issue by mobeenhameed** [owid/covid-19-data#1767]

**Comment by mobeenhameed** [comment]
The data is available on the same source

**Comment by lucasrodes** [comment]
Hi @mobeenhameed,
Thanks for your message.

We are currently unable to report the number of people that received at least one dose due to the way Pakistan is reporting data on its website.

Besides the total number of administered doses, the metrics reported in our source (https://ncoc.gov.pk/covid-vaccination-en.php) are:

- **people partly vaccinated**: Number of people that have received the first dose of a 2-dose vaccine (e.g. Pfizer/BioNTech, Oxford/AstraZeneca, Moderna, etc.).
- **people fully vaccinated**: Number of people that have received all necessary doses depending on the vaccine (one dose for CanSino, two for others

On our website, we report the metric "people vaccinated", which is equivalent to "people with at least 1 dose", which counts the number of people that have received at least one dose (first dose of a 2-dose vaccine or the only dose of a 1-dose vaccine).

Due to the use of a 1-dose vaccine (CanSino) by Pakistan, we cannot simply calculate "people with at least 1 dose" (i.e. people vaccinated) based on the available information, and we currently have to leave it blank until more precise data is reported.
