### ISSUE TITLE
South Africa seems to have odd result on 26/27 July 2021 

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#1777]
Looking at https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/South%20Africa.csv

On 26 July it seems that the data was sourced from a place that is totally different to the rest of the days making for some very strange stats for 26 and 27 July. Maybe remove 26July? 

Thanks for all the work you do.

**Comment by lucasrodes** [comment]
Hi @zizwiz,
Thanks for your message.


We sourced the data for 26th from the same platform (i.e. https://sacoronavirus.co.za). The only difference is that we used their static report instead of the dynamic one, as we couldn't retrieve the latter. While the data on the 26th is not complete (missing metrics `people_vaccinated` and `people_fully_vaccinated`), it still provides some valuable information, namely the number of vaccinations administered up to date.


Hope this helps.
