### ISSUE TITLE
Accuracy of GBR population is out or to be better determined. State the source in the dataset, for the UK's population figure?

### ISSUE THREAD

**Issue by philipswift** [owid/covid-19-data#1785]
Data released at /.../tree/master/public/data, states GBR population for 1st Aug 2021 as 67,886,004 when worldometers.info states it as live as 68,275,315.
The UK's Government website for statistics is the ONS. The ONS has figures for estimated populations however, these are up until mid 2020 so their API is seemingly, not useful. There maybe a difference in defintion of <Great Britain> at the ONS and that of <GBR> in OWID/JHU. This element is key to accurate reporting of <people_fully_vaccinated>. An example is the UK's BBC (British Broadcasting Corporation) has reported "nearly 90% of the adult population - and more than 37 million - over 70% of adults - have had both doses".  Source: [https://www.bbc.co.uk/news/health-55274833](https://www.bbc.co.uk/news/health-55274833)

Obviously no one is responsible for the media and how they report figures however, the clearer the origin/source is, the better the analysis/interpretation can be. Stating the origin/source is useful as it helps in assessements.
The UK's ONS states the predicted population for 2022 is 67,844,183. Source: [https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/articles/overviewoftheukpopulation/january2021](The UK's population has grown year-on-year since 1982)

We are only still in 2021 and the OWID Covid data states the UK population as more than 67,844,183, at 67,886,004.

End user perception could be that 70% of 67,886,004 has had both doses, which is 47,506,202.8 when the OWID Covid data is reporting <people_fully_vaccinated>=38,126,702. This is a difference of some 9.3 million. I fully understand this may be outside any stated scope however, I didd think it worth mentioning.
PCS 1st Aug 2021 at 17:20 BST/12:20 EDT

**Comment by edomt** [comment]
Hi @philipswift 

There are two different issues here:

### The population denominator that we use for the UK

The population estimates we use come from the United Nations World Population Prospects. We use this data for its reliability, its consistent methods, and because it makes our work much easier. The exact values can be viewed [here](https://github.com/owid/covid-19-data/blob/master/scripts/input/un/population_2020.csv).

The United Nations estimates may not always reflect the latest censuses or national figures—but there are [several reasons](https://ourworldindata.org/covid-vaccinations#frequently-asked-questions) why we use this data over country-by-country national population estimates.

It is written in many places in this repo that we use the UN figures for population denominators (including our [main REAMDE](https://github.com/owid/covid-19-data/tree/master/public/data), [vaccination README](https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations), and [codebook](https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-codebook.csv)).

Also note that Worldometer's "live" counters are entirely illustrative, and not based on any scientific data.

### Confusion over % of adults vs % of population vaccinated

The other issue you describe in your last paragraph is unrelated. The BBC figures you mentioned, just like the official UK dashboard, report the % of the _adult_ population that's vaccinated (or fully vaccinated), while our data shows the % of the _total_ population. The difference of 9.3 million in your calculation is simply due to this different denominator.

**Comment by philipswift** [comment]
Hi edomt

Thank you for the clarification and sources.
