### ISSUE TITLE
France: different count for vaccination 

### ISSUE THREAD

**Issue by B0pol** [owid/covid-19-data#1791]
The count for both 1st doses and fully vaccinated people is different between OWID and health autority data.

On 2021-07-29

- [OWID data](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/output/France.csv): 41673008 1st doses, 31841857 people fully vaccinated
- [Santé Public France data](https://www.data.gouv.fr/fr/datasets/r/fa4ad329-14ec-4394-85a4-c5df33769dff), from [data.gouv.fr](https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1/): 41692674 1st doses, 34808758 people fully vactinated

Can you explain/fix?

**Comment by edomt** [comment]
Dear @B0pol 

In our data, fully-vaccinated people are those who have received all doses prescribed by their vaccination regimen (e.g. 2 doses for Pfizer/BioNTech, Moderna, Oxford/AstraZeneca, etc. and 1 dose for Johnson & Johnson, CanSino, etc.).

Some countries also allow for alternative definitions, such as having been infected with SARS-CoV-2 in the past and having received 1 dose of a two-dose regimen. We currently ignore these alternative definitions to preserve the common definition of fully vaccinated, i.e. all doses required in the vaccine regimen. This allows for an optimal comparability between countries.

**Comment by tristanguigue** [comment]
@edomt thanks for the explanation, I completely understand the need for simplicity however I would argue this does not necessarily allows for an optimal comparison between countries since those second doses will never be able to be administered given the local regulations. In particular, it will never be possible for a country such as France to have the fully vaccinated ratio equates the primary vaccination ratio which will be a problem as we approach the final stages of the vaccination in some countries. This might induce wrong conclusions to be drawn from this data, for example interpreting this as persons that refuse to get their second dose.

A possible solution could be that if and only if the fully vaccinated data is indeed publicly available from an official source then use it (such as is the case here).

**Comment by edomt** [comment]
@tristanguigue That's a very interesting point, thank you for the feedback.

My personal hunch is that these alternative definitions might soon become obsolete. They were initially introduced in a context where there was a lock of vaccine doses, but I wouldn't be surprised if some of those governments announced in a little while that everyone is required to get the prescribed two doses, due to the waning effects of the immunity created by the disease.

In any case and as always, we'll revisit this decision in the future and if the circumstances have changed, and we think it's best to use the national definitions of a full vaccination, we'll be happy to do so.

**Comment by pconort** [comment]
@edomt The issue is that many news and information providers are using OWID data as point of truth to explain vaccination coverage to lay persons and news outlets. This in turn participate to misinformation about national vaccination coverage, especially in countries like France where media is highlighting the anti-vax phenomenon. Should we risk misinformation on personal hunch or on national definitions of full vaccination made by experts in the field?

**Comment by edomt** [comment]
@pconort Thank you for pointing out our lack of expertise.

However, I don't agree that our common definition "participates to misinformation" in any way. As a platform that provides comparative data for hundreds of countries, defining a common basis is extremely important, and our methodology is clearly explained in our chart footnotes (see [here](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=People+fully+vaccinated&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=USA~GBR~CAN~DEU~ITA~IND~FRA)).

On top of the reasons above, another reason to keep a common definition is that country-specific definitions tend to change regularly and be badly documented. Keeping track of definitions for the 214 territories we monitor would require a lot of time and effort from our team, replacing other useful work.

**Comment by tristanguigue** [comment]
@edomt thanks for your answer.

> On top of the reasons above, another reason to keep a common definition is that country-specific definitions tend to change regularly and be badly documented. Keeping track of definitions for the 214 territories we monitor would require a lot of time and effort from our team, replacing other useful work.

I'm not sure I fully understand the argument here. In the end you do depend on the willingness of each national authority to provide you with the data which is the case here with `data.gouv.fr`. So this is purposely replacing the official source for "fully vaccinated persons" by a custom-made OWID definition. There wouldn't be really much additional effort to plug in the proper dataset (https://www.data.gouv.fr/fr/datasets/r/fa4ad329-14ec-4394-85a4-c5df33769dff). If other national authorities have a different definition, it's up to them to provide the proper data (which is the case regardless of the definition adopted).

> I wouldn't be surprised if some of those governments announced in a little while that everyone is required to get the prescribed two doses

There isn't really any evidence this will every occur however, it seems dubious to rely on national authorities to change their covid vaccination regulations, rather than make sure OWID use the official numbers.

The difference has become quite huge this last weeks (4 million now) so this is a fairly important issue given the media attention on comparing vaccination rates across countries. Thanks again for the great work.

**Comment by tristanguigue** [comment]
A recent example of press coverage that highlights the issue: https://www.latribune.fr/economie/international/au-royaume-uni-l-economie-accelere-tandis-qu-en-france-elle-remonte-doucement-890501.html

> Depuis, la France - comme les autres pays de l'UE - a resserré l'écart, mais reste tout de même en retard sur son voisin. Désormais, 58,46% des Britanniques sont complètement vaccinés contre 50,54% des Français, selon les données d'Our World in Data au 9 août.

The actual percentage of fully vaccinated persons in France is 56.99% as of 11st of August (from https://covidtracker.fr/vaccintracker/) against 58.94% for the UK which make the whole comparison and conclusions drawn here based on OWID invalid or exaggerated at best. Those 4 million individuals not counted in OWID data have no possibility or need of getting a second dose following the official regulations based on the scientific advice that immunity from the disease provides.

**Comment by edomt** [comment]
> There isn't really any additional work needed though, if there is any change in regulation it will be in any case reflected in the fully vaccinated numbers which are provided to you.

This is because you are focusing on the sole case of France, which is precalculating "people fully vaccinated" in a dedicated column. This isn't how data is released for many other countries in the world, where vaccinations are reported by dose number (and sometimes manufacturer), and we have to calculate things ourselves.

**Just to reiterate, because this is important: we'll revisit this decision in the future and if the circumstances have changed, and we think it's best to use the national definitions of a full vaccination, we'll be happy to do so.**

**Comment by danbeck** [comment]
> Some countries also allow for alternative definitions, such as having been infected with SARS-CoV-2 in the past and having received 1 dose of a two-dose regimen. 

Here is the definition of data.gov.fr of a fully vaccinate person:
- a person vaccinated once with monderna or pfizer counts as having gotten one dose of the vaccin
- a person vaccinated twice with moderna, pfizer or astrazeneca or once with jansen counts as beeing fully vaccinated.

Having been infected by SARS-CoV-2 is not taken into consideration.  The definition of data.gov.fr seems quite similar to the definition of OurWorldInData. Where is the difference?

Link: https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1/

**Comment by edomt** [comment]
Hi @danbeck 

I don't see any mention of these two points on the page you linked to. 

People with a previous infection and one dose of vaccine are indeed counted as "fully vaccinated" by the French government in their official statistics:
- https://www.ameli.fr/paris/medecin/actualites/covid-19-qui-est-concerne-par-le-schema-vaccinal-une-seule-dose
- https://www.has-sante.fr/jcms/p_3237456/en/une-seule-dose-de-vaccin-pour-les-personnes-ayant-deja-ete-infectees-par-le-sars-cov-2

**Comment by danbeck** [comment]
Hi @edomt 

data.gov.fr provides both information (Source: https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1/):

- the amount of persons who are fully vaccinated according to the french definition is contained in the following files:
``` 
vacsi-tot-fra-YYYY-MM-DD-HHhmm.csv (échelle nationale)
vacsi-tot-reg-YYYY-MM-DD-HHhmm.csv (échelle régionale)
vacsi-tot-dep-YYYY-MM-DD-HHhmm.csv (échelle départementale)
```
- the amount of persons who got vaccinated once, twice or three times is contained in the following files. The data is grouped by the vaccin (JJ, Astra, Pfizer, Moderna):
```
vacsi-tot-v-fra-YYYY-MM-DD-HHhmm.csv (échelle nationale)
vacsi-tot-v-reg-YYYY-MM-DD-HHhmm.csv (échelle régionale)
vacsi-tot-v-dep-YYYY-MM-DD-HHhmm.csv (échelle départementale)
```

**Comment by edomt** [comment]
Yes - and we use the second one. See https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/batch/france.py
