### ISSUE TITLE
Summing up vaccination by age for any specific country/day mismatches people_vaccinated/fully_vaccinated for the same country/day   

### ISSUE THREAD

**Issue by sunset001** [owid/covid-19-data#1792]
In this file (https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations-by-age-group.csv) vaccinated number for each age group presented "per hundred".    Say, you want to check vaccinated in Austria for 2/19/21.
Summing up respective numbers from each age groups (i.e. 18-24, 25-49, 50-59, 60-69, 70-79, 80+) for this date in Austria gives  37.33 for "people_vaccinated_per_hundred" and 24.51 for  "people_fully_vaccinated_per_hundred".
 But in file https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.xlsx  for the same date and country (i.e. 2/19/2021, Austria) the people_vaccinated_per_hundred  = 3.69 and  people_fully_vaccinated_per_hundred = 2.51, i.e. in other words, those are 10 times less than in the  vaccinations-by-age-group.csv file. 
So, it seems that numbers represented in vaccinations-by-age-group.csv file  is not "per hundred",  but rather "per thousand".
Please, provide updates on this issue and please, specify,  which file of the two ones mentioned above was actually updated.

**Comment by edomt** [comment]
Dear @sunset001 

The figures by age given as `people_vaccinated_per_hundred` and `people_fully_vaccinated_per_hundred` are given _per age group_ (i.e. the denominator is the number of people in that age group in the country, rather than the entire population). Therefore you cannot simply sum up these figures to get the national count. (What you'd need to calculate is a average of these numbers, weighted by the share that each age group represents in the country's population.)

Both sets of figures in `owid-covid-data` and `vaccinations-by-age-group.csv` are therefore correct.
