### ISSUE TITLE
Missing UK Testing Data

### ISSUE THREAD

**Issue by Mezzical** [owid/covid-19-data#1796]
UK test count before 7-13-2020 is now missing from the dataset

**Comment by camappel** [comment]
Thank you for your feedback. Current testing figures include both PCR and antigen test in Scotland, Wales, and N. Ireland, and only PCR tests in England; these data by testing type are only available from 7-13-2020. We are in the process of deciding which tests to include in the historical data in order to ensure that only diagnostic tests are included, as per the case definition, which changes across time and between constituent countries (https://coronavirus.data.gov.uk/details/about-data#daily-and-cumulative-numbers-of-tests).

**Comment by edomt** [comment]
This has now been fixed
