### ISSUE TITLE
people_fully_vaccinated fix 

### ISSUE THREAD

**Issue by alb-ctrl** [owid/covid-19-data#1819]
Im not sure if this has been addressed before
but it would be useful if the people_fully_vaccinated entry could be carried through time when there is not a new entry for that date 
for example in country X in 2021-08-04 the value is 1294353 but in 2021-08-05 the value is 0
if the data from the previous day can be carried when there is not a new entry that would be useful.
unless is deliberate left that way for a reason

**Comment by edomt** [comment]
Hi @alb-ctrl 

This is done on purpose: when `people_fully_vaccinated` is left blank in the data, it's because we don't know what the number is on that date. Given the absence of information from the source, we can't know whether it's still the same as the previous day, or if it has increased but without being reported. Therefore, we prefer keeping it blank, and leaving the choice to our users to run a forward-fill if they wish to do so.
