### ISSUE TITLE
Israel Population is incorrect

### ISSUE THREAD

**Issue by akarlinsky** [owid/covid-19-data#182]
The population estimate you have for Israel in 2020 is too low (8.65 million persons). 

According to the Israeli Central Bureau of Statistics, the population on the eve of 2020 was 9.1405 million persons and the latest figure (August 2020) is 9.2412 million persons.

If you wish to verify, The population series generator (in English) is available [here].(https://www.cbs.gov.il/en/Statistics/Pages/Generators/Time-Series-DataBank.aspx?r=ea3bd53b-b8ef-4c4a-8f6f-8eb5e8cdb84f&uptodate=1)

**Comment by edomt** [comment]
Hi @akarlinsky — the data we're using for 2020 is from the latest United Nations World Population Prospects dataset, including our estimate for Israel's population. As these are estimates, it's of course entirely likely that some national figures may differ (especially if a country has conducted a new census very recently) but for consistency we go with the latest UN population release for all countries, rather than going to each national source individually.
