### ISSUE TITLE
Belgium data not updated 16-17 November but data is present in ECDC and MOH source

### ISSUE THREAD

**Issue by DrBazUK** [owid/covid-19-data#184]
Guys, firstly please accept my very great thanks for the effort -it must be Herculean and we all owe you a debt for the fantastic collection, error checking and general data wrangling done here.

I spotted an uncharacteristic gap in the data today, however as Belgium's data is missing from 16 and 17 November with the latest included being from the 15th.

I suspect that this will be resolved relatively quickly but wanted to check that it hadn't crept through unnoticed.

Thanks again!

**Comment by edomt** [comment]
Hi @DrBazUK, and thank you! We're glad to know our efforts are useful!

We've recently introduced this change: we remove the last 2 days of data from the time series for Belgium cases and deaths, due to reporting lags. These delays are actually fairly short in Belgium, as the data is almost complete after 2 days; but before that, the official data (and thus the ECDC data) often presents a large drop, which we want to avoid showing.

We're in the process of changing our source from ECDC to Johns Hopkins (see here: https://github.com/owid/covid-19-data/tree/master/public/data), so we'll very soon reevaluate how this affects the new data.
