### ISSUE TITLE
Testing Data: Tests Performed and Samples Tested 

### ISSUE THREAD

**Issue by limyeeqing126** [owid/covid-19-data#1847]
Hi, thanks for the effort in compiling the testing data. I would like to clarify with you how you differentiate the testing data is testes performed or samples tested. Do you have any criteria to differentiate them? For example, Singapore testing data, the local source mentions the data as swab test tested, then it is categorized as samples tested in OWID. 

Appreciate you could explain the difference between tests performed and samples tested. 

Thank you in advance.

**Comment by camappel** [comment]
We use four categories for testing units: people tested, samples tested, tests performed, and units unclear. In general, we try to reflect the units given by the source as closely as possible. The difference between 'samples tested' and 'tests performed' is therefore not clear cut, as it is due to differences in reporting, not definitions; as such, they generally do not point at radically different things. It is possible that in some instances, multiple samples are included for each 'test performed' (although we are unable to confirm whether or not this is the case), in which case the definition would be closer to cases or people tested, but for internal reasons the source may have decided to label it as tests performed.

In the case of Singapore, swabs tested is the same thing as samples tested.
