### ISSUE TITLE
Confirmed COVID-19 deaths for Slovenia differ significantly from JHU

### ISSUE THREAD

**Issue by SergRZ** [owid/covid-19-data#189]
For example OWiD data for Cumulative confirmed COVID-19 deaths on nov 18 is 556, JHU data - 919.

**Comment by edomt** [comment]
Hi @SergRZ 
We have been in touch with the team at https://covid-19.sledilnik.org/ recently to try to understand these differences—they are due to how our current source (the European CDC) collects the data for Slovenia. However, we will very soon change our source from the ECDC to Johns Hopkins University, which should correct this problem entirely.
