### ISSUE TITLE
Missing data for people_vaccinated for Bulgaria

### ISSUE THREAD

**Issue by mkhanka** [owid/covid-19-data#1916]
From 18th Aug no data is available for 'people_vaccinated' for Bulgaria in [vaccinations.csv ](https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv) and in covid-19-data/public/data/vaccinations/country_data/Bulgaria.csv
 but this was available prior to 18th Aug in [vaccinations.csv](https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv). 

Is it because the data is now not published by official source https://coronavirus.bg/bg/statistika ? I would be very grateful if you could tell me why that is.

**Comment by lucasrodes** [comment]
Hi @mkhanka,
Thanks for your message.

As you mention, we stopped reporting this metric for Bulgaria in August. Specifically in commit 8c622f54fb6c4e768261d2b06d6c5deb6fb850c1.

The [official source](https://coronavirus.bg/bg/statistika) is reporting the number of administered doses and people fully vaccinated, but not the number of people vaccinated with at least one dose. In the past we were able to estimate this metric by computing `total_doses - people_fully_vaccinated`, but this relation no longer holds since Janssen (i.e. single-shot vaccine) has been in use.


Hope this solves your question,
Kind regards
