### ISSUE TITLE
US state vaccination data - cumulative data not accumulating

### ISSUE THREAD

**Issue by fmg-tmodel** [owid/covid-19-data#1919]
Hi,

I've noticed an issue in the US state vaccination data (https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/us_state_vaccinations.csv), where I'm seeing that many of the vaccines numbers, including cumulative measures of total vaccination, are systematically missing on certain dates where they shouldn't be missing.

For example, on May 30, 2021, Florida recorded 18,703,929 total vaccinations. On May 31, Florida recorded 0 vaccinations, though it wouldn’t make sense why Florida’s total vaccinations fell from 18,703,929 the previous day to 0 vaccinations the next day. In fact, the same data show that Florida had 58,684 new vaccinations (daily vaccinations) on May 31, 2021, and total vaccinations should reflect that increase: 18,703,929 total vaccinations on May 30 + 58,684 new vaccine doses administered on May 31  should equal 18,762,613 total vaccinations on May 31. On June 1, Florida records 18,821,297, in line with what we would expect.

Thank you for providing a wonderful collection of data!

Tim

**Comment by edomt** [comment]
Hi @fmg-tmodel 

This missing data is because the US CDC did not publish any data on these days. You can find the complete archive of original CDC files [here](https://github.com/owid/covid-19-data/tree/master/scripts/input/cdc/vaccinations). For example, there is no file for May 31, because the CDC didn't update its data on that date. For that reason, the `total_vaccinations` is missing. This empty value should of course not be replaced by a zero, since the total for the previous day was 18,703,929 — but we leave it to the users of our data to decide how they want to interpolate the data (forward-fill, linear interpolation, etc).

**Comment by fmg-tmodel** [comment]
HI @edomt, I do see that your CDC data files are missing information for May 31, but the CDCs website does appear to show data for May 31. For example, you can take a look here: https://data.cdc.gov/Vaccinations/COVID-19-Vaccination-Trends-in-the-United-States-N/rh2h-3yt2/data (filter to May 31, 2021 to see the data). Perhaps you are pulling the CDC data from somewhere else?

**Comment by edomt** [comment]
The "vaccination trends" data from the CDC has significant reporting delays, and therefore always shows a very low number of vaccinations for the last few days (see the graph here: https://covid.cdc.gov/covid-data-tracker/#vaccination-trends)

Therefore we're pulling the data behind [this page](https://covid.cdc.gov/covid-data-tracker/#vaccinations_vacc-total-admin-rate-total) instead.
