### ISSUE TITLE
Portugal: fake data

### ISSUE THREAD

**Issue by diasjoaocarlos** [owid/covid-19-data#1920]
At least the number of new cases for Portugal for the day N doesn't correspond to the 24 hours of the day N! Unfortunately, it corresponds to day N-1!!! Having in consideration the Ministry of Health data!!! Is your source wrong? I think so!!! Could you change source? Where does the data transmission chain fails??? #Truth!

**Comment by edomt** [comment]
We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues

**Comment by davipt** [comment]
All sources and historical pieces of information are reported as "up to N-1 23:59:59" as day "N" (midnight).

The confusion arrises from the fact that when we calculate period differences between day N and day N-M we still keep this value as day N, no matter if it's bi-weekly, 7 days, or 1 day.

The reporter is confused because he'd expect to see e.g. "1908 cases that happened during the day of Aug 30th", whilst [this  chart](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2021-08-19..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Confirmed+cases&Interval=New+per+day&Relative+to+Population=false&Align+outbreaks=false&country=~PRT) shows them on Aug 31th, correctly, as they refer to "up to Aug 31th".
Likewise when we select 7 days or bi-weekly we know the data point corresponds to the 7 or 14 days prior to the date of the point.

Thanks Edouard
