### ISSUE TITLE
Hungary's people_fully_vaccinated data has been cut off at 2021-06-05 recently

### ISSUE THREAD

**Issue by czka** [owid/covid-19-data#1921]
In https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv the last record for Hungary's people_fully_vaccinated data is now at 2021-06-05.

Those data were in place only few days ago, until Sat Aug 21 at least.

**Comment by edomt** [comment]
Hi @czka 

This was a retroactive correction on our part: given that Hungary is using the 1-dose vaccine Johnson & Johnson, the information that they publish in their [daily report](https://koronavirus.gov.hu//cikkek/5-millio-781-ezer-beoltott-262-az-uj-fertozott-elhunyt-egy-beteg) isn't enough to know how many people are fully vaccinated.

The only information given is how many people have received one dose and two doses.

**Comment by edomt** [comment]
Actually, just as I wrote this we received an email with this link: https://444.hu/2021/09/02/minden-eddiginel-reszletesebb-adatokat-tudtunk-meg-arrol-hogy-a-beoltottakat-milyen-aranyban-tamadta-meg-a-koronavirus-magyarorszagon

From this it seems that we should be able to report a new figure for `people_fully_vaccinated` tomorrow.

**Comment by brwirth** [comment]
Hi @edomt. I was about to provide a fix for this, I thought the past data may have been deleted by mistake. But since you say it was on purpose, I don't understand why?

The Hungarian authorities (unfortunately) report a "received 2 doses" number, instead of reporting data as "fully vaccinated" like the rest of the world does, causing an ambiguity about the 1-dose vaccine. But using the daily reported "received 2 doses" number for "fully vaccinated" data would not be incorrect, because it is the closest data you have, given the way information is provided by authorities. Otherwise data is just being omitted currently, in my opinion.

Let me know if you need help with the language of Hungarian sources.

**Comment by edomt** [comment]
Hi @brwirth 

Unfortunately this isn't enough for us — we're not aiming for the closest estimate, but for 100% accurate figures. Since we know with full certainty that the number published as "2 doses received" is _not_ the same as "fully vaccinated" in Hungary, we can't use it. 

At this point it's down to the Hungarian government to publish the correct data; which they seem to have at their disposal, given the FOI data published by 444.hu

**Comment by czka** [comment]
@edomt Understood. Thanks. However, given that Hungary's `people_fully_vaccinated` data are unreliable, why not delete it all for that country, rather than the few recent records only?

On Sat Aug 21 my chart for Hungary in 2021 looked as follows: https://github.com/czka/covid_toll_tool/blob/main/covid_toll_ALL/Hungary_2021.png (see the cyan-ish solid line).

As of yesterday's `owid-covid-data.csv` it would look as the attached one - mind the flattening since 13.06.
![Hungary_2021](https://user-images.githubusercontent.com/1593918/131997214-71fb5660-73bc-46b4-9e6b-13dbce60cb6a.png)

I mean if you asked me, I would either drop the whole column, or continue publishing the data as they were until around Sat Aug 21.

**Comment by edomt** [comment]
We received confirmation from the International Communications Office, State Secretariat for International Communications and Relations, that the part of the report referring to people who received the 2nd dose (`közülük ([\d ]+) fő már a második oltását is megkapt`) also includes those who have received the J&J vaccine. This means we can actually report `people_fully_vaccinated`. On the other hand, we cannot estimate the number of vaccinations administered, as adding the two reported metrics would count J&J vaccines twice.
