### ISSUE TITLE
Ireland "new_cases" for Sept 2nd 21 negative value

### ISSUE THREAD

**Issue by ericdaly** [owid/covid-19-data#1966]
Ireland "new_cases" for Sept 2nd 21 negative value -1707
![image](https://user-images.githubusercontent.com/45198422/133296505-03a5d1c4-ed36-4e8c-afb2-fb82a48097ff.png)

**Comment by edomt** [comment]
Thanks for getting in touch.

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.

This page also lists their sources, country by country.

We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues

Note: the number of cases or deaths reported by any institution—including JHU, the WHO, the ECDC and others—on a given day does not necessarily represent the actual number on that date. This is because of the long reporting chain that exists between a new case/death and its inclusion in statistics. This also means that negative values in cases and deaths can sometimes appear when a country corrects historical data because it had previously overestimated the number of cases/deaths.
