### ISSUE TITLE
MMissing data of people_vaccinated for Moldova

### ISSUE THREAD

**Issue by MehraSakshi** [owid/covid-19-data#1974]
For Moldova, data is available in the github file till Sep 16 but when checking on OWID site, it shows data only till Aug 15. Could you please assist here why data is not flowing to the OWID site. 

Links for reference:
Github - https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Moldova.csv
OWID - https://ourworldindata.org/covid-vaccinations?country=MDA

**Comment by lucasrodes** [comment]
Hi @MehraSakshi,
Thanks for your message.

Since August 15 we have that Moldova started administering J&J doses. Therefore, it was no longer possible to obtain the metric `people_vaccinated` the way we had been doing so far, i.e. by calculating `Total Doze Administrate` - `Persoane vaccinate cu două doze`.

After 15 August we only report the total number of doses and people with the complete vaccination schema. You can find these metrics [here](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&facet=none&pickerSort=asc&pickerMetric=location&Metric=Vaccine+doses&Interval=Cumulative&Relative+to+Population=true&Align+outbreaks=false&country=~MDA) and [here](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&facet=none&pickerSort=asc&pickerMetric=location&Metric=People+fully+vaccinated&Interval=Cumulative&Relative+to+Population=true&Align+outbreaks=false&country=~MDA), respectively.


I hope that this helps.
