### ISSUE TITLE
United States Share of people fully vaccinated against COVID-19

### ISSUE THREAD

**Issue by jqrprogrammer** [owid/covid-19-data#1983]
in the data as of 2021-09-19 the people_fully_vaccinated_per_hundred in the graph and table is 53.93%, but if you see the data this country has the following information:

Population: 332915074
people_fully_vaccinated: 181382976
people_vaccinated_per_hundred: 62.97%
people_fully_vaccinated_per_hundred: 53.93%

**In this case, if I realized the calculation of  people_fully_vaccinated_per_hundred get 54.98%**

In addition to this in the Graph and Table shown in the total of 63.03% but the data, the people_vaccinated_per_hundred is 62.97%

![image](https://user-images.githubusercontent.com/76001622/134002430-7afa6f0a-62c5-4004-b94d-66da686b1e35.png)

**Comment by edomt** [comment]
Hi @jqrprogrammer 

That is because the vaccination data published by the US CDC also includes the following territories:

American Samoa
Micronesia
Guam
Marshall Islands
Northern Mariana Islands
Puerto Rico
Palau
United States Virgin Islands

Therefore, our use a higher denominator of 336,324,782 instead of the usual denominator of 332,915,074 for the US.

**Comment by jqrprogrammer** [comment]
Can you confirm what data you use for fully_vaccinated and vaccinated_people?

**Comment by edomt** [comment]
Yes, that's the right data. You can see it here: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/United%20States.csv

**Comment by jqrprogrammer** [comment]
@edmont thanks for the information, review the information I think the calculation of Share of people only partly vaccinated against COVID-19 is calculate using population 332,915,074 and not 336,324,782

if you realized the calculation of Partly vaccinated with denominator 332,915,074  the result is 9.13% but if you realized the calculation with denominator 336,324,782 the result is 9.04%


It would be better if the US table in the Population data showing the data with which the indicators are calculated and validate the calculation of Share of people only partly vaccinated against COVID-19


![image](https://user-images.githubusercontent.com/76001622/134020480-937e4cd3-3ee6-457d-97e9-af810ef63090.png)


![image](https://user-images.githubusercontent.com/76001622/134020296-18c2f1d8-7e4b-454b-b1a1-562e81bcea91.png)

**Comment by edomt** [comment]
Nice catch, thank you! This is now fixed here.

However, the population denominator in the downloadable file will remain the same: it is actually the correct denominator that we use for other metrics such as cases per capita, deaths per capita, etc.

**Comment by jqrprogrammer** [comment]
@edmont thanks


It generates a bit of noise for me that when we select the Population metric the value of 332,915,074 appears since if someone is based on that value applying the percentages of the graph they will have wrong values ​​of the vaccinated and partially vaccinated

The value of 336,324,782 should be shown, which is with which these percentages are calculated.

![image](https://user-images.githubusercontent.com/76001622/134044878-b8368831-b4a1-4d2f-9434-7780e883c39e.png)

**Comment by marikouda** [comment]
Hi there, I am looking at the vaccination per 100 rates for the USA.  I see that OWID is using a population value of 332,015,253.  I get this from backcalculating using 'total vaccinations' and 'total vaccinations per 100 rate'.  This population value is significantly lower than the UN World Population Prospects (2022 Release) population projection for 2022 of 338,290,000.  I would have expected it to be about 3million higher than 338,290,000 based on the fact that we have to add the population of American Samoa, Puerto Rico etc. to the UNWPP population because the islands are not included in the 338,290,000 value.  If I add all the islands in, I get a USA population value of 3,420,810.  I think this should be used as the denominator.  Have I found a mistake?  Or am I mistaken?  Thanks for all your work.
