### ISSUE TITLE
Calculation of share of global population that is vaccinated?

### ISSUE THREAD

**Issue by fibke** [owid/covid-19-data#1987]
A few questions (and potential issues) about the calculation of the share of the global population that is vaccinated with at least 1 dose.

1/ OWID mentions it uses the [2019 WPP numbers for 2020 population](https://population.un.org/wpp/). Is this the medium-variant scenario? Could you double check you got the numbers right since there are sometimes significant discrepancies with WPP. 

For example, for China, WPP reports 1,439,324 thousands for Mainland China. OWID reports 1,444,216 thousands and the difference cannot be attributed to including or not including Hong Kong SAR, Macao SAR or Taiwan POC. This particular difference is not huge, but in the aggregate across the database the numbers are adding up. So by way of example, could you point us to the datapoint from WPP that conforms with the OWID estimate?

2/ How does the calculation deal with missing vaccination data that is explicitly acknowledged as missing in the dataset? OWID reports NA for Burundi, Eritrea, Marshall Islands, Micronesia, Palau and the Vatican. Are these countries excluded from both numerator and denominator when calculating the share of people vaccinated?

3/ How does the calculation deal with countries that are not featured in the OWID dataset? These include: North Korea (with a population fo 25 million), Nauru, Tonga, Turkmenistan (population around 6 million) and Tuvalu. When calculating the global share of people vaccinated are these countries excluded from both the numerator and denominator? 

Thank you in advance for clarifying!

**Comment by edomt** [comment]
Hi @fibke 

1/ We use the 2019 edition of UNWPP, indeed with the medium-variant scenario, but with the **2021** estimates. (If you see any remaining mention of "2020 estimates" in our documentation, please let us know, as we should fix it!). 1,444,216,000 is the figure reported for China — the latest file is available [here](https://population.un.org/wpp/Download/Standard/CSV/).

2–3/ There is actually a mixed bag of situations in the countries you've listed. I'm not sure what you mean by "explicitly acknowledged as missing in the dataset", as I don't think we've listed missing countries anywhere in particular? (Maybe you mean that their vaccination variables are set to `NA` in our `owid-covid-data` files, but that's merely because of the outer join with the Johns Hopkins cases & deaths data. They don't appear in [our actual vaccination dataset](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv).)

– Burundi, Eritrea, North Korea: as far as we know, these countries have not reported any vaccination figures, and based on media reports it seems that's because they haven't vaccinated anyone. (Burundi said it would vaccinate against COVID-19 on July 29, but we haven't found any new reports since.) Therefore, their population is included in the world population estimate for the denominator.

– Marshall Islands, Federated States of Micronesia, Republic of Palau: the US CDC reports vaccinations in these territories as part of the US data, which is why they don't appear as separate entities in our dataset. But this means that when calculating the share of the global population that is vaccinated, they appear in both the numerator (as part of `United States`) and the denominator.

– Vatican: same as the previous item, but with Italy including these vaccinations in its data.

– Nauru, Tonga, Turkmenistan, Tuvalu: these territories are already included in our vaccination dataset.

I hope this helps!

**Comment by fibke** [comment]
Yes, the main source of confusion was the occasional reference to 2020 population data where you've been using 2021 numbers. Thanks for the clarification on the other points.
