### ISSUE TITLE
**Honduras ( 20 September )**

### ISSUE THREAD

**Issue by lucasrodes** [owid/covid-19-data#1997]
**Honduras ( 20 September )**

Total Doses Administered: 5,034,639
1 Doses: 3,042,472
2 Doses: 1,992,167

Source: https://twitter.com/Covid19Honduras/status/1440516586310279169

_Originally posted by @Javierpedatos in https://github.com/owid/covid-19-data/issues/230#issuecomment-925351951_

**Comment by lucasrodes** [comment]
@Javierpedatos

I think that "VACUNADOS" refers to people vaccinated and not doses administered. The numbers for the last update would therefore be:

- doses administered: 7,026,806
- people vaccinated: 5,034,639
- people fully vaccinated: 1,992,167

**Comment by Javierpedatos** [comment]
@lucasrodes 

In the image reported by the Ministry of Health of Honduras to the word vaccinated if it refers to administered doses because it specifies first and second doses also if the amount of them is added gives the number of administered doses.


In the following link you can see the vaccination data all the way down . (http://www.salud.gob.hn/site/)

![Captura de pantalla (4463)](https://user-images.githubusercontent.com/79803615/134539111-75043d75-f25e-476b-be7f-c82d1677fcec.png)

**Comment by lucasrodes** [comment]
It has now been fixed. Thanks for your feedback!
