### ISSUE TITLE
Incorrect Total vaccination count for Australia

### ISSUE THREAD

**Issue by nickybisht** [owid/covid-19-data#2036]
As per Govt website as of Sep 30, 2021, 11,357,591 people are fully vaccinated in  Australia.
Source: https://www.health.gov.au/sites/default/files/documents/2021/10/covid-19-vaccine-rollout-update-1-october-2021.pdf

https://www.health.gov.au/initiatives-and-programs/covid-19-vaccines/numbers-statistics 

Github seems to be showing incorrect data. As per github the stats for fully vaccinated people are: 11202638. 
https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Australia.csv

Please check and correct the data. 

As per OWID as well the total people vaccinated are ~44%
But as per https://www.health.gov.au/initiatives-and-programs/covid-19-vaccines/numbers-statistics  its ~55% (as of Sep 30, 2021)

**Comment by lucasrodes** [comment]
Hi @nickybisht,
Thanks for the report.

> Github seems to be showing incorrect data. As per github the stats for fully vaccinated people are: 11202638. https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Australia.csv

We use https://covidlive.com.au/vaccinations, as it enables us to programmatically import new data every day. There might be small differences, mostly due to the time of reporting (some hour differences). However we are investigating this issue further.

> As per OWID as well the total people vaccinated are ~44% But as per https://www.health.gov.au/initiatives-and-programs/covid-19-vaccines/numbers-statistics its ~55% (as of Sep 30, 2021)

We compute the percentages using the **total population**. Health.gov.au uses population +16 years old, in the report you can read: "...of people over the age of 16 are fully vaccinated..."
