### ISSUE TITLE
Partially vaccinated data not visible for Zambia.

### ISSUE THREAD

**Issue by tushartify** [owid/covid-19-data#2045]
Hi,

Partially vaccinated data for Zambia is not available in [feed](https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv) and on [OWID](https://ourworldindata.org/covid-vaccinations?country=ZMB) after September 7. Is this something which is expected due to introduction of a single-dose vaccine (which is also the case for some other countries' data)? Please confirm.

Also, do you have a list/log of such countries where partial vaccination data calculation has stopped?

**Comment by lucasrodes** [comment]
Currently, we are only able to report all figures in the chart that you mention for those countries that provide data on:

- People with at least one dose
- People fully vaccinated

This is due to how our pipeline is set up. 

So far, our interpretation for [the source for Zambia](https://rtc-planning.maps.arcgis.com/apps/dashboards/3b3a01c1d8444932ba075fb44b119b63) has been:

- Fully Vaccinated: Measures the number of fully vaccinated people.
- Total Vaccination: Measures the number of doses administered.

However, we are however revisiting this interpretation with the officials.


> Also, do you have a list/log of such countries where partial vaccination data calculation has stopped?

No, we currently don't provide such list.
