### ISSUE TITLE
About US positive rate in owid-covid-data.csv

### ISSUE THREAD

**Issue by AnnaNishino** [owid/covid-19-data#207]
Hello!

I would like to ask about US positive rate at https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv.
It seems this file has positive rate once a week here from last week.
Is this because of Department of Health & Human Services's data itself, or any other reason?\
Thank you!

**Comment by edomt** [comment]
Hi @AnnaNishino 

The positive rate we use for the United States is collected directly from the [Weekly Surveillance Summary of U.S. COVID-19 Activity](https://www.cdc.gov/coronavirus/2019-ncov/covid-data/covidview/index.html) report published weekly by the U.S. Center for Disease Control and Prevention. That's why it only shows data on a weekly basis. A new report has been published by the CDC on Friday, so today's update will add a new data point for the positive rate up to November 28.

Note that it's pretty difficult to calculate a single positive rate for the United States as a whole (which is why we prefer trusting the CDC for its calculation). The COVID Tracking Project recently published a very interesting summary of what makes it so complex: [Test Positivity in the US Is a Mess](https://covidtracking.com/blog/test-positivity-in-the-us-is-a-mess)

Ed
