### ISSUE TITLE
Illinois Vaccinations and Kentucky Data jump on 10/29/2021

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#2102]
I observed that Illinois and Kentucky have abnormal data starting from 10/29/2021. 
Here is the link: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/us_state_vaccinations.csv?raw=true
Other than the huge jump, Kentucky also lack of whole September and October data, which does not look good. Could you take a look at these 2 states data?
![image](https://user-images.githubusercontent.com/68354122/139598555-179373cb-4a34-4a72-9518-f77e1ff039e2.png)
![image](https://user-images.githubusercontent.com/68354122/139598608-fca08872-ecd4-4d39-bb31-470cd15cc90c.png)

**Comment by edomt** [comment]
Hi @RuijingZ 
US vaccination data is improved so that vaccinations always increase monotonically. When the CDC issues new figures that are lower than previous ones, it can therefore create gaps in the time series.
You can see the original daily data from the CDC here: https://github.com/owid/covid-19-data/tree/master/scripts/input/cdc/vaccinations
