### ISSUE TITLE
New cases for Turkey for 11 December 2020 seem incorrect

### ISSUE THREAD

**Issue by emesbe123** [owid/covid-19-data#212]
Hi There
The new cases reported for Turkey for 11 December 2020 is 824907 where other sites report 32106.  Is this a data reporting correction or a typo
TIA
MB

**Comment by edomt** [comment]
Hi @emesbe123 
This is indeed due to a one-off data correction (and a massive one). There are a couple issues opened in the Johns Hopkins GitHub repo (which is where we take our data from):
- https://github.com/CSSEGISandData/COVID-19/issues/3446
- https://github.com/CSSEGISandData/COVID-19/issues/3454
Ed

**Comment by emesbe123** [comment]
Hi Ed

Thanks for this.  Wow, what a massive correction!

MB
________________________________

**Comment by analphabit** [comment]
That's a massive correction because the Turkish officials decided to massively distort the numbers since July. They excluded asymptomatic cases to keep the numbers low and to avoid risk warnings during holiday season.

Now they seem to have added all "forgotten" asymptomatic cases at once.

The 32.106 is the correct number for new reported cases only for this day.
