### ISSUE TITLE
data(vax, china): update

### ISSUE THREAD

**Issue by lucasrodes** [owid/covid-19-data#2128]
### China Update on 2021-11-12

1. Update on 2021-11-12: <http://www.nhc.gov.cn/xcs/s3574/202111/4ed1e55f05af44e0a4b2d2fc52b99afe.shtml>
> 截至**11月12日**，全国累计报告接种新冠病毒疫苗**23亿7271.3万**剂次，完成全程接种的人数为**10亿7384.5万**人。

> 目前，3-11岁人群已经接种了8439.5万人，加强免疫已经接种**4944万**人，我们将力争在12月底完成3-11岁人群的全程接种工作。

2. The data from WHO on 2021-10-29 is inconsistent with the data from NHC China. According to <http://www.nhc.gov.cn/xcs/s3574/202110/66acdf3ec40b41929944224c65b1d85c.shtml>, the data on 2021-10-29 should be as shown in the following table.

Summary:
| location  |      date      | total_vaccinations | people_vaccinated | people_fully_vaccinated | total_boosters |
| :-------: | :------------: | -----------------: | ----------------: | ----------------------: | -------------: |
|   China   |   2021-06-10   |          845299000 |         622000000 |                         |                |
|   China   |   2021-08-12   |         1832450000 |                   |               777046000 |                |
|   China   |   2021-08-26   |         2003914000 |        1072500000 |               889439000 |                |
|   China   |   2021-09-06   |         2113083000 |        1095000000 |               969720000 |                |
|   China   |   2021-09-15   |         2161428000 |                   |              1011584000 |                |
|   China   |   2021-09-18   |         2174043000 |        1100842000 |              1022207000 |                |
|   China   |   2021-09-28   |         2206054000 |                   |              1047872000 |                |
|   China   |   2021-10-23   |         2244727000 |                   |              1067621000 |                |
| **China** | **2021-10-29** |     **2262226000** |                   |          **1070386000** |                |
|   China   |   2021-11-05   |         2311626000 |                   |              1072454000 |       37973000 |
| **China** | **2021-11-12** |     **2372713000** |                   |          **1073845000** |   **49440000** |

@edomt @lucasrodes

_Originally posted by @aywi in https://github.com/owid/covid-19-data/issues/230#issuecomment-968091637_

**Comment by lucasrodes** [comment]
Hi @aywi,
Thanks for reporting.

Could you elaborate on why the data from 2021-10-29 from WHO is not consistent with NHC China? I would say that all values could go together.

- total vaccinations: 2262226000 (NHC China)
- people vaccinated: 1155058478 (WHO)
- people fully vaccinated: 1070386000 (NHC China)

**Comment by aywi** [comment]
1. [ZF2001](https://en.wikipedia.org/wiki/ZF2001) contributes a lot to the total count of COVID-19 vaccinations in Mainland China, so the figure for people_vaccinated/people_fully_vaccinated is not the same as other two-dose/one-dose countries, but also not the same as the three-dose country like Cuba.

2. According to the latest data from <https://covid19.who.int/region/wpro/country/cn>, on 2021-10-28 (**and is not 2021-10-29**):
- total vaccinations: 2,272,044,058 (significantly larger than 2,257,584,000 from NHC China on 2021-10-28, and 2,262,226,000 on 2021-10-29)
- people vaccinated: 1,155,058,478
- people fully vaccinated: 1,014,759,580 (significantly lower than 1,070,386,000 from NHC China on 2021-10-29)

WHO China region should include Mainland China, Hong Kong, Macau, and Taiwan, but somehow the data neither match the total count from all four regions (people fully vaccinated) nor the count from Mainland China (total vaccinations). So this data source is unreliable.

2. NHC China has not published new people_vaccinated data since 2021-09-18. However, from the latest news conference <http://www.nhc.gov.cn/xcs/s3574/202111/4ed1e55f05af44e0a4b2d2fc52b99afe.shtml>:

> 目前，3-11岁人群已经接种了**8439.5万**人，加强免疫已经接种4944万人，我们将力争在12月底完成3-11岁人群的全程接种工作。

China starts the vaccination for the 3~11-year-old in late October, so this 84,395 million should totally be added to people_vaccinated. That means people_vaccinated for 2021-11-12 should be > 1100842000+84395000=1185237000. If OWID accepts this kind of lower bound estimation from the government source, then the figure will become:

| location  |      date      | total_vaccinations | people_vaccinated | people_fully_vaccinated | total_boosters |
| :-------: | :------------: | -----------------: | ----------------: | ----------------------: | -------------: |
|   China   |   2021-06-10   |          845299000 |         622000000 |                         |                |
|   China   |   2021-08-12   |         1832450000 |                   |               777046000 |                |
|   China   |   2021-08-26   |         2003914000 |        1072500000 |               889439000 |                |
|   China   |   2021-09-06   |         2113083000 |        1095000000 |               969720000 |                |
|   China   |   2021-09-15   |         2161428000 |                   |              1011584000 |                |
|   China   |   2021-09-18   |         2174043000 |        1100842000 |              1022207000 |                |
|   China   |   2021-09-28   |         2206054000 |                   |              1047872000 |                |
|   China   |   2021-10-23   |         2244727000 |                   |              1067621000 |                |
| **China** | **2021-10-29** |     **2262226000** |                   |          **1070386000** |                |
|   China   |   2021-11-05   |         2311626000 |                   |              1072454000 |       37973000 |
| **China** | **2021-11-12** |     **2372713000** |    **1185237000** |          **1073845000** |   **49440000** |

source_url for 2021-10-29: http://www.nhc.gov.cn/xcs/s3574/202110/66acdf3ec40b41929944224c65b1d85c.shtml
source_url for 2021-11-12: http://www.nhc.gov.cn/xcs/s3574/202111/4ed1e55f05af44e0a4b2d2fc52b99afe.shtml

**Comment by lucasrodes** [comment]
Thanks!
