### ISSUE TITLE
Vaccination figures in Russia

### ISSUE THREAD

**Issue by timdonovanuk** [owid/covid-19-data#216]
Yet nothing on US or Russia?

"Dec. 2 More than 100,000 Russians at higher risk of severe coronavirus cases have been vaccinated with the domestically made Sputnik V vaccine, Health Minister Mikhail Murashko said at a special session of the UN General Assembly Wednesday."

**Comment by edomt** [comment]
Hi @timdonovanuk 
In order to keep this manageable, we really need to collect data as *directly* reported on official websites, in press releases, or by social media accounts of national authorities. If you're aware or can find an official website that reports a number of vaccine doses administered in Russia, we'll be very interested in adding it to our data.
So far we've received a few second-hand reports such as the one you quote, but nothing has appeared on official websites such as https://стопкоронавирус.рф/ or https://sputnikvaccine.com/.

**Comment by timdonovanuk** [comment]
UN Press Report: https://russiaun.ru/en/news/sv_0212 

"While the clinical trials are going, we have started to vaccinate high risk population groups. To date more than one hundred thousand citizens have already been vaccinated."

**Comment by edomt** [comment]
@timdonovanuk We have now added figures for Russia, see https://twitter.com/redouad/status/1339588081100308482
