### ISSUE TITLE
total_tests in France 

### ISSUE THREAD

**Issue by odadoun** [owid/covid-19-data#2160]
'total_tests' (cumulative tests) seems to be not available for France but 'new_tests' (new per day) yes.
Does the total_tests is the sum of new tests ? if yes why it is not apply for France ?
By advance thank you
And thanks for all your work

**Comment by camappel** [comment]
Bonjour,

The time series for 'Daily change in cumulative total' begins 15 May 2020. As such, we are not able to publish any cumulative total, since no information is available on how many people had been tested prior to the first day of reporting. More information is available in the 'Ressources' section [here](https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-resultats-des-tests-virologiques-covid-19/#resources).

Total_tests only equals the sum of new tests if a continuous time series is available since the very first test; this is rare, however. Most of our total_tests figures are taken directly from the source.
