### ISSUE TITLE
Romania people_vaccinated gap since 09/28/2021

### ISSUE THREAD

**Issue by RuijingZ** [owid/covid-19-data#2174]
Romania people vaccinated only report 1 day data on 11/28/2021 since September 28. May I ask if there is any reason behind it?

![image](https://user-images.githubusercontent.com/68354122/144862856-ff1917f5-6a3f-45bb-9030-33e702a31776.png)

**Comment by edomt** [comment]
Hi @RuijingZ 

The data published by the Romanian government doesn't allow us to calculate any value for `people_vaccinated`. That's because the only metrics that they report are:
- Total doses administered
- Total people fully vaccinated

Given that boosters are now also administered, it's impossible to infer `people_vaccinated` based on this data alone. For that reason, our script fetches the latest value of `people_vaccinated` reported by Romania to the WHO, to make sure we show at least once recent value for that metric.
