### ISSUE TITLE
Calculate extra decimal for positivity rate

### ISSUE THREAD

**Issue by EwoutH** [owid/covid-19-data#2176]
Currently the positive rate (percentage positive tests) is only calculated to a single decimal precision, so for example as 1.2%. For countries that test a lot, such a [Denmark](https://ourworldindata.org/coronavirus/country/denmark#are-countries-testing-enough-to-monitor-their-outbreak), the precision is not high enough. The jumps from 0.1% to 0.2% are huge for example. So I would suggest adding an extra decimal to the calculation of the positivity rate.

![positive-rate-daily-smoothed](https://user-images.githubusercontent.com/15776622/144923281-2ef44eb1-8d5d-4c20-b1f0-a630261f043d.png)

**Comment by edomt** [comment]
Hi @EwoutH 

The issue here is that showing more than a single decimal would overstate how precise these figures truly are. We know that there are many things that make these calculations approximate:

- Uncertainties around the number of confirmed cases
- Delay between specimen date and reporting date
- Uncertainties around the number of tests
- Delay between test date and reporting date

Because of this, showing for example a positive rate of 1.31% would give an overconfident impression about what we truly know about this metric. In other words, this final digit wouldn't really be a significant figure. The data at our disposal definitely makes it relevant to show the difference between 1% and 2%, and between 1.3% and 1.4%, but not between 1.30% and 1.31%

**Comment by EwoutH** [comment]
Thanks for the extensive reply. Could we otherwise use some threshold value for the number of significant figures? Most of the time, when the percentage positive is low this is because there has been a lot of testing. Also, in the graphs a 7-day rolling average is displayed, so this increases the available data with a factor 7 on average.

I would propose a threshold of 2%. So a precision of 0.1% for numbers equal or larger than 2%, and 0.01% precision for numbers smaller than 2%.

**Comment by EwoutH** [comment]
The current rounding just looks weird and does not represent the data properly.

![positive-rate-daily-smoothed 2](https://user-images.githubusercontent.com/15776622/145569844-4fa0bfdf-e660-4f6a-883f-0bd99506c358.png)
