### ISSUE TITLE
New and total vaccinations (smoothed) in Bangladesh

### ISSUE THREAD

**Issue by MikihiroMatsuoka** [owid/covid-19-data#2183]
Dear sir or madam,

Thank you very much as always for your hard work on updating so many statistics.

On the new vaccinations (smoothed per million) and total vaccinations (per hundred) for Bangladesh, 
I found large jumps on Decemver 10, 2021: from 5,758 (Dec 9) to 22,891 (Dec 9) on new vaccination series (smoothed per million),
and from 64.08% (Dec 9) to 76.48% (Dec 10) on total vaccination series  (per hundred).
I would be very grateful to know, if possible, whether this reflects an addition of the past data that had not been counted until Dec 9 without retroactivly revising the past series.

Thank you again and kind regards,
Mikihiro Matsuoka
[211214-New_and_Total_vaccination_Bangladesh.xlsx](https://github.com/owid/covid-19-data/files/7709319/211214-New_and_Total_vaccination_Bangladesh.xlsx)

**Comment by edomt** [comment]
Hi @MikihiroMatsuoka 

Given the very sudden rise in vaccinations in the time series, we've interpreted this change to be part of a data correction published by the government of Bangladesh, probably due to a backlog of uncounted vaccinations.

Unfortunately, they haven't published any corrected time series, so for now we can only keep the change on the specific date that it was published.

![image](https://user-images.githubusercontent.com/7103774/146025910-a18d8dc7-6c79-407d-be7a-3398074f4a52.png)
(http://103.247.238.92/webportal/pages/covid19-vaccination-update.php)

**Comment by MikihiroMatsuoka** [comment]
Dear Mr Edouard Mathieu,

Thank you for your prompt reply despite your busy schedule.
Much appreciated!

Kind regards,
Mikihiro Matsuoka

2021/12/15 0:17、Edouard Mathieu ***@***.***>のメール:

﻿
Hi @MikihiroMatsuoka

Given the very sudden rise in vaccinations in the time series, we've interpreted this change to be part of a data correction published by the government of Bangladesh, probably due to a backlog of uncounted vaccinations.

Unfortunately, they haven't published any corrected time series, so for now we can only keep the change on the specific date that it was published.


(http://103.247.238.92/webportal/pages/covid19-vaccination-update.php)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
