### ISSUE TITLE
Ireland Total vaccination count as of Dec 15

### ISSUE THREAD

**Issue by MehraSakshi** [owid/covid-19-data#2192]
Ireland total vaccination count as per irish health service site: https://www.hse.ie/eng/services/news/newsfeatures/covid19-updates/vaccination-programme-dashboard-as-of-15-december-2021.pdf is 7,556,513 but the feed (https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv
) is providing 8815665 on the date Dec 15th, whereas the feed is extracting data from Health service executive https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/locations.csv
as mentioned in this link.

Checking further we found less count is presented on the site : https://covid-19.geohive.ie/pages/vaccinations Total Vaccines Administered is 7,467,553 up to December 19, 2021.

Can you please confirm and correct if the feed stats are wrong?

**Comment by edomt** [comment]
Hi @MehraSakshi 

The `Total Vaccines Administered` box on the official dashboard actually doesn't include booster doses. As you can see here, the three numbers at the top sum up to the number at the bottom: 

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/7103774/146779609-5c536ed4-dc24-432d-926f-33e55e105918.png">

Because our metric `total_vaccinations` counts all doses (including boosters), we add the boosters (1,535,060 so far) to this number to get the total count.
