### ISSUE TITLE
USA Deaths mismatch on 4/16/2020

### ISSUE THREAD

**Issue by smbasha47** [owid/covid-19-data#22]
USA deaths are showing up 4928 on 4/16/2020 but in other sources, it's around 2500 can you please the check the data?

**Comment by HannahRitchie** [comment]
Hi smhasha47,

Thank you for your comment. We are of course aware of this significant jump in daily deaths in the US on 16th April. This was due to a large methodological change in how deaths are counted, particularly in NY. The definition was extended from deaths diagnosed in hospital to also include estimates from homes and nursing homes.

This was also reflected in the Johns Hopkins University database (which reported similar figures on 16th April): https://coronavirus.jhu.edu/map.html
