### ISSUE TITLE
Reconciling France UNWPP Denom data

### ISSUE THREAD

**Issue by beansrowning** [owid/covid-19-data#2206]
Hello,

I see that in 89839c8054f9ea965b3360c3a9378344f6c8bd14 and a few parent commits, your population denominator data has been updated to midyear-2021 projections. We've proceeded similarly on our end, but I've had trouble reconciling the OWID listed value for France, which indicates the data provenance is UN WPP.

From [population_latest.csv](https://github.com/owid/covid-19-data/blob/master/scripts/input/un/population_latest.csv):

entity | iso_code | year | population | source
-- | -- | -- | -- | --
France | FRA | 2021 | 67564251 | https://population.un.org/wpp/Download/Standard/CSV/

Pulling from this source, however, I'm seeing considerably lower values across all projection variants. 

From UNWPP [Total Population, All variants](https://population.un.org/wpp/Download/Standard/CSV/) (PopTotal in 1000s):

Location | VarID | Variant | Time | PopTotal
-- | -- | -- | -- | --
France | 2 | Medium | 2021 | 65426.177
France | 3 | High | 2021 | 65504.826
France | 4 | Low | 2021 | 65374.698
France | 5 | Constant fertility | 2021 | 65440.8
France | 6 | Instant replacement | 2021 | 65480.975
France | 7 | Zero migration | 2021 | 65376.946
France | 8 | Constant mortality | 2021 | 65418.4
France | 9 | No change | 2021 | 65419.265
France | 10 | Momentum | 2021 | 65419.391

The "France (and dependencies)" entry is closer, but still off:

Location | VarID | Variant | Time | PopTotal
-- | -- | -- | -- | --
France (and   dependencies) | 2 | Medium | 2021 | 68325.35

We've been using the medium projection variant, 65426177, which is off by some ~2M.

I thought to check [Eurostat](https://ec.europa.eu/eurostat/databrowser/view/tps00001/default/table?lang=en) as well, and this is much closer (67439599), but still not matching.

All other values with a stated provenance from UNWPP seem to align with the medium variants in this file, so is there a different source for the France numbers, or possibly something I've missed?

**Comment by edomt** [comment]
Hi @beansrowning 

This is unfortunately a complicated situation!

The [French vaccination data](https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1/) is supposed to include oversea territories, but:
- It's not clear which ones are included in the national file that we use
- There have been a lot of issues with the counting of oversea vaccinations since November
- Vaccinations in oversea territories have been removed from some files published on the government's platform

Initially, what we had done was sum up the UNWPP estimate for France with the ones for the oversea territories that we thought were included in the French vaccination statistics (Guadeloupe, Martinique, Réunion, Mayotte, Saint Barthélémy, Saint Martin, Guyane). But after looking into it again today, I think it'd be safer to assume that all oversea territories are included in the national file that we use (`vacsi-v-fra-YYYY-MM-DD-HHhMM.csv`). But then it seems that the UNWPP estimate for France + dependencies is a bit high (>68M).

Therefore, we'll now use [the latest national estimate produced by INSEE](https://www.insee.fr/fr/statistiques/5012724), which stands at 67,422,000 for 2021 (all territories included).

Thanks for bringing this up!

**Comment by beansrowning** [comment]
Thanks for the cogent response!

Yes, it's a difficult problem indeed, so I appreciate how thorough you all are in thinking it through.

All the best.
