### ISSUE TITLE
Count of fully vaccinated missing for Trinidad and Tobaga - 9 April 2021 to 12 August 2021

### ISSUE THREAD

**Issue by MehraSakshi** [owid/covid-19-data#2221]
For location “Trinidad and Tobaga” Covid vaccination data is stale. As per feed https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv from 9 April 2021 to 12 August 2021, count of people fully vaccinated is missing. The count directly spikes from 4777 (8 April 2021) to 444328 (13 August 2021).

Can you please confirm and correct if the feed stats are wrong?

**Comment by edomt** [comment]
Hi @MehraSakshi 

I'm not sure that I fully understood the description of this issue:

- The data is not stale - it is updated every day, and the time series goes to 2022-01-03
- The data is also not wrong - it reflects what is published by the government of T&T
- I think you were referring to the field `people_vaccinated` rather than `people_fully_vaccinated`?

In any case, we've managed to add more data from 8 April 2021 to 13 August 2021 for `people_vaccinated` so that the time series is more complete.
