### ISSUE TITLE
Probable under reported covid vaccination data for Norway, Ukraine, Canada, Uruguay 

### ISSUE THREAD

**Issue by mkhanka** [owid/covid-19-data#2224]
For the below countries the vaccination stats are same for the dates: 31st Dec, 2021 - 2nd January, 2022 as per: https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv. 
1. Ukraine  
2. Uruguay  
3. Canada 
4. Norway, the data shown on search has minor changes during 31st Dec, 2021 - 2nd January, 2022 

Can you please confirm if this is expected or data issue?

**Comment by lucasrodes** [comment]
Hi @mkhanka,
Thanks for your message.

I can see all metrics remaining constant for Uruguay and Ukraine, but not for Canada and Norway, could you double-check this?

Regarding Ukraine and Uruguay:
- Ukraine: We source the data from [Ukrain Government](https://health-security.rnbo.gov.ua), specifically from API endpoints https://health-security.rnbo.gov.ua/api/vaccination/process/chart?dose=2 and https://health-security.rnbo.gov.ua/api/vaccination/process/chart?dose=1. For both sources, the data points registered during these days remain constant.
- Uruguay: We source it from the Ministry of Health via a [third party project](https://github.com/3dgiordano/covid-19-uy-vacc-data): https://github.com/3dgiordano/covid-19-uy-vacc-data/blob/main/data/Uruguay.csv

This is likely due to the governments not releasing new data during New Year's Eve.

I hope this helps
