### ISSUE TITLE
Under reported covid vaccination data for Norway

### ISSUE THREAD

**Issue by nickybisht** [owid/covid-19-data#2227]
With reference to https://github.com/owid/covid-19-data/issues/2224

For Norway:

As per official website(https://www.fhi.no/en/id/vaccines/coronavirus-immunisation-programme/coronavirus-vaccination---statistic/), for Jan 1 - Jan 3, 2022, people partially & fully vaccinated count on OWID(https://ourworldindata.org/covid-vaccinations?country=NOR)/GitHub(https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv) appears to be incorrect. For example, on Jan 3, 2022, the people partially vaccinated count is 4284546 & the fully vaccinated count is 3921663.
However, on OWID(https://ourworldindata.org/covid-vaccinations?country=NOR) having GitHub repo(https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv) as the data source, people partially vaccinated count is 4284415 & the fully vaccinated count is 3921477 

![image](https://user-images.githubusercontent.com/90417853/148326781-e92e96c6-d0c7-4bb4-8819-464597549e4b.png)

We also checked the previous month data set and there appears to be a discrepancy in those numbers as well.
Therefore, request you to please check and corroborate the stats.

**Comment by edomt** [comment]
Hi @nickybisht 

I'm not sure if I understand what the issue is?

- The discrepancies you're citing are of 0.00003% for `people_vaccinated` and 0.00005% for `people_fully_vaccinated`
- The reason is simply that the Norwegian government is correcting its time series with older records at each update. For example, when we pulled the data from them yesterday, the count on 2022-01-01 for `people_vaccinated` was 4283840. Today it is 4283981 instead. These differences will always appear if you check the data in the evening, because our updates are run in the morning.
