### ISSUE TITLE
US-NH percent vaccinated over 100% inconsistent with other sources

### ISSUE THREAD

**Issue by amstark** [owid/covid-19-data#2232]
Column I Row 13627 > 100% 
New Hampshire January 7 2022
 
 JHU and state webpages reports vaccination at 68% at this time.   This data is inconsistent.

**Comment by edomt** [comment]
Hi @amstark 

I'm not sure where you got that 68% from – the share of people with at least 1 dose in NH is basically close to 100%. You can see that [here](https://covid.cdc.gov/covid-data-tracker/#vaccinations_vacc-people-onedose-percent-total).

The uncertainty comes from the data published by the CDC itself. In the latest version of [its file](https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data), NH has the following data:

```
Administered_Dose1_Recip = 1363378
Census2019 = 1359711
```

This gives us a first-dose uptake of 100.27%, which is what we have in our data.
I am not sure how to reconcile these numbers, but it seems the issue comes from the CDC (maybe the population denominator that they use?)
