### ISSUE TITLE
[Uganda] Stale new_daily_vaccinated_count stats

### ISSUE THREAD

**Issue by nickybisht** [owid/covid-19-data#2246]
For Uganda, people_vaccinated & people_fully_vaccinated stats are missing for Jan 06, 2022. As per GitHub [OWID feed](https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv), these stats are only updated until Dec 20, 2021 . However, the count of total_vaccinations is correctly refreshed up till Jan 06, 2022.
Since there is no bifurcation of people_vaccinated & people_fully_vaccinated stats, the authenticity of the given numbers cannot be corroborated. 

Therefore, request you to check the data discrepancy & help fix the issue, if there’s any.

![image](https://user-images.githubusercontent.com/90417853/148875423-6dfc2fa1-1d49-4f2a-ae50-7a62e465619c.png)
![image](https://user-images.githubusercontent.com/90417853/148875448-2661c3d4-acb8-40b3-89ac-39c279f4412d.png)

**Comment by edomt** [comment]
Hi @nickybisht 

I don't understand what you mean by "Since there is no bifurcation of people_vaccinated & people_fully_vaccinated stats, the authenticity of the given numbers cannot be corroborated."

In the [`country_data`](https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations/country_data) folder you can find country-by-country sources. If you go to [`Uganda.csv`](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Uganda.csv) you can see the exact source of each data point.
