### ISSUE TITLE
Stale stats for For Wales & Northern Ireland

### ISSUE THREAD

**Issue by nickybisht** [owid/covid-19-data#2247]
For Wales & Northern Ireland, OWID vaccination stats viz. people_partially_vaccinated, people_fully_vaccinated & people_with_booster_shot observed to be stale on the [OWID feed](https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv) as the same numbers are repeated since 2/3 days.

For Wales data is last updated: 2022-01-06
For Northern Ireland data is last updated: 2022-01-07

Can you please check and confirm if the stats  are correct.

Github source: https://github.com/owid/covid-19-data/issues

**Comment by edomt** [comment]
Hi @nickybisht 

I'm slightly worried that you've opened several issues recently about extremely minor problems (#2227, #2246, and this one). Unfortunately, we don't have the resources to reply repeatedly to the same questions, so I'll try to be clearer here.

Our data is updated each morning (Europe time), with the latest data reported by each government. In the case of NI and Wales, what you see in the data since yesterday is exactly what they reported yesterday. This morning, we will update the data and you will therefore see exactly what they reported this morning. We have no control over the actual content of what they report: if a government decides to stop refreshing their statistics for a few days, then it will also look like that in our data, because we can't invent numbers.

I would suggest that you browse the [`country_data`](https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations/country_data) folder and check our sources for each country.
