### ISSUE TITLE
Macao booster data

### ISSUE THREAD

**Issue by 36wish** [owid/covid-19-data#2300]
The current source for Macao doesn't report booster data. The old [source](https://github.com/owid/covid-19-data/commit/9275aabb4967af588871e21b254157609c7c5644) does include booster data, but it's only updated once a week.

The URL for getting the booster data is [here](https://www.gov.mo/zh-hant/global-search/?q=%E5%B7%B2%E6%8E%A5%E7%A8%AE%E7%AC%AC3%E5%8A%91), and you parse for the following string已接種第3劑有XXXX人.

**Comment by lucasrodes** [comment]
Hi @36wish,
Thanks for reporting this.


I am reviewing this source, and while I was running some checks on the data, I found some minor issues.

Take the [article](https://www.gov.mo/zh-hant/news/864824/) for 2022-01-20 as an example. It states that:
- Doses: 1017416
- People with at least one dose: 502469
  - People with one dose: 30598
  - People with two doses: 412668
  - People with three doses: 59203


**Sanity check 1**  ✅
```
People with at least one dose =  People with one dose + People with two doses + People with three doses 
          502469              =           30598       +       412668          +       59203
          502469              =                                502469          ✅ 
``` 

**Sanity check 2** ❌
```
Total doses =  1 x People with one dose + 2 x People with two doses + 3 x People with three doses 
  1017416   =             30598         + 2 x         412668        + 3 x          59203
  1017416   =                                1033543          ❌
``` 

As you can see, while _sanity check 1_ mostly holds, _sanity check 2_ never holds. If we add the individual doses, we always have a slightly higher number of doses administered. Do you have any idea why this could be happening? As far as I know, Macao is using Sinopharm & BioNTech, so that I wouldn't attribute this to single-shot vaccines.

Any insights are very appreciated. Thanks for your help & time!

**Comment by 36wish** [comment]
Thank you for looking into this matter.I suspect some of them had their first shot outside Macau and second shot in Macau. I've sent an email to the department to ask and will post any replies.

**Comment by 36wish** [comment]
I have reply from the department to say that it includes overseas vaccinations. They pointed me towards this [page](https://www.ssm.gov.mo/apps1/covid19vaccine/en.aspx#clg18753) which has a link to the [Daily Bulletin on COVID-19 Vaccination](https://www.ssm.gov.mo/docs/19164/19164_562c2ce497d947fa90ea0dea188f4a39_000_.pdf). That PDF shows the daily number of people boosted (local and overseas).

I asked them further will they give breakdowns of local vaccination only, will update with any replies.

**Comment by lucasrodes** [comment]
Hi @36wish,
Thanks for your help, detailed investigation and for reaching out to them. This is incredibly helpful!

This might be good enough to report the vaccination data. Will run some checks, also let me know if you receive any response. 

Kind regards

**Comment by lucasrodes** [comment]
Hi @36wish,
Once again, thanks for your time and help.

I have added this source now and we will start collecting boosters data as of the next data update. 

It would be great if they could add booster data to their nice API: https://www.ssm.gov.mo/apps1/apps/healthdeclaration/monitor/monitor.json, so the data extraction can be done in a cleaner way.

**Comment by 36wish** [comment]
They refused to provide details of local vaccinations. Anyway thank you for your hard work, can see the booster data coming through now.
