### ISSUE TITLE
Date inside for "COVID-19 - Vaccinations.csv" not same as other files

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#233]
Can we have the date in the file "COVID-19 - Vaccinations.csv" the same as that in country files please. At present the date is something like 340 when all others say 2020-12-27. 

BTW - thanks for for adding the new data in country csv files to the bottom. Makes it easier for my App to parse it.

Not sure the UK data of 80000 is correct. If I add up Scotland, England, Wales and N Ireland I do not get that figure.  

I appreciate it is extremely hard to get good data so thanks for putting this together I am using it in my App.

**Comment by edomt** [comment]
Date format: that's because `COVID-19 - Vaccinations.csv` is an internal file. You can use https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations.csv instead.

UK data: the counts currently shown for the UK and its 4 nations all refer to slightly different dates, due to irregular reporting by each nation. This is why the UK total does not currently match the sum of the subnational counts.
The current number for the UK (800,000) is sourced from the press conference delivered by Boris Johnson on 24 December: https://www.gov.uk/government/speeches/prime-ministers-statement-on-eu-negotiations-24-december-2020

**Comment by zizwiz** [comment]
Thanks, I have changed to the vaccination.csv as above in my app now. Thanks for providing the information.
