### ISSUE TITLE
Data for partial and full vaccination

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#234]
I know this will be near impossible to get at the moment but no harm in me asking for it just in case we can get it. Most vaccine need 1 dose then wait 21 days then get second dose then wait a few days then you are vaccinated. At present countries are giving figures of first vaccine but in a few days there will be a mix some getting second dose and some just their first dose. It would be lovely for us to be able to get stats so we know the % population covered a bit better.

**Comment by edomt** [comment]
That is indeed what we hope to be able to report in the medium term. As you say it would be much more informative to express coverage in terms of "people fully vaccinated" in the population rather than "doses per capita". Our ability to do this will depend a lot on countries reporting the data in this way when they start giving second doses. The UK, for example, should in theory start this process next week.
