### ISSUE TITLE
Israel: Shares of people that have received doses of the COVID-19 vaccine by age

### ISSUE THREAD

**Issue by Aric5301** [owid/covid-19-data#2429]
Hi!
It seems that perhaps there is a problem with Israel's data of the share of vaccines received by age. It only shows data newer than Jan 25 2022 on OWID's dashboard:

For example:
![image](https://user-images.githubusercontent.com/25414752/153709980-8318121b-ead3-4840-888e-5306076919a4.png)

Thanks!

**Comment by edomt** [comment]
Hmm, that's because we rely on the file maintained by @dancarmoz at https://github.com/dancarmoz/israel_moh_covid_dashboard_data/raw/master/vaccinated_by_age.csv, and the data only starts on January 25 – I'm not sure why. Is the data available from the official API?

**Comment by Aric5301** [comment]
@erasta keeps track of this data for older dates in his [GitHub Repository](https://github.com/erasta/CovidDataIsrael/tree/master/out/history) using _vaccinationsPerAge_ files.
Please notice that they change over time as additional booster shots are commissioned (for example very old files don't have third dose data as there wasn't a third dose yet).
So perhaps use his repository as the source for this specific data?

**Comment by dancarmoz** [comment]
Hi, I just noticed this - I was not aware this data is being used, sorry for removing previous dates from the main file! It happened since the official data stopped including absolute numbers of doses per age group, forcing me to use significantly different columns, so I started a new file; but it should be easy to reincorporate the older data into the file, and I'll try to do it ASAP (I see that it's not really urgent as you have a workaround, but I assume you'd prefer using just the one file if possible).

Please let me know if there's anything I can do or add to make this file (or any other that you might be using) more useful to you! I'll be happy to help if I can.
