### ISSUE TITLE
Vaccination Numbers for Austria are Implausible

### ISSUE THREAD

**Issue by mitsuhiko** [owid/covid-19-data#2437]
With the update in https://github.com/owid/covid-19-data/issues/2420 / https://github.com/owid/covid-19-data/commit/e515d6c9c1101517a0a761162fdd17706ccbf78a the current numbers for single dose are 69.4% and for fully vaccinated 67.1%. First of all the first number seems significantly below what is officially reported in Austria, secondly the number of fully vaccinated is also below the number of active vaccination certificates as per official dashboard. The number of active vaccination certificates is lower than the number of fully vaccinated as some did not get their boosters and their second shot certificate expired.

So however that number is currently calculated, it seems quite significantly different from the official numbers reported in Austria and probably worth an investigation.

**Comment by mitsuhiko** [comment]
Also another data point is that the ECDC also shows higher numbers on their dashboard: https://vaccinetracker.ecdc.europa.eu/public/extensions/COVID-19/vaccine-tracker.html#uptake-tab

**Comment by lucasrodes** [comment]
Hi @mitsuhiko,
Thanks for spotting this!

I have checked and found a bug in our code. The problem was our assumptions of field `TargetGroup` from [ECDC data](https://www.ecdc.europa.eu/sites/default/files/documents/Variable_Dictionary_VaccineTracker-04-11-2021.pdf).

We had assumed that `TargetGroup='ALL'` meant all the population when it actually means "Adult population" [[reference](https://www.ecdc.europa.eu/sites/default/files/documents/Variable_Dictionary_VaccineTracker-04-11-2021.pdf)]. That is, we were missing the numbers from adolescents and children (group `TargetGroup='Age<18'`).

After the changes, values for Austria are:

|location|date      |vaccine                                                      |source_url                                                                      |total_vaccinations|people_vaccinated|people_fully_vaccinated|total_boosters|
|--------|----------|-------------------------------------------------------------|--------------------------------------------------------------------------------|------------------|-----------------|-----------------------|--------------|
|Austria |2022-01-28|Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech|https://www.ecdc.europa.eu/en/publications-data/data-covid-19-vaccination-eu-eea|17598367          |6760733          |6469154                |4716960       |
|Austria |2022-02-04|Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech|https://www.ecdc.europa.eu/en/publications-data/data-covid-19-vaccination-eu-eea|17795320          |6772359          |6500684                |4870807       |
|Austria |2022-02-11|Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech|https://www.ecdc.europa.eu/en/publications-data/data-covid-19-vaccination-eu-eea|17864404          |6778074          |6516272                |4918600       |

Thanks once again!
