### ISSUE TITLE
Adding new items to CSV files

### ISSUE THREAD

**Issue by zizwiz** [owid/covid-19-data#248]
I know you own the files and can change them as you need but can we consider always being backwards compatible. The addition of the ISO code as the second entry in the file broke my usage of the file in my app. I always add additional info to the end as a new field that way the CSV file will always parse into my app. For me I will change the way I parse the files so my app will always work even if you change items inside the structure.

**Comment by edomt** [comment]
Hi @zizwiz 

If this issue has arisen, I'm guessing you must be parsing the file by referencing the column number rather than the column names from the header. As a general rule you should always parse the header in our files (or the keys in JSON files), as the order of the columns could change at any point and for various reasons.

**Comment by zizwiz** [comment]
Thanks, On other CSV files I have used in the past in entirely different projects I have had issues where the column names have changed or worse still add a comma into the name, this is why I always add items to the end, that way I do not worry about name changes and know the absolute position of the data. I am now parsing these files by column name so all is now working again. Thanks.
