### ISSUE TITLE
data: New Zealand vaccination

### ISSUE THREAD

**Issue by 36wish** [owid/covid-19-data#2499]
### Country

New Zealand

### Domain

Vaccinations

### Which data is wrong?

I'm having trouble reconciling the vaccine data for 2022-02-15 to the NZ Ministry of Health webpage, archived [here](https://web.archive.org/web/20220216024736/https://www.health.govt.nz/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-vaccine-data).

### total_vaccinations 10435219 
On the MoH webpage it says 12+total dose is 9,997,411  and child total dose is 218,074. Add them together you get 10,215,485 which is smaller than the number in the file

### people_vaccinated 4450234
On the MoH webpage it says 12+ first dose is 4,014,360  and child first dose is 218,074. Add them together you get 4,232,434 which is smaller than the number in the file

### people_fully_vaccinated 3947848
On the MoH webpage it says 12+ second dose is 3,951,272 

### total_boosters 2037137 
On the MoH webpage it says 12+ booster dose is 2,004,808

**Comment by Rouein** [comment]
Hi @36wish ,
By using the wayback machine you might see numbers that are different from the ones reported here. This is due to the source correcting their data at a later date. To view the most up to date data, I recommend using the excel sheet available [here](https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus/covid-19-data-and-statistics/covid-19-vaccine-data) under "Details of vaccination data" section.
