### ISSUE TITLE
data: Singapore data missing for 7th and 14th Feb 2022. 

### ISSUE THREAD

**Issue by gauravjoshijo** [owid/covid-19-data#2501]
### Country

Singapore

### Domain

Vaccinations

### Which data is wrong?

For Singapore the data is missing for 7th and 14th feb 2022 in the feed while the data is available in [OW](https://data.gov.sg/dataset/covid-19-vaccination?view_id=6c5916de-8429-4aaf-89ef-76dbb3cd9a9c&resource_id=5ae0f0e8-7d61-404e-b5a9-33448cdd6d21). 

### Why do you think the data is wrong?

One possibility: Data is not properly fetched from the source.

**Comment by Rouein** [comment]
Hi @gauravjoshijo ,
This is due to an error in the source [dataset](https://storage.data.gov.sg/covid-19-vaccination/covid-19-vaccination.zip) . In the dataset, the cumulative total of the 2nd doses administered on 7th and 14th are higher than the following days. Therefore, these data points are removed until they are corrected in the source.

**Comment by lucasrodes** [comment]
Hi @gauravjoshijo,
Thanks for your message.

As @Rouein points out, we have considered these data points as outliers as they break increasing monotony. We force all time series to be monotonically increasing, as cumulative metrics should be always increasing. 

- **7 Feb 2022**: Metric `Received at least two doses` on the 8th of February is lower than 7th's, hence we discard 7th's.
- **14 Feb 2022**: Metric `Received at least two doses` on the 15th of February is lower than 14th's, hence we discard 14th's.

Note that this also happens on the 30st of January.

Hope this helps!
