### ISSUE TITLE
data: ( Vax , Ethiopia)

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2522]
### Country

Ethiopia 

### Domain

Vaccinations

### Which data is wrong?

Majority of the data points for `people_fully_vaccinated` and `vaccine` in [Ethiopia.csv](https://github.com/owid/covid-19-data/blob/bebc25f6522f677bc9fc63d6583127d3748d8ac1/public/data/vaccinations/country_data/Ethiopia.csv) are wrong.

### Why do you think the data is wrong?

According to Africacdc:
```
Vaccines Approved: 
AstraZeneca Sinopharm J&J Moderna
Vaccine(s) in use: 
AstraZeneca Sinopharm BioNTech J&J Sinovac Moderna
```
This [link](https://ethiopianmonitor.com/tag/johnson-johnson-vaccine/) could help finding when first J&J doses were administered.

I suggest using Africacdc to automate data collection for Ethiopia after vaccine timeline is determined.

**Comment by lucasrodes** [comment]
Thanks, @Rouein!

I am removing all data points for `people_fully_vaccinated`, as they assumed no single dose was in use. Based on the cited link, Ethiopia received the first batch of J&J doses on 6th September 2021. I have assumed that they started being administered by then.

Additionally, have added the vaccines:

- Sinopharm: https://www.globaltimes.cn/page/202103/1219909.shtml?id=11, adding since the beginning of our time series.
- Pfizer/BioNTech: https://reliefweb.int/report/ethiopia/united-states-donates-1552590-doses-pfizer-covid-19-vaccine-ethiopia, earliest batch received that I found dates from 2nd November 2021
- Sinovac: https://www.republicworld.com/world-news/africa/ethiopia-receives-first-batch-of-chinese-vaccine.html, adding since the beginning of our time series.

Couldn't find a reference for when Moderna started to be administered.

---
> I suggest using Africacdc to automate data collection for Ethiopia after vaccine timeline is determined.

We currently are not using Africa CDC because we don't fully understand their metrics. In particular, metrics `TotAmtAdmi`,  `FullyVacc`, `VacAd1Dose` don't seem accurate as `TotAmtAdmi = FullyVacc + VacAd1Dose`.

**Experiment:**

```python
from cowidev.vax.incremental.africacdc import AfricaCDC
df = AfricaCDC().read()
df.loc[df.CtryTest=='ethiopia', ['TotAmtAdmi', 'FullyVacc', 'VacAd1Dose', 'Booster']]
    TotAmtAdmi  FullyVacc  VacAd1Dose  Booster
12    15311442    4181972    11129470        0
```

**Comment by Rouein** [comment]
then WHO?

**Comment by lucasrodes** [comment]
We will keep the Ethiopia data manual for now, as it is updated more frequently.

Booster data from AfricaCDC is reporting 0 currently. Fully vaccinated metric is not obtainable from WHO either because single-dose vaccines are in use.


Thanks for opening this issue!
