### ISSUE TITLE
data: Indonesia total booster data

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2574]
### Country

Indonesia

### Domain

Vaccinations

### Source

https://data.covid19.go.id/public/index.html

### Comments

Hi there, may I ask recently the Indonesia total booster data has abnormal timepoint deletion?

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Thanks for your report.

I just added historical data for Indosia, data should be live on our website in the next 24 hours.

**Comment by Leonaides96** [comment]
Hi @lucasrodes ,
may I know what issues on it and the data source from ?

**Comment by lucasrodes** [comment]
We use the API behind https://data.covid19.go.id/public/index.html, which is available at https://data.covid19.go.id/public/api/pemeriksaan-vaksinasi.json. This data is great because it provides historical data, allowing for backward data corrections. However, this source only includes data on first and second doses, and hence we can only estimate the number of people who have received at least one dose and the number of fully vaccinated people.

To obtain the total number of doses and booster doses, we use another source: 
- https://public.tableau.com/views/DashboardVaksinKemkes/TotalVaksinasiDosis1 for first doses
- https://public.tableau.com/views/DashboardVaksinKemkes/TotalVaksinasiDosis2 for second doses
- https://public.tableau.com/views/DashboardVaksinKemkes/TotalVaksinasiDosis3 for third doses

These power the dashboard at https://vaksin.kemkes.go.id/#/vaccines

**Comment by Leonaides96** [comment]
Understand, therefore the for the third doses is come from this source ( https://public.tableau.com/views/DashboardVaksinKemkes/TotalVaksinasiDosis3 )  correct ?

**Comment by lucasrodes** [comment]
> Understand, therefore the for the third doses is come from this source ( https://public.tableau.com/views/DashboardVaksinKemkes/TotalVaksinasiDosis3 ) correct ?

Yes

**Comment by Leonaides96** [comment]
Hi @lucasrodes,

In the country_data, I saw the update in indonesia.csv. but in the vaccination.csv file it seen not yet updated, may I know around when will be updated?

**Comment by lucasrodes** [comment]
Hi @Leonaides96!
Updates in the final files occur by 12 noon (London time).

**Comment by Leonaides96** [comment]
> Hi @Leonaides96!
> Updates in the final files occur everyday by 12 noon (London time).

Hi @lucasrodes ,

Noted with thanks
