### ISSUE TITLE
data: Colombia vaccination stats 

### ISSUE THREAD

**Issue by mkhanka** [owid/covid-19-data#2575]
### Country

Colombia

### Domain

Vaccinations

### Which data is inaccurate or missing?

Booster shot data are only available after 17th December 2021. Could you please check the reason behind unavailability of data for booster shot upto 17th December 2021.
Also, the data for “people_vaccinated” from 31st Oct. 2021 to 17th December 2021 is missing. Kindly look into the issue

### Why do you think the data is inaccurate or missing?

Data source: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Colombia.csv 

Booster shots on 18th Dec: 2677561 , such number of shots administrated on a single day is not possible and looks like prior days shots info has been added on a single day. Same can be seen in the people_vaccinated count, where there is a sudden jump in count on 18th Dec.

**Comment by lucasrodes** [comment]
Hi @mkhanka,
Thanks for your message.

We started collecting booster data for Colombia on the 17th of December 2022, when it became available on our source. Also, we were not able to obtain the data for "people_vaccinated" during the mentioned period because there was missing information in the source (i.e. number of single-doses).

We are happy to backfill these dates provided that the data is available in some official reports. So far we have not found one but you might be aware of the existence of such documents. If so, we would really appreciate it if you could share these with us!

Thanks once again for your help!
