### ISSUE TITLE
data: Error in calculations of some indicators

### ISSUE THREAD

**Issue by 3dgiordano** [owid/covid-19-data#2590]
### Country

Germany

### Domain

Cases

### Which data is inaccurate or missing?

I discovered that for Germany, the daily average data for the last 7 days for both cases and death were not being displayed.
Analyzing the file https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv I noticed that the problem occurs on 2022-04-01 when the data from new cases or new deaths is set to null, breaking the daily average calculation (new_cases_smoothed, new_deaths_smoothed)

The data from CSSE for that day display a decrement in total cases and deaths.
Probably the error in calc is generated by the unexpected negative value in the daily difference.

### Why do you think the data is inaccurate or missing?

CSSE use a total counter and OWID create the daily based on the difference between dates, CSSE made fixes to the total data reported, generating negative values to compensate the extra positive of previous dates when human error occurs in the reported data.
If the negative value not is considered, probably the smoothed average not is accurate, probably upwards the values by not taking into account negative values.
The fact that the negatives end up generating a null can generate other inconsistencies in the data.
I'm reporting it for review.
I understand before the data of new cases and deaths reflected the negative ones and these problems did not occur.
It is a conjecture that possibly with some change something stopped working as it should.

**Comment by edomt** [comment]
Hi @3dgiordano - thanks for reporting!

This is done on purpose in our code. When JHU reports a negative value for either cases or deaths, we stop reporting the 7-day rolling average for the next 7 days, because including the negative value in the rolling average would lead to an artificially low value (sometimes close to 0, or even negative) due to the data correction. This happened in the past and led to some very wrong interpretations of our charts.

For Germany, given that the negative value is on April 1st, the 7-day average from April 1st to April 7th is set to `NA`. It will be calculated again on April 8th (on the basis of daily values from April 2nd-8th).
