### ISSUE TITLE
Vaccinations UK Update

### ISSUE THREAD

**Issue by Nishan-Pradhan** [owid/covid-19-data#260]
UK Vaccination figures of 1.3 million doses administered were announced yesterday. When will this be displayed in the dataset?

Thanks

**Comment by edomt** [comment]
Hi @Nishan-Pradhan 

Regarding the figure of 1.3 million doses announced earlier today for the UK: we're taking our data from the official dashboard (https://coronavirus.data.gov.uk/details/healthcare) rather than separate announcements. The new data will therefore appear on our charts tomorrow afternoon.

The reason for this is that the public announcements aren't necessarily synchronized with the underlying data. For example, we initially took into account Matt Hancock's figure of 1M doses last week, but the NHS later told us that this number had actually been reached earlier.

Adding correct numbers but with the wrong dates would lead to under/overestimating the number of daily vaccinations on our charts, so we'll be sticking to the official dashboard data for simplicity and accuracy!

**Comment by Nishan-Pradhan** [comment]
That makes sense, thanks for clarifying!
