### ISSUE TITLE
Czechia tests looks extremely strange

### ISSUE THREAD

**Issue by imoskvin** [owid/covid-19-data#264]
Since today's commit 02d14ae60e9be5531361620e5e384a4e237b15eb Czechia's tests data has lots negative deltas. Cumulative tests looks like tests deltas.

<img width="409" alt="2021-01-06_19-39-09" src="https://user-images.githubusercontent.com/1217983/103795317-e1c31480-5056-11eb-9be1-6bebc75e9abb.png">

Please check correctness if possible. Thank you

**Comment by edomt** [comment]
Hi @imoskvin! Many thanks for notifying us. The column was mislabeled and was indeed the daily change in cumulative total. This will be fixed in the next few minutes. 

We're now using new data published by the Ministry that contains complete daily overviews of PCR _and_ antigen tests. This data does not allow us to publish any cumulative total, since no information is available on how many people had been tested prior to the first day of reporting. However, the website says that "this format will be replaced by the open dataset that is currently being prepared."

**Comment by imoskvin** [comment]
Labels fixed, but you still publish cumulative total as cumulative sum of deltas.
If this is expected, then OK, but as I understand you, it's been expected to remove all cumulative tests, as it's done for France, for example.

**Comment by edomt** [comment]
Sorry about that, there was still a typo in my code… Thank you for paying attention!
