### ISSUE TITLE
Missing data: Anguilla, Nicaragua, Poland

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2642]
### Country

Anguilla, Nicaragua, Poland

### Domain

Testing

### Which data is inaccurate or missing?

Daily change in cumulative total for the above 3 country

### Why do you think the data is inaccurate or missing?

Hi, may I question the Daily change in cumulative total for the above 3 country are deleted? or any revise on those 3 country?

**Comment by camappel** [comment]
Hi @Leonaides96 ,

The source for [Anguilla](https://beatcovid19.ai/) has not updated since Nov 8, 2021.

Our script for Nicaragua stopped working on April 6, 2022. The data will be updated using the data provided in issue #2580.

The data for Poland is current as per the [ECDC](https://www.ecdc.europa.eu/en/publications-data/covid-19-testing).

Thanks!

**Comment by Leonaides96** [comment]
@camappel ,

Sorry, and I meant the historical data of the Daily change in cumulative total for the both countries are comfirm removed?
