### ISSUE TITLE
data: Data revision

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2676]
### Country

argentina

### Domain

Vaccinations

### Which data is inaccurate or missing?

total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters

### Why do you think the data is inaccurate or missing?

Hi team,

I have found the data have a revision on 06 June 2022, may I know what are the reason for the full revision in this country?

Thanks and regards
Leonaides

**Comment by lucasrodes** [comment]
Hi @Leonaides96,
Thanks for reporting. 

This is due to a data revision in the source. It seems to be a minor revision, although it does affect almost all of the rows for Argentina. However, the changes in the metrics' values are small. Value for `total_vaccinations` is 0.059% larger, `people_vaccinated` is 0.004%, `people_fully_vaccinated` is 0.011% and `total_boosters` is 0.22%.

**Comment by Leonaides96** [comment]
Hi @lucasrodes ,

Thanks for the information. 

Does the local sources have any reason on this minor revisions?

Thanks and regards
Leonaides
