### ISSUE TITLE
Number of new cases negative for France during first wave

### ISSUE THREAD

**Issue by Arcturus122** [owid/covid-19-data#270]
Hi,
there is a Number of **new cases** negative for France during the first wave. it was not the case weeks ago. Why are the historical data are changing ?
Many thanks,

**Comment by edomt** [comment]
Bonjour @Arcturus122 

See #197 on the transition from ECDC to JHU for our data on cases & deaths (that's the reason for the change in historical data).

As for the negative cases, the issue is mentioned in our [main README](https://github.com/owid/covid-19-data/tree/master/public/data): 

> Confirmed cases and deaths: our data comes from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University (JHU). Note: the number of cases or deaths reported by any institution—including JHU, the WHO, the ECDC and others—on a given day does not necessarily represent the actual number on that date. This is because of the long reporting chain that exists between a new case/death and its inclusion in statistics. This also means that negative values in cases and deaths can sometimes appear when a country corrects historical data, because it had previously overestimated the number of cases/deaths. Alternatively, large changes can sometimes (although rarely) be made to a country's entire time series if JHU decides (and has access to the necessary data) to correct values retrospectively.

Since we import the JHU data without making changes to it, you can open an issue directly on their side if needed: https://github.com/CSSEGISandData/COVID-19/issues
