### ISSUE TITLE
data: Vac Sudan

### ISSUE THREAD

**Issue by Leonaides96** [owid/covid-19-data#2701]
### Country

Sudan

### Domain

Vaccinations

### Which data is inaccurate or missing?

The timepoint from 2022/06/06 until 2022/06/28 have been removed

### Why do you think the data is inaccurate or missing?

Hi Team,

I have noticed that the latest commit has removed the timepoint from 2022/06/06 till 2022/06/28  in Country Sudan. 

May I have your helps in checking is there any reason for this deletion? 

Thanks 
Best regards,
Leonaides

**Comment by lucasrodes** [comment]
Thanks for reporting, @Leonaides96!

This has been fixed in https://github.com/owid/covid-19-data/commit/cfc7015db8c40c91c541fba36f73801fb400b7b4. Will be live in the next 24h.

For future reports, it is extremely helpful if you mention the commit hash, e.g https://github.com/owid/covid-19-data/commit/9be3c284b76a364def42b314343cd25403f821a2#diff-e8155a2ca7947965c1f739d47e1d7479ea9dfe9dd1cffac8f4dada3fb30fc43a.


Once again, thanks for your help!

**Comment by Leonaides96** [comment]
Hi @lucasrodes ,

Thanks for your prompt response, and will take note next time.

Once again thank you.

Best regards
Leonaides
