### ISSUE TITLE
data: Age-specific vaccinations are unavailable for Germany, despite being mentioned in the list of locations 

### ISSUE THREAD

**Issue by singlaayush** [owid/covid-19-data#2710]
### Country

Germany

### Domain

Vaccinations

### Which data is inaccurate or missing?

Although Germany is included in the list of countries for which vaccination data is available by age in [locations-age.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/locations-age.csv), there is no data available for Germany in the [vaccinations-by-age-group.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/vaccinations-by-age-group.csv) file.

### Why do you think the data is inaccurate or missing?

Answered above

**Comment by lucasrodes** [comment]
Thanks for reporting, @singlaayush.

That was a bug on our end. I have removed Germany from [locations-age.csv](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/locations-age.csv). The reason why we do not report vaccination data for Germany is broken down by age is because the ECDC (our source for most European countries) does not provide granular enough age groups.
