### ISSUE TITLE
data: OWID daily data

### ISSUE THREAD

**Issue by dkasprzak99** [owid/covid-19-data#2712]
### Country

ALL

### Domain

Cases

### Which data is inaccurate or missing?

The global data has not been updated since Aug 14, when it is usually updated daily (so we should be seeing Aug 16 today).

### Why do you think the data is inaccurate or missing?

Missing two days of data currently
![Owid snip-image](https://user-images.githubusercontent.com/111444088/185165493-d67074d2-bc31-46d5-964b-2aa42c20f11c.png)

**Comment by lucasrodes** [comment]
Hi @dkasprzak99, thanks for reporting this bug.

We have fixed this now, and the updated data should be also live on our website. This occurred because a new country was added to one of our source datasets, which prevented our processes from running successfully. In particular,  it was "Micronesia" which was added to the [reproduction rate estimate dataset](https://github.com/crondonm/TrackingR/raw/main/Estimates-Database/database_7.csv).

Sorry for the inconvenience.


Side note, we encourage the use of this link to download the data: https://covid.ourworldindata.org/data/owid-covid-data.csv, instead of the GitHub link. More details about this can be found [here](https://github.com/owid/covid-19-data/tree/master/public/data#stable-urls)

**Comment by dkasprzak99** [comment]
I appreciate you looking into this matter and getting back to me.

Thank you,

Derek Kasprzak
GLOBAL Safety, Health and Environment
SH&E mANAGER management Systems

ECOLAB 1601 W. DIEHL RD, NAPERVILLE, IL 60563-1198
M 630 605 7932   T 630 305 1523    F 630 305 2986
