### ISSUE TITLE
data: Data mismatches from WHO vaccinations

### ISSUE THREAD

**Issue by karaschechtman** [owid/covid-19-data#2718]
### Country

Sierra Leone, Togo, Lesotho

### Domain

Vaccinations

### Which data is inaccurate or missing?

Sierra Leone, Togo and Lesotho seem to have their data pulled from the WHO, but their total vaccinations mismatch the current WHO totals.

### Why do you think the data is inaccurate or missing?

SLE: 3526495 total in OWID vs. 3493386 in WHO
TGO: 3290821 total in OWID vs. 3262548 in WHO
LSO: 1077116 in OWID vs. 1102069 in WHO

**Comment by lucasrodes** [comment]
Hi @karaschechtman,
Thanks for bringing this to our attention!

I just checked and fixed our values for Sierra Leone and Togo so that they are aligned with WHO (these will be live in the next 24h). Lately, WHO has been reporting some metric values that were not consistent (e.g. cumulative metrics that decreased from week _n_ to week _n+1_), which has led to these small discrepancies.

Regarding Lesotho, the latest data from Lesotho has not been imported bc of an irregularity in WHO data: The number of total doses administered was substantially lower than the number of people vaccinated with at least one dose. 1102069 vs 1631364, respectively. I've just reported this to them.


Thanks once again!
