### ISSUE TITLE
data: people_with_booster_shot should not be larger than people_fully_vaccinated

### ISSUE THREAD

**Issue by mkhanka** [owid/covid-19-data#2722]
### Country

Japan

### Domain

Vaccinations

### Which data is inaccurate or missing?

For Japan,  as per OWID, total_boosters are reporting more than the count for people_fully_vaccinated from 19th August 2022 to 6th September 2022 .

<img width="737" alt="Screen Shot 2022-09-12 at 1 42 42 PM" src="https://user-images.githubusercontent.com/87356889/189606085-d74feb75-2ee8-47c3-85bd-2a660fde6dec.png">

### Why do you think the data is inaccurate or missing?

total_boosters cannot be more than the count of people_fully_vaccinated, This is only true if multiple booster doses are prescribed.

**Comment by lucasrodes** [comment]
Hi @mkhanka,
`people_fully_vaccinated` counts **people** and `total_boosters` counts **doses**. Since people can get more than one booster, the latter metric is likely to be greater than the former.

Note that in Japan, fourth doses have been administered. See [this note](https://www.kantei.go.jp/jp/headline/kansensho/vaccine_note.html#note-3) for more details.
