### ISSUE TITLE
Vaccination data for Greece

### ISSUE THREAD

**Issue by sivenni** [owid/covid-19-data#274]
New site for daily vaccinations in Greece: https://emvolio.gov.gr/vaccinationtracker

**Comment by lucasrodes** [comment]
Currently using this [API](https://data.gov.gr/api/v1/query/mdg_emvolio), as coded in [greece.py](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/automations/batch/greece.py).

@edomt I presume the current approach might be more stable (format might not suffer hard changes) but requires a token, so that sharing might be a bit more tedious. Shall we stick to the current approach? I can work on an incremental script if deemed better

**Comment by edomt** [comment]
The API gives the full time series, and given what we saw with testing data it's a lot better to get that in case a country makes retroactive corrections (which happens a lot). So yes, let's stick to the API way for now 👍
