### ISSUE TITLE
data: UK deaths all zero since December 5, 2022

### ISSUE THREAD

**Issue by Mike-Honey** [owid/covid-19-data#2773]
### Country

United Kingdom

### Domain

Deaths

### Which data is inaccurate or missing?

The value of new deaths has been zero since December 5. All derived values (e.g. 7-day average) are also affected.
https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=desc&pickerMetric=new_cases_per_million&Metric=Confirmed+deaths&Interval=New+per+day&Relative+to+Population=true&Color+by+test+positivity=false&country=~GBR

### Why do you think the data is inaccurate or missing?

UK government dashboard indicates death reporting is continuing, at least for the member countries (e.g. England):
https://coronavirus.data.gov.uk/details/deaths?areaType=nation&areaName=England

**Comment by lucasrodes** [comment]
Hi @Mike-Honey,
Thanks for your message.

Note that you are comparing the UK with England. For the same dashboard for the UK, there has been no data since May 2022: https://coronavirus.data.gov.uk/details/deaths?areaType=overview&areaName=United%20Kingdom.

We report the data for the UK and all countries based on https://github.com/CSSEGISandData/COVID-19. Based on the issue https://github.com/CSSEGISandData/COVID-19/issues/6440, it looks like there has been a break in data reporting due to the winter holidays.
