### ISSUE TITLE
total_vaccinations count is incorrect for multiple locations

### ISSUE THREAD

**Issue by tushartify** [owid/covid-19-data#2778]
Hello,

As per your definition of [total_vaccinations](https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations) count, it is the sum of number of doses administered (first, second, third/booster). However, I have observed that it is not the case for some of the locations, example: [Tanzania](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Tanzania.csv) and [Burkina Faso](https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Burkina%20Faso.csv)

Here, the count in 'total_vaccinations' column is not matching the sum of  'people_vaccinated', 'people_fully_vaccinated',	'total_boosters' columns

Could you please explain the reason behind this and rectify it in case this is unexpected.

**Comment by lucasrodes** [comment]
Hi @tushartify,
Thanks for your message.

`total_vaccinations` might be not equal to the sum of `people_vaccinated`, `people_fully_vaccinated` and `total_boosters`. This is because of single-shot vaccines (e.g. Johnson&Johnson), which are counted both in `people_vaccinated` and `people_fully_vaccinated`. In such cases, `people_vaccinated + people_fully_vaccinated + total_boosters` would be an overestimate, as it would double-count single-shot vaccines.

Back to your specific example, both Tanzania and Burkina Faso use the Johnson&Johnson vaccine.
