### ISSUE TITLE
FRA Data vaccination

### ISSUE THREAD

**Issue by Dan-Simple** [owid/covid-19-data#281]
France data may contain an error.
On line for 2021-01-07 the total should be 37500 instead of 45000 (or daily_vaccinations is false)...

**Comment by edomt** [comment]
Hi @Dan-Simple 

Olivier Véran announced (although in a very confusing and scattered way) the following figures:

* 5,000 vaccinations on January 5 ([source](https://twitter.com/olivierveran/status/1346529841701662722))
* 12,500 on January 6 ([source](https://twitter.com/nicolasberrod/status/1347270933841633281))
* 45,000 on January 7 ([source](https://twitter.com/Le_Figaro/status/1347239178484985858))
* 80,000 on January 8 ([source](https://twitter.com/olivierveran/status/1347616253490450433))

The "daily_vaccinations" variable is calculated as a 7-day rolling average, which is why the value for January 7 is not simply the difference between one day and the previous one.
