### ISSUE TITLE
data: Appears like your deaths data is now weekly?

### ISSUE THREAD

**Issue by sondreus** [owid/covid-19-data#2828]
### Country

All countries

### Domain

Deaths

### Which data is inaccurate or missing?

https://ourworldindata.org/explorers/coronavirus-data-explorer?facet=none&Metric=Confirmed+deaths&Interval=New+per+day&Relative+to+Population=false&Color+by+test+positivity=false&country=~OWID_EUR

https://ourworldindata.org/explorers/coronavirus-data-explorer?facet=none&Metric=Confirmed+deaths&Interval=Weekly&Relative+to+Population=false&Color+by+test+positivity=false&country=OWID_EUR~USA

Hi team -- looks like your daily deaths data is now weekly totals (at least for most countries / regions). This results in e.g. "new per day" figures being 7x what they should be (weekly are also 7x what they should be). Also, recent data from the US is somehow missing. 
https://ourworldindata.org/explorers/coronavirus-data-explorer?facet=none&Metric=Confirmed+deaths&Interval=Weekly&Relative+to+Population=false&Color+by+test+positivity=false&country=OWID_EUR~USA

### Why do you think the data is inaccurate or missing?

https://ourworldindata.org/explorers/coronavirus-data-explorer?facet=none&Metric=Confirmed+deaths&Interval=New+per+day&Relative+to+Population=false&Color+by+test+positivity=false&country=~OWID_EUR

Values are 7x what they should be

**Comment by lucasrodes** [comment]
Hi @sondreus,
Thanks for reporting this. There was a bug in our processing pipeline due to a minor change in the file structure from the source. I've worked out a fix; let me know if it looks good now.

Daily numbers have been weekly since early 2023 when we switched to the WHO as our [main source](https://ourworldindata.org/covid-data-switch-jhu). So it is better to look at the [smoothed values instead](https://ourworldindata.org/explorers/coronavirus-data-explorer?time=2023-08-03..latest&facet=none&Metric=Confirmed+deaths&Interval=Weekly&Relative+to+Population=false&Color+by+test+positivity=false&country=~OWID_EUR).
