### ISSUE TITLE
data: Missing covid data for many countries in EU

### ISSUE THREAD

**Issue by gognjanovski** [owid/covid-19-data#2831]
### Country

United Kingdom and many other countries in EU

### Domain

Cases

### Which data is inaccurate or missing?

Why many countries are missing from the https://github.com/owid/covid-19-data/blob/master/public/data/latest/owid-covid-latest.csv ? 

### Why do you think the data is inaccurate or missing?

Why many countries are missing from the https://github.com/owid/covid-19-data/blob/master/public/data/latest/owid-covid-latest.csv ?

**Comment by lucasrodes** [comment]
Hi @gognjanovski,
This file only contains data from the last two weeks. Therefore, countries that haven't reported data in the previous two weeks are not shown there. This restriction has never significantly affected the file, but now that the WHO reports data less frequently, it does.

I've increased the tolerance so that data in the last 4 weeks is shown instead.

I'd recommend using the complete time series instead: https://covid.ourworldindata.org/data/owid-covid-data.csv
