### ISSUE TITLE
Vaccination date of observation inconsistencies?

### ISSUE THREAD

**Issue by adamredfern92** [owid/covid-19-data#298]
Does the "date of observation" include vaccinations from that day, or just up until that day?

UK data for the 11th for example says "Data are presented for vaccinations carried out up to and including the end of the report date."

But some of the rows in vaccinations.csv have the current date (e.g. Italy has a row for the 12th) - do we assume that is incomplete data for that day?

**Comment by edomt** [comment]
@adamredfern92 Unfortunately that's very unclear in many cases. When countries report the data in a clean way (files, API, etc.) they typically set the date to the date of vaccination, because that's what makes the most sense.

But for many countries we're still collecting the data from news articles and press reports. In those cases we find ourselves for example with a news report published at 3PM saying that X people have been vaccinated so far—and it's impossible to know if that includes the morning of that day or not.

I suspect that those differences will disappear as more and more countries report data from proper files, and we'll converge towards dates that are vaccination dates.

**Comment by adamredfern92** [comment]
@edomt ok thanks - I will assume that the dates are up for vaccinations up to and including that day for now.

I ask because I'm trying to calculate a "live" estimation of vaccinations at the current point in time (https://covidvax.live/location/gbr) and the number for UK is too high as I was assuming the date was not including the current days data.

Many thanks for everything you have been doing, it's made this project a million times easier!

**Comment by adamredfern92** [comment]
@edomt I am seeing some countries that might make more sense if the data was shifted back a day, e.g. Hungary, Poland, Oman, Bulgaria.

They are being reported in the morning with full days worth of vaccinations, so it's unlikely they include any numbers from that day.

**Comment by edomt** [comment]
Very true @adamredfern92, thanks for the suggestion! This will be fixed at the next update.
