### ISSUE TITLE
VACCINATION: world data does not update during the day updates since yesterday

### ISSUE THREAD

**Issue by nrazon** [owid/covid-19-data#304]
I see that I think since from yesterday, WORLD total info is not updating during the day
but country vaccination dates are updating during the day multiple times.

Are you calculating world data 1 time at the end of the day now?
For example World data last updated date is yesterday on vaccination.csv but other countries have todays data.

**Comment by edomt** [comment]
Hi @nrazon
Yes, since yesterday we've introduced this change: the world total is calculated up to the previous day. This is to avoid showing a world total for the current day that would look very low in the morning when few countries have reported, and thus give the impression that the pace of vaccination is slowing.
