### ISSUE TITLE
Hong Kong covid data

### ISSUE THREAD

**Issue by dkobak** [owid/covid-19-data#309]
Why is Hong Kong data empty in owid-covid-data.csv? 

It's present in the CSV but with no information (all entries are empty). At the same time I do see the Hong Kong deaths in the John Hopkins dataset: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv

**Comment by edomt** [comment]
Hi @dkobak 

This is because in the JHU dataset, HK is listed as a subregion of China, and we currently don't import any subnational data from JHU. Meanwhile, in our testing data, we collect information that's specific to HK from the [Centre for Health Protection, Department of Health](https://data.gov.hk/en-data/dataset/hk-dh-chpsebcddr-novel-infectious-agent). So in owid-covid-data.csv all cases & deaths columns will be empty but you'll see data in the variables related to testing.

We're pretty busy with the vaccination dataset right now, so there's little chance we'll add subnational data from JHU in the near future. If you really need cases & deaths data for HK then your best bet will be to import it and add it to our dataset locally.

**Comment by dkobak** [comment]
All right, thanks for the explanation!
