### ISSUE TITLE
Add hospital & ICU data for Israel

### ISSUE THREAD

**Issue by edomt** [owid/covid-19-data#352]
Given the speed of the vaccination campaign in Israel, we're considering adding hospital & ICU data for the country on our [dedicated page](https://ourworldindata.org/covid-hospitalizations) so people can monitor how the situation evolves.

In the official [API](https://datadashboardapi.health.gov.il/api/queries/patientsPerDate) there are many variables, and we're not exactly sure which ones to use. This is what the data looks like for yesterday for example:

```
"date": "2021-01-21T00:00:00.000Z",
"new_hospitalized": 221,
"Counthospitalized": 2092,
"Counthospitalized_without_release": 1835,
"CountHardStatus": 1183,
"CountMediumStatus": 325,
"CountEasyStatus": 479,
"CountBreath": 318,
"CountDeath": 38,
"total_beds": 2020,
"StandardOccupancy": 1.035643564356436,
"num_visits": 5978,
"patients_home": 79060,
"patients_hotel": 1641,
"CountBreathCum": 2655,
"CountDeathCum": 4256,
"CountCriticalStatus": 400,
"CountSeriousCriticalCum": 14462,
"serious_critical_new": 160
```

The 4 variables we're looking for are:

* Daily hospital occupancy (number of COVID-19 patients in hospital on a given day): I think that's `Counthospitalized`. I'm not sure at all what `Counthospitalized_without_release` means and why it's lower?
* Daily new hospital admissions of COVID-19 patients: I think that's `new_hospitalized`
* Daily ICU occupancy (number of COVID-19 patients in intensive care on a given day): I don't think that's available exactly in this form, but we could use `CountBreath` if that's the total number of people currently on respirators.
* Daily new ICU admissions of COVID-19 patients: not available?

The language barrier makes it difficult for me to compare this to the [official dashboard](https://datadashboard.health.gov.il/COVID-19/general) or press reports, and Google Translate is far from perfect for Hebrew. I'd appreciate it if people could confirm that those are indeed the right variables we should use.

(cc @EladHeller and @Aric5301 who have helped us in the past!)

**Comment by Aric5301** [comment]
Hey!
Elad probably knows more than I know because he's experienced with this [alternative dashboard](https://covid.eran.dev) for data of Israel (Judging by his GitHub profile). 

I'll try to help:
- Based on the translated data from the alternative dashboard I linked, `Counthospitalized` is the number of COVID-19 patient in a hospital in a given day. I too am not sure what `Counthospitalized_without_release` means.
- `new_hospitalized` seems right. This figure doesn't show up in any of the dashboards so I can't make sure (Nothing to translate it from).
- I think you should use `CountCriticalStatus` instead of `CountBreath`. This is the figure that is displayed on the official dashboard (Translated "Critical"), so I think that this is more precise to determine how many patients are in ICU.
- Perhaps use `serious_critical_new`? This is again a figure that doesn't show up on the official dashboard so I have nothing to compare it to but it seems right.

I can email the MOH and ask them about the exact meaning of every variable. Last time I contacted them they replied within a few days.

BTW, I will happily help you translate data from Hebrew to English anytime, just contact me :)

**Comment by edomt** [comment]
Thank you @Aric5301! That's super useful.

**Comment by edomt** [comment]
This has been added to our hospital & ICU entry now: https://ourworldindata.org/covid-hospitalizations
