### ISSUE TITLE
VACCINATIONS: total_vaccinations column data in vaccinations.csv

### ISSUE THREAD

**Issue by GianluigiVitale** [owid/covid-19-data#362]
I am using the file vaccinations.csv to build cumulative charts about total_vaccinations.

I noted that in some rows of this file, the total_vaccinations sometimes is not present even if the daily_vaccinations column is not null.
Since based on daily_vaccinations, total_vaccinations can be calculated, I would like to ask you if you could fill in this way the missing information in the corresponding cells.

Also, I think that even if the daily_vaccinations is not present, total_vaccinations shouldn't be null but the same as the previous day.

**Comment by jmarcio** [comment]
I've noticed the same. At least for Russia and China.

The problem is with, at least, new_vaccinations and total_vaccinations and probably related fields.

As an example, attached are the contents for these two countries, but only columns :
 iso_code,date,new_vaccinations,total_vaccinations

[china.txt](https://github.com/owid/covid-19-data/files/5867533/china.txt)
[russia.txt](https://github.com/owid/covid-19-data/files/5867534/russia.txt)

**Comment by jmarcio** [comment]
OK. Just an update.

It seems to me that the reason is that OWID doesn't have intermediate data. So, it seems to me that to publish raw data may be the correct thing to do.

Up to each one to interpolate missing values, the way he want.

These data appear interpolated in columns such as "new_vaccinations_smoothed" and used in OWID graphics.

But... interpolate and smooth aren't the same thing.

So, a possible solution is of the kind :
* if new_vaccinations is missing
  * if total_vaccinations is present,
    * set new_vaccinations = total_vaccinations - previous_total_vaccinations
  * else
    * set new_vaccinations = new_vaccinations_smoothed
    * set total_vaccinations = total_vaccinations_previous+  new_vaccinations_smoothed
* it total_vaccinations is still missing:
  set total_vaccinations = total_vaccinations_previous + new_vaccinations

**Comment by edomt** [comment]
Hi @GianluigiVitale @jmarcio 

You can find a longer description of our variables here: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/

- The `total_vaccinations` column only includes the totals that are truly reported by each country. We do not interpolate anything here; this is the raw data.
- `daily_vaccinations_raw`: daily change in the total number of doses administered. It is only calculated for consecutive days. This is a raw measure provided for data checks and transparency, but we strongly recommend that any analysis on daily vaccination rates be conducted using `daily_vaccinations` instead.
- `daily_vaccinations`: new doses administered per day (7-day smoothed). For countries that don't report data on a daily basis, we assume that doses changed equally on a daily basis over any periods in which no data was reported. This produces a complete series of daily figures, which is then averaged over a rolling 7-day window.

And to clarify even further, the names by @jmarcio refer to the complete dataset (`owid-covid-data.csv`) where the variable named `daily_vaccinations` in the vaccination dataset is renamed to `new_vaccinations_smoothed` to match the naming convention we've used for other COVID-19 metrics.

**Comment by jmarcio** [comment]
Hi @edomt,

Thanks a lot for all that information. It confirms what I've already thinking.
Congrats for your good work on this.
From my side, I just play with these data. Playing with statistics - personal curiosity.
Best regards
