### ISSUE TITLE
Updated Dutch (NLD) data sources

### ISSUE THREAD

**Issue by EwoutH** [owid/covid-19-data#374]
We have some new sources for data:

- The [Coronavirus dashboard](https://coronadashboard.government.nl/landelijk/vaccinaties) now lists the total _Number of doses administered_, updated daily at 15:30 (14:30 UTC). It's split in:
  - Number of doses administered by municipal health services (GGDs)
  - Number of doses administered by hospitals
  - Number of doses administered by long-term care institutions
- A weekly overview will be published by the [RIVM](https://www.rivm.nl/node/168041) (each Tuesday afternoon)
- The number of daily and total vaccins administered by the GGDs is also published by the [GGD GHOR](https://ggdghor.nl/actueel-bericht/update-vaccinatie-coronavirus-door-ggden/).

In the future, vaccination data will be published on [data.rivm.nl/covid-19](https://data.rivm.nl/covid-19/) in a machine readable format (updated daily at 15:15 (14:15 UTC)).

**Comment by EwoutH** [comment]
Also maybe useful: Marino van Zelst has written a [webscraper](https://github.com/mzelst/covid-19/blob/master/workflow/parse_vaccines.R) to get the vaccin data from the Coronadashboard.

With this webscraper, he maintains this CSV file: [vaccines_by_day.csv](https://github.com/mzelst/covid-19/blob/master/data/vaccines_by_day.csv)

**Comment by edomt** [comment]
Thank you @EwoutH — when you say:

> In the future, vaccination data will be published on data.rivm.nl/covid-19 in a machine readable format (updated daily at 15:15 (14:15 UTC)).

Any idea of when that future will be? :)

**Comment by EwoutH** [comment]
Unfortunately not, the RIVM is probably still working on it internally.

**Comment by edomt** [comment]
Okay, thanks! Let us know whenever they start publishing it :)
For now we'll be collecting from @mzelst's file :)

**Comment by edomt** [comment]
Actually I just noticed that @Sikerdebaard had kindly provided a scraper here: https://github.com/owid/covid-19-data/issues/230#issuecomment-767597305
So we'll be using this!

**Comment by mzelst** [comment]
Hi folks, 

Little update from my side: dashboard got updated today and the vaccine data is now properly stored in the source data of the official dashboard. I've updated the vaccine scripts to do three things:
- Get the vaccines used straight from the source data
- Get the vaccines that are expected to be delivered straight from the source data
- The vaccines used per organization (hospitals / public health org's / elderly homes) are still scraped from the website (as they are not (yet?) in the source data.

This has implications for OWID as well, because they've changed the structure of the vaccine data in the source data. The data is now being displayed per type of vaccine (e.g., Pfizer or Moderna). More detail, but requires you to sum over the types of vaccines before you get to the total. Please find the updated workflow for vaccines here: https://github.com/mzelst/covid-19/blob/master/workflow/parse_vaccines.R

@edomt @EwoutH
