### ISSUE TITLE
ISO3 in testing data

### ISSUE THREAD

**Issue by gfwakefieldg** [owid/covid-19-data#39]
Hi, thanks so much for your work, it's an excellent comprehensive resource.

The testing data (csv) only lists countries by name - is it possible for you to add ISO3 codes to this file? It would make joining with other data much simpler for users!

Thanks :-)

**Comment by edomt** [comment]
Hi @gfwakefieldg 

Thanks for the kind words :-)
Great suggestion, I'll work on adding the ISO codes to that file today.

Out of curiosity, is there a specific reason you're using the testing file instead of [the complete dataset]https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv)? 

Ed

**Comment by gfwakefieldg** [comment]
Only my ignorance in not seeing the testing data in the main dataset!  For my purposes I just need the numbers of total tests but I imagine there may be times that the sources are wanted :-)

Thanks again and keep up the great work! :-D

**Comment by edomt** [comment]
Great, I think the complete dataset will be perfect for you then :-)
Just in case, I've added the ISO codes to the testing-only dataset just now.

Thanks again for using our data!
Edouard
