### ISSUE TITLE
vaccinations OWID_WRL inconsistencies

### ISSUE THREAD

**Issue by Sikerdebaard** [owid/covid-19-data#397]
Hi all,

Nice work on this dataset. Really appreciate the work on this. :)

I'm noticing some weird values in the total_vaccinations column for OWID_WRL. total_vaccinations -> starts at ~1.5M, then goes to NaN for a couple of days, then goes back to ~1.5M. What is the reason behind this and can we just ffill() this locally?

![image](https://user-images.githubusercontent.com/801853/106253195-79132600-6217-11eb-8480-9098ada8106f.png)

**Comment by edomt** [comment]
Hi @Sikerdebaard 
Thanks! :)

This is due to the fact that no country reported any number on those two days. That's typically a case where we want to make as few assumptions as possible to avoid "creating data". But of course, in that particular case you can indeed fill the missing data pretty safely with `ffill()` or `interpolate("linear")`.
