### ISSUE TITLE
In February 5th update to covid dataset , Sweden's data has reverted to the irregular version where there are many gaps in the reporting of deaths.

### ISSUE THREAD

**Issue by Padraig-Mac-Carthaigh** [owid/covid-19-data#435]
Starting with the Jan 28th update, Sweden's data changed from the irregular pattern of covid  deaths, with most days recording zero deaths,  to  records of the actual dates of death, with a pronounced reporting lag. 

Today (Feb. 5th) the update has reverted to the irregular (but more up-to-date) pattern.

Was this intended, and will it now remain like this?

Pádraig Mac Cárthaigh

**Comment by edomt** [comment]
Hi @Padraig-Mac-Carthaigh 

Indeed, as of yesterday we've gone back to using the data for Sweden as published by Johns Hopkins University—this provides better consistency in our data (and the few days in January when data was completely missing [were patched](https://github.com/CSSEGISandData/COVID-19/pull/3613/files) by the JHU team).

However, we now show the official mortality data for Sweden by date of death [in our dedicated blog post](https://ourworldindata.org/covid-sweden-death-reporting) so that people can compare the two series over time.
