### ISSUE TITLE
Ratio of tests to positive cases

### ISSUE THREAD

**Issue by AJamesPhillips** [owid/covid-19-data#45]
As per [this graph](https://ourworldindata.org/grapher/number-of-covid-19-tests-per-confirmed-case?yScale=log&time=..2020-05-08&country=KOR+GBR+FRA+DEU+USA+NZL), the United Kingdom's ratio is shown as 5.7 as of May 7th
![Screen Shot of our world in data graph of ratio of tests to positive cases showing UK trending up but still only at about 5.7](https://user-images.githubusercontent.com/526509/81496591-93375d80-92b0-11ea-89f6-d4d475461e0a.png)

However the [data source (UK Department of Health and Social Care and Public Health England)](https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public#number-of-cases) shows the ratio at ~12.  With a 14 day moving average it's still about 10.
![Screen Shot of spreadsheet showing uk cases and tests per day and cumulative, their ratio and the 14 day average of that ratio](https://user-images.githubusercontent.com/526509/81496696-5b7ce580-92b1-11ea-9a99-53e52c36b9e3.png)
[Link to spreadsheet](https://docs.google.com/spreadsheets/d/1hI2_1A1Ty5S6r8sY9dzRwM2mLgDvfxQitHGz-_8LHOA/edit?usp=sharing).

I was wondering where the value of 5.7 comes from?  Thank you.

**Comment by edomt** [comment]
Hi @AJamesPhillips 

- This official ratio seems to be calculated by dividing the _daily_ number of cases by the number of tests;
- Our World in Data's ratio is calculated by dividing the _total_ number of cases by the number of tests, since the outbreak started in the country.

Both can be considered valid and relevant metrics, but they describe different aspects of the epidemic and the public health policies in place.

Edouard

**Comment by AJamesPhillips** [comment]
Great thank you so much @edomt .  That makes a lot more sense now.  I'm going to open another issue with a minor suggestion to clarify that in the page title / notes.  Thank you again.
