### ISSUE TITLE
Zero values in vaccination data

### ISSUE THREAD

**Issue by lilyclemson** [owid/covid-19-data#455]
It looks like the values in the vaccination data are cumulative values. Eg. if we have total 100 people vaccinated on day one, 0 people vaccinated on day two, the total vaccination value should still be 100 instead of zero for day two. Can you please make the data more consistent? It will help the downstream analytics works. Thank you

**Comment by lucasrodes** [comment]
Hi @lilyclemson,
What do you mean by "making the data more consistent"? At the moment, precisely, the vaccination data measures cumulative quantities.

**Comment by lilyclemson** [comment]
Hi @lucasrodes ,
Using the example I described above: total 100 people vaccinated on day one and 0 people vaccinated on day two. 
Currently the value of total vaccinated people for day two is zero in vaccination data. The inconsistent here is that the value for day one is cumulative value but the value for day two is not. The value for day two should still be 100 instead. It will make it consistent.

**Comment by edomt** [comment]
Hi @lilyclemson 
I'm not seeing any row that would go from a known value to 0 in our data. Can you specifically mention the file and country where you're seeing this please?

**Comment by lilyclemson** [comment]
![image](https://user-images.githubusercontent.com/11076113/107632067-fab17d80-6c33-11eb-8e68-0d4f4fb7be92.png)

Hi @edomt 
Please see the above screenshot of the vaccination.csv file. Take the total_vaccination column as an example. It looks like the empty spot should have the same value as the previous day instead. Or it can mislead as zero

**Comment by edomt** [comment]
Ok, I understand better, thanks. These cells are not set to 0, they're set to "missing". If you take Argentina for example the value of December 30 was very likely not 700, it was something between 700 and 32013, but we don't know how much because the country didn't report on that day. So we leave it to our users to decide, depending on their use of our data, if they want to:

* Fill that cell with 700 (last observation carried forward)
* Leave it blank (to exclude the row from an analysis or a model)
* Infer the value, for example as 16357 (average between the preceding and next value)

**Comment by lilyclemson** [comment]
I see. We may have to infer the value for downstream analytics. Thank you very much for the info @edomt .
