### ISSUE TITLE
New deaths/ New deaths per million

### ISSUE THREAD

**Issue by givan94** [owid/covid-19-data#476]
Dears, 

I've just noticed that the series new_deaths and new_deaths_per_million contain negative values (see for instance Sweden, Ireland or France among many others). 

How should I interpret these values? Is this a measurement error or a correction?

Thanks in advance!

**Comment by edomt** [comment]
Hi @givan94 

See our README: https://github.com/owid/covid-19-data/tree/master/public/data

**Confirmed cases and deaths:** our data comes from the [COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19) (JHU). We discuss how and when JHU collects and publishes this data [here](https://ourworldindata.org/coronavirus-source-data). The cases & deaths dataset is updated daily. *Note: the number of cases or deaths reported by any institution—including JHU, the WHO, the ECDC and others—on a given day does not necessarily represent the actual number on that date. This is because of the long reporting chain that exists between a new case/death and its inclusion in statistics. **This also means that negative values in cases and deaths can sometimes appear when a country corrects historical data, because it had previously overestimated the number of cases/deaths. Alternatively, large changes can sometimes (although rarely) be made to a country's entire time series if JHU decides (and has access to the necessary data) to correct values retrospectively.***
