### ISSUE TITLE
Data of UAE isn't always visible

### ISSUE THREAD

**Issue by Aric5301** [owid/covid-19-data#488]
When looking at some of the graphs, no data of the UAE is shown although it is selected.
See attached picture for an example.

Thanks!
![image](https://user-images.githubusercontent.com/25414752/107872244-9b60a100-6eb1-11eb-9c05-0f8ef0efba94.png)

**Comment by edomt** [comment]
Hi @Aric5301 

That's because we only have a single data point with this data for the UAE, on January 10. Because of this, it cannot be displayed on our line charts:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/7103774/107954864-4e59f900-6f9d-11eb-8bbe-d0ca8d74424d.png">

For more information, here is what we currently have at our disposal on vaccinations in the UAE:

- The total number of doses administered is reported daily on this official website: https://covid19.ncema.gov.ae/en
- On January 10, it was reported that 250,000 citizens had received their second dose of the vaccine: https://www.khaleejtimes.com/coronavirus-pandemic/covid-vaccine-uae-250000-residents-get-second-dose
- However, since then, we haven't encountered any new information on how many people have received a first or a second dose of the vaccine. On January 25 we asked the UAE National Emergency Crisis and Disaster Management if more people had received their second dose since January 10, but we were told that the data was not currently available publicly.

For now, we are therefore only able to update the number of doses in our data.
