### ISSUE TITLE
zimbabwe march+april data was dropped?

### ISSUE THREAD

**Issue by shadiakiki1986** [owid/covid-19-data#50]
There used to be data for zimbabwe from march 15 till may 4.
Now it's just may 6,7,8.
Was this a mistake?

**Comment by edomt** [comment]
Hi @shadiakiki1986 

The press release for May 6th 2020 reported that 7,808 PCR and 8,244 “rapid screening” tests had been conducted to date. We exclude rapid screening tests from the daily time series that we construct, since we assume that these are antibody tests.

Prior to May 6th 2020, the press releases either: (a) reported a combined cumulative total of PCR and rapid screening tests without providing a breakdown between the two types of tests; or (b) did not clearly specify whether the reported cumulative total was in reference to PCR tests, antibody tests, or both. For this reason, the daily time series we construct begins on May 6th 2020, at which point the press releases began to clearly indicate that the reported cumulative totals only include PCR tests.

Edouard
