### ISSUE TITLE
Day of death != day death reported

### ISSUE THREAD

**Issue by Nettsentrisk** [owid/covid-19-data#58]
Several issues have been closed relating to inconsistencies between a country's daily death numbers and the data that comes from ECDC. The source of the problem is the difference between date death reported and date of death.

Let's take Sweden as an example, which leads to [misleading press reports](https://www.reuters.com/article/us-health-coronavirus-sweden-casualties/sweden-tops-europe-covid-19-deaths-per-capita-over-last-seven-days-idUSKBN22V26A).

Reuters says, based on the data from this repo: 

> While deaths are on the decline Sweden had 6.25 deaths per million inhabitants per day in a rolling seven day average between May 12 and May 19, according to Ourworldinsata.org. That was the highest in Europe and just above the United Kingdom, which had 5.75 deaths per million.

The problem is that for Sweden (and how many other countries?), there is a large difference between the date a death is reported, and when that death actually occurred.

The numbers for daily deaths for the mentioned week, according to the ECDC data:
- May 12: 31
- May 13: 57
- May 14: 147
- May 15: 69
- May 16: 117
- May 17: 28
- May 18: 5
- May 19: 19
Total: 473 (46 per million; 6 per million per day)

The numbers of daily deaths from [Sweden's own health department](https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa) for the same period:
- May 12: 35
- May 13: 21
- May 14: 21
- May 15: 16
- May 16: 10
- May 17: 16
- May 18: 6
- May 19: 1
Total: 126 (12 per million; 2 per million per day)

The difference is almost a factor of 4! 

Now, the reason for the difference is that the ECDC numbers are for how many deaths were reported that day, irrespective of when those deaths actually occurred. Sweden's own numbers are according to which date the death actually occurred. (At this time, they have 23 deaths where they have not gotten a confirmed death date yet.)

When comparing the current trend, aggregated reported numbers that are applied retroactively to previous dates do not give an accurate picture of what is happening during that time.

Sweden is thereby being "punished" in the press reports because of lagging death reports, and makes people believe that the current situation in Sweden is worse than it actually is.

At a minimum this repo should communicate to those who use the data that these numbers are perhaps misleading when it comes to which date the deaths actually occurred, and those who use the numbers should make a point of that.

The only remedy to fix this is for this repo to use primary sources from each country that is based on actual date of death reports, instead of number of deaths reported that day.

This repo and products derived from it are now being misused to mislead the public.

**Comment by Nettsentrisk** [comment]
For sake of comparison, the UK in the same period as mentioned by Reuters, deaths per date as reported by this repo:
- May 12: 210
- May 13: 627
- May 14: 494
- May 15: 428
- May 16: 384
- May 17: 468
- May 18: 170
- May 19: 160
Total: 2941 (44 per million)

As reported by the NHS in the UK, according to date of death:
- May 12: 170
- May 13: 145
- May 14: 159
- May 15: 137
- May 16: 125
- May 17: 94
- May 18: 29
- May 19: N/A
Total: 859 (13 per million)

In each case, for both Sweden and UK, they warn that the numbers for the last 5 days should not be seen as final.

**Comment by w4sevens** [comment]
so what?

**Comment by edomt** [comment]
Hi @Nettsentrisk,

We agree that this is not ideal. However, we don't believe that it's accurate to say "this repo and products derived from it are now being misused to mislead the public." I'll try to outline why here.

First, in your issue you compare for May 12th-19th the number of deaths as reported by the ECDC and as reported by the Swedish health department, and conclude that "the difference is almost a factor of 4". However, this won't stay true: Sweden will correct this data retroactively, so those numbers will increase a lot in their time series, while they'll stay the same on the ECDC side. In fact, since you posted this 11 hours ago, the total on the Swedish side has already increased from 126 to 186.

More generally, updates that are done following the "ECDC method" shouldn't really show a significant lag compared to the "retroactive updates" method, unless the country suffers from a huge lag in reporting. There will indeed be a bit of a lag (a few days probably), but that's one of the reasons why we caution our readers against drawing conclusions based on daily data. We think that they should instead look at more long-term metrics such as 7-day rolling averages, which we make available on our site.

Another thing to take into account is that organizations like the ECDC, WHO, JHU, are very conscious of their role as data providers during this pandemic. This means that they aim for stability in their data, and they avoid as much as possible (or even completely) going back and changing past days, as the many people/applications/dashboards/etc. relying on their data wouldn't necessarily notice these changes and handle them correctly.

Yet another issue is that while it's easy for one country to correct past figures in a time series on its own website, it would be much harder for an international organization that receives data from 200+ countries to accept retroactive changes—their job is therefore made a lot easier by simply telling countries to send data corrections as if they were "blocks" of cases or deaths that appear on a given day.

Finally, when you write that:

> The only remedy to fix this is for this repo to use primary sources from each country that is based on actual date of death reports, instead of number of deaths reported that day.

I think you tend to overestimate the resources at our disposal. _Our World in Data_ is a non-profit organization of 10 full-time employees, and the system you're describing isn't at all something we'd be able to take on. We rely on [donations](https://ourworldindata.org/donate) and grants to keep us going, so of course we'd welcome any financial help that would allow us to hire more people 🙂

I'll rediscuss with the team whether we can make it clearer on our site and/or on this repo that the ECDC reports in this way.

I hope this answers your questions.

Best,
Edouard

**Comment by Nettsentrisk** [comment]
> However, this won't stay true: Sweden will correct this data retroactively, so those numbers will increase a lot in their time series, while they'll stay the same on the ECDC side. In fact, since you posted this 11 hours ago, the total on the Swedish side has already increased from 126 to 186.

That's true, which is why I said, "In each case, for both Sweden and UK, they warn that the numbers for the last 5 days should not be seen as final." My point is that the discrepancy will be quite a bit off between "deaths by death date" and "deaths by reported date". Many people believe that they are getting the former when they are actually getting the latter. This is also how the press tends to report it, by conflating the two.

I fully appreciate that producing "deaths by death date" probably isn't feasible, but as you're indicating, there needs to be greater awareness about what these numbers actually show.

If one were able to get the "deaths by death date" numbers properly from somewhere, there would need to be a warning that these numbers can be updated retroactively and that the last ~5 days in the series should be seen as unfinished.

The Swedish public broadcaster [SVT does this](https://www.svt.se/datajournalistik/har-sprider-sig-coronaviruset/) by showing bar graphs of the numbers with the last 5 days in the series greyed out and with a legend that states that the numbers are not final.

My intent was to flag the fact that your numbers are being misunderstood and misused by various parties out there, first and foremost of importance is the news media, which has the potential to mislead quite a lot of people.
