### ISSUE TITLE
Automated git commit for vaccinations

### ISSUE THREAD

**Issue by adamredfern92** [owid/covid-19-data#586]
Hi @edomt

Is there any chance of automating the vaccination updates for the locations that are scripted like has been done with US vaccination data? It would be great if it could be run twice a day as I know you normally do the update in the morning, but as countries report numbers throughout the day I often get requests asking for some countries data to be updated in the afternoon and evening.

Thanks, appreciate all the hard work!

**Comment by edomt** [comment]
Hi @adamredfern92 

I don't think we'll be able to do this for now - there are a few different things that need to be executed correctly for the global vaccination update. Some of it is indeed automated but even these automations break fairly often because of changes in how countries publish their data.

So overall, given that our resources are already really stretched and that in our current system a country will be updated on average 12 hours after the data is published, I think that for now we'll stay at 1 update per day (& of course potential corrections later in the day if needed).

**Comment by adamredfern92** [comment]
Ok no worries, I figured that would probably be the case but thought I would check. It tends to be the same few countries that people ask for so I can look at doing them from my end if needs be. Thanks
