### ISSUE TITLE
Spain negative new cases

### ISSUE THREAD

**Issue by mercedeslga** [owid/covid-19-data#608]
Hi!!

How come that Spain last new cases (march 2nd) is a negative number?? It would be impossible, right?

Thank you!

**Comment by edomt** [comment]
Hi @mercedeslga 

We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues

**Comment by DColadas** [comment]
The Spanish Ministry of Health [reported that](https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Actualizacion_323_COVID-19.pdf) the reason for the negative number of new cases is due to the removal of duplicate cases in Catalonia (some cases were assigned two different IDs by the computer system). I remember a similar adjustment made back in May.

**Comment by Mellyorawalker1** [comment]
Mellyora walker
