### ISSUE TITLE
Vaccination data Netherlands

### ISSUE THREAD

**Issue by Sikerdebaard** [owid/covid-19-data#628]
Hi all,

Looks like the scraper for the Netherlands data was updated to scrape the data from the weekly reports from the RIVM. This report contains a combination of estimated and reported numbers and the scraper currently does not distinguish between the two.

1. In the past, it was decided not to use the estimated numbers and only use reported numbers. Has this rule changed?
2. The table from the pdf is available in HTML form on this page. This might be easier to scrape should the pdf scraper become unstable. https://www.rivm.nl/covid-19-vaccinatie/cijfers-vaccinatieprogramma

**Comment by Azzeo** [comment]
It would be more useful to scrape from the (official) [Dutch COVID-19 dashboard](https://coronadashboard.government.nl/landelijk/vaccinaties): see "Number of doses administered" since it's updated daily. Either using the calculated number or the reported number. Using the calculated number would be more representative of the real situation, since reporting lags behind severely. Not 100% sure but the European CDC seems to use the calculated number: https://qap.ecdc.europa.eu/public/extensions/COVID-19/vaccine-tracker.html#uptake-tab. Otherwise the Netherlands would've been at the bottom of vaccine uptake if the reported number was used.

**Comment by ebosveld** [comment]
> It would be more useful to scrape from the (official) [Dutch COVID-19 dashboard](https://coronadashboard.government.nl/landelijk/vaccinaties): see "Number of doses administered" since it's updated daily. Either using the calculated number or the reported number. Using the calculated number would be more representative of the real situation, since reporting lags behind severely. Not 100% sure but the European CDC seems to use the calculated number: https://qap.ecdc.europa.eu/public/extensions/COVID-19/vaccine-tracker.html#uptake-tab. Otherwise the Netherlands would've been at the bottom of vaccine uptake if the reported number was used.

Yes, but as @edomt said in his commit: this doesn't give information about 1st and 2nd dose. Interestingly enough he was against using the RIVM weekly reports in #469, so I don't know what made him change his mind.

**Comment by edomt** [comment]
Hi everyone — and thanks for opening this issue.

In case that's not obvious, I'll start by saying that the reporting on vaccinations by the Dutch government has been extremely poor so far. The current situation makes very little sense, and we're forced to find a suboptimal compromise to publish the best data at our disposal.

* The [official dashboard](https://coronadashboard.rijksoverheid.nl/landelijk/vaccinaties) is updated daily, but doesn't include any breakdown of 1st & 2nd doses, and introduces this very confusing distinction between "estimated" and "reported" doses — which, 2 months after the vaccination campaign started, is a little hard to understand.

* The [RIVM reports](https://www.rivm.nl/covid-19-vaccinatie/cijfers-vaccinatieprogramma) do include a breakdown of doses, but they are only published weekly, and they mention the "estimated number" from the dashboard as the official statistics.

* My understanding, based on the _many_ emails we get about this every day, is that the Dutch government always uses that "estimated number" in its public communication. It's also the one that's reported by the ECDC [in its tracker of European vaccination](https://qap.ecdc.europa.eu/public/extensions/COVID-19/vaccine-tracker.html#uptake-tab).

Based on all this, we'll use the weekly RIVM reports for now (although we'll switch to collecting them from the HTML table as suggested by @Sikerdebaard), because 1st/2nd dose breakdown is a more important piece of information to have right now than daily-updated data only on doses.

(@ebosveld: my comment in #469 was merely about the fact that our small "parallel" dataset on doses by manufacturer is only based on full time series, rather than separate numbers pieced together.)

**Comment by EwoutH** [comment]
To add to this: The source data used on the [dashboard](https://coronadashboard.government.nl/landelijk/vaccinaties) is also available on https://data.rivm.nl/covid-19/. It's updated daily at exactly 15:15 (local time). The file is called `COVID-19_vaccinatiegraad_per_gemeente_per_week_leeftijd` and available in both CSV and JSON formats. Meta data is available from the HTML file with the same name ([here](https://data.rivm.nl/meta/srv/eng/catalog.search#/metadata/205d0bf4-b645-4e5b-84bc-f8ec482fd3f3?tab=relations)). 

Using the source data might be more reliable than using a web scraper to get the data from the dashboard.
