### ISSUE TITLE
Saudi Arabia negative cases

### ISSUE THREAD

**Issue by msgoussi** [owid/covid-19-data#644]
Please advise.
![image](https://user-images.githubusercontent.com/18138496/110235999-7b6a4d80-7f44-11eb-9e87-95d2d60a4fae.png)

**Comment by edomt** [comment]
We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues 

Note: the number of cases or deaths reported by any institution—including JHU, the WHO, the ECDC and others—on a given day does not necessarily represent the actual number on that date. This is because of the long reporting chain that exists between a new case/death and its inclusion in statistics. This also means that negative values in cases and deaths can sometimes appear when a country corrects historical data, because it had previously overestimated the number of cases/deaths.

**Comment by msgoussi** [comment]
Hi. I am talking about vaccination not confirmed or death cases. Sorry for misleading you. The cumulative number went down on March 05 compared to number of March 04.

**Comment by edomt** [comment]
It seems this has been fixed by the Saudi government — our update this morning removed that negative change.
