### ISSUE TITLE
Numbers in "people_vaccinated" are not consistently increasing

### ISSUE THREAD

**Issue by sakshamsoni97** [owid/covid-19-data#698]
Hi,

I assumed that the numbers in the people_vaccinated column were cumulative number of people vaccinated and hence would be non-decreasing (ignoring the days when numbers are not reported). But on certain days in the data they are less than the previous day. One example is Arizona from March 7th - March 8th. There are other instances I can provide and it happens with people_fully_vaccinated as well.

Is there some gap in my understanding of the data or could that be a bug?

**Comment by edomt** [comment]
Hi @sakshamsoni97 

This was due to a change in the CDC's methodology. This has been really well documented by the team taking care of the Bloomberg tracker here: https://www.bloomberg.com/news/live-blog/2021-01-21/methodology-and-analysis-for-the-covid-19-vaccine-tracker#60319089B2240006

More technically, in the CDC data this change consisted in adding a new column with the new method. From February 20 to March 7, both columns (old and new) were present. Then on March 8 the CDC completely removed the old method.

Until now, for the overlap period (from February 21 to March 7) our script selected the column with the old method (variables `Administered_Dose1` and `Administered_Dose2`). I've now changed this, so that the new variables (`Administered_Dose1_Recip` and `Administered_Dose2_Recip`) are used as soon as they appear in the files in February. However, this still means that around February 21, there will be a negative change in `people_vaccinated` in some states, due to this change by the CDC.

**Comment by free-soellingeraj** [comment]
Thank you!

**Comment by free-soellingeraj** [comment]
The effective date of the CDC policy change impacting the OWID dataset are not all the same so it complicates comparisons between state vaccine regimes. 
Currently, I measure the effect of this policy change by looking for instances where the change-over was substantial enough to cause the `people_vaccinated` to be less than it was the day before the policy change.  For the states where the series becomes non-monotonic, that day most certainly was the start and it makes sense that D.C. would experience a large change given it is the largest concentration of federal employees relative to population.  However, that is most likely not the extent of the effect -- other states may have had more subtle while still significant impacts.  Has anyone developed better methodologies for quantifying the impact of the policy change?

**Comment by free-soellingeraj** [comment]
As I look more, it would be really helpful to know the dates each state took effect, or at least the date the first state was effected by the CDC change.  I didn't see that in the bloomberg article.  Does anyone know it?
