### ISSUE TITLE
Negative values for New Confirmed Cases

### ISSUE THREAD

**Issue by amirhome61** [owid/covid-19-data#747]
FIle: owid-covid-data.xlsx
The fields new confirmed, new confirmed smoothed, new confirmed per million and new confirmed per million smoothed have negative values for the following countries: France, Luxembourg, Spain

Thanks for addressing this

Amir

**Comment by edomt** [comment]
We source our data on COVID-19 confirmed cases and deaths from the COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University: https://github.com/CSSEGISandData/COVID-19.
This page also lists their sources, country by country.
We report this data without alterations, but issues can be raised in their GitHub repository: https://github.com/CSSEGISandData/COVID-19/issues 

Note: the number of cases or deaths reported by any institution—including JHU, the WHO, the ECDC and others—on a given day does not necessarily represent the actual number on that date. This is because of the long reporting chain that exists between a new case/death and its inclusion in statistics. This also means that negative values in cases and deaths can sometimes appear when a country corrects historical data, because it had previously overestimated the number of cases/deaths.
