### ISSUE TITLE
Croatia daily testing data not updated since March 7th

### ISSUE THREAD

**Issue by Nufflee** [owid/covid-19-data#791]
Hi, I've noticed that Croatia's `new_tests` column has not been updated since March 7th. The `total_tests` column seems to be updated every few days though, and I imagine `positive_rate` data is extrapolated from it too.
I believe that the reason for this is that the government's website (https://www.koronavirus.hr/) now uses Cloudflare Anti-DDOS protection which makes all non-Croatian IPs need to pass a browser check/anti-bot challenge. Since your [data collection script](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automations/incremental/croatia.R) cannot pass this challenge, it keeps failing and never adds new data.

I've tried to bypass this myself for quite a bit but I don't think there is a straightforward solution. The only other daily-updated source of this information from the Croatian government that I know of is their [Twitter page](https://twitter.com/koronavirus_hr?lang=en) but scraping that will probably be a bit more challenging. I'm not aware of any other sources but if I find any, I will let you know.

Also, what is your source for the cumulative test count (`total_tests` column) since it is being updated regardless of missing data in the `new_tests` column, and why does it only updated occasionally, at irregular intervals?

**Comment by Nufflee** [comment]
Upon inspecting the code closer, I realized that the data collection script actually collects the cumulative number of tests, not the new tests. Since that has been updating, I'm not sure what the issue with `new_tests` may be then. 
It's also curious that you're able to get past the Cloudflare check while my Python script wasn't.

**Comment by edomt** [comment]
Hi @Nufflee 

I'm not sure about the Cloudflare check, but our script that collects this data is _supposed_ to run daily to collect `total_tests`. There were a few issues recently, such that the total was only collected twice a week (when we actually update our testing dataset). These issues are now solved, and `total_tests` should be collected daily.

`new_tests` represents the daily difference between `total_tests`, but it's only calculated for consecutive days. This is why it has been missing a lot recently, since `total_tests` was not consistently recorded.

If you need a measure of daily tests that is complete, you can use `new_tests_smoothed`. To calculate this, for countries that don't report testing data on a daily basis, we assume that testing changed equally on a daily basis over any periods in which no data was reported. This produces a complete series of daily figures, which is then averaged over a rolling 7-day window.
