### ISSUE TITLE
Strange number of new_detahs on 2020-05-25

### ISSUE THREAD

**Issue by otavio-s-s** [owid/covid-19-data#84]
Hello!

Thank you for the great dataset.

I noticed that the number of new deaths on May 25th is strange. It shows 816 new deaths. It's not only a very small number comparing with the other days, but Brazil and the US had over 600 deaths each in the same day.

I think this happened in the last update as my analyses were not showing such a discrepancy yesterday.

**Comment by edomt** [comment]
Hi @otavio-s-s 

On that day, Spain reported a large *negative* number of deaths (–1918), which was a data correction due to a previous over counting of deaths. This results in the global number of new deaths for May 25th to be only 816, while indeed both Brazil and the US by themselves reported over 600 deaths.

Edouard
